
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model UserRole
 * 
 */
export type UserRole = Prisma.UserRoleModel
/**
 * Model AdminUserProfile
 * 
 */
export type AdminUserProfile = Prisma.AdminUserProfileModel
/**
 * Model AccountInfo
 * 
 */
export type AccountInfo = Prisma.AccountInfoModel
/**
 * Model Bank
 * 
 */
export type Bank = Prisma.BankModel
/**
 * Model Biodata
 * 
 */
export type Biodata = Prisma.BiodataModel
/**
 * Model OtpVerification
 * 
 */
export type OtpVerification = Prisma.OtpVerificationModel
/**
 * Model Savings
 * 
 */
export type Savings = Prisma.SavingsModel
/**
 * Model PersonalSavingsPlan
 * 
 */
export type PersonalSavingsPlan = Prisma.PersonalSavingsPlanModel
/**
 * Model PersonalSavings
 * 
 */
export type PersonalSavings = Prisma.PersonalSavingsModel
/**
 * Model Shares
 * 
 */
export type Shares = Prisma.SharesModel
/**
 * Model LoanType
 * 
 */
export type LoanType = Prisma.LoanTypeModel
/**
 * Model Loan
 * 
 */
export type Loan = Prisma.LoanModel
/**
 * Model LoanSchedule
 * 
 */
export type LoanSchedule = Prisma.LoanScheduleModel
/**
 * Model BulkRepaymentUpload
 * 
 */
export type BulkRepaymentUpload = Prisma.BulkRepaymentUploadModel
/**
 * Model LoanRepayment
 * 
 */
export type LoanRepayment = Prisma.LoanRepaymentModel
/**
 * Model LoanStatusHistory
 * 
 */
export type LoanStatusHistory = Prisma.LoanStatusHistoryModel
/**
 * Model Request
 * 
 */
export type Request = Prisma.RequestModel
/**
 * Model RequestApproval
 * 
 */
export type RequestApproval = Prisma.RequestApprovalModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Transaction
 * 
 */
export type Transaction = Prisma.TransactionModel
/**
 * Model SystemSettings
 * 
 */
export type SystemSettings = Prisma.SystemSettingsModel
/**
 * Model SystemSettingsHistory
 * 
 */
export type SystemSettingsHistory = Prisma.SystemSettingsHistoryModel
