
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const MembershipStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  RESIGNED: 'RESIGNED',
  TERMINATED: 'TERMINATED'
} as const

export type MembershipStatus = (typeof MembershipStatus)[keyof typeof MembershipStatus]


export const AccountStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  CLOSED: 'CLOSED'
} as const

export type AccountStatus = (typeof AccountStatus)[keyof typeof AccountStatus]


export const TransactionType = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT',
  SAVINGS_DEPOSIT: 'SAVINGS_DEPOSIT',
  SAVINGS_WITHDRAWAL: 'SAVINGS_WITHDRAWAL',
  SAVINGS_INTEREST: 'SAVINGS_INTEREST',
  SHARES_PURCHASE: 'SHARES_PURCHASE',
  SHARES_LIQUIDATION: 'SHARES_LIQUIDATION',
  SHARES_DIVIDEND: 'SHARES_DIVIDEND',
  LOAN_DISBURSEMENT: 'LOAN_DISBURSEMENT',
  LOAN_REPAYMENT: 'LOAN_REPAYMENT',
  LOAN_INTEREST: 'LOAN_INTEREST',
  LOAN_PENALTY: 'LOAN_PENALTY',
  FEE: 'FEE',
  REVERSAL: 'REVERSAL',
  ADJUSTMENT: 'ADJUSTMENT',
  PERSONAL_SAVINGS_DEPOSIT: 'PERSONAL_SAVINGS_DEPOSIT',
  PERSONAL_SAVINGS_WITHDRAWAL: 'PERSONAL_SAVINGS_WITHDRAWAL'
} as const

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType]


export const TransactionStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REVERSED: 'REVERSED',
  CANCELLED: 'CANCELLED'
} as const

export type TransactionStatus = (typeof TransactionStatus)[keyof typeof TransactionStatus]


export const TransactionModule = {
  SAVINGS: 'SAVINGS',
  SHARES: 'SHARES',
  LOAN: 'LOAN',
  SYSTEM: 'SYSTEM',
  ADMIN: 'ADMIN'
} as const

export type TransactionModule = (typeof TransactionModule)[keyof typeof TransactionModule]


export const RequestType = {
  LOAN_APPLICATION: 'LOAN_APPLICATION',
  SAVINGS_WITHDRAWAL: 'SAVINGS_WITHDRAWAL',
  ACCOUNT_CLOSURE: 'ACCOUNT_CLOSURE',
  BIODATA_UPDATE: 'BIODATA_UPDATE',
  ACCOUNT_CREATION: 'ACCOUNT_CREATION',
  ACCOUNT_UPDATE: 'ACCOUNT_UPDATE',
  ACCOUNT_VERIFICATION: 'ACCOUNT_VERIFICATION',
  PERSONAL_SAVINGS_CREATION: 'PERSONAL_SAVINGS_CREATION',
  PERSONAL_SAVINGS_WITHDRAWAL: 'PERSONAL_SAVINGS_WITHDRAWAL',
  LOAN_DISBURSEMENT: 'LOAN_DISBURSEMENT',
  BULK_UPLOAD: 'BULK_UPLOAD',
  SYSTEM_ADJUSTMENT: 'SYSTEM_ADJUSTMENT'
} as const

export type RequestType = (typeof RequestType)[keyof typeof RequestType]


export const RequestStatus = {
  PENDING: 'PENDING',
  IN_REVIEW: 'IN_REVIEW',
  REVIEWED: 'REVIEWED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED'
} as const

export type RequestStatus = (typeof RequestStatus)[keyof typeof RequestStatus]


export const RequestModule = {
  LOAN: 'LOAN',
  SAVINGS: 'SAVINGS',
  SHARES: 'SHARES',
  ACCOUNT: 'ACCOUNT',
  SYSTEM: 'SYSTEM'
} as const

export type RequestModule = (typeof RequestModule)[keyof typeof RequestModule]


export const RequestPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
} as const

export type RequestPriority = (typeof RequestPriority)[keyof typeof RequestPriority]


export const ApprovalStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SKIPPED: 'SKIPPED'
} as const

export type ApprovalStatus = (typeof ApprovalStatus)[keyof typeof ApprovalStatus]


export const LoanStatus = {
  PENDING: 'PENDING',
  IN_REVIEW: 'IN_REVIEW',
  REVIEWED: 'REVIEWED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  DISBURSED: 'DISBURSED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  DEFAULTED: 'DEFAULTED'
} as const

export type LoanStatus = (typeof LoanStatus)[keyof typeof LoanStatus]


export const PaymentStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PARTIAL: 'PARTIAL',
  LATE: 'LATE',
  OVERDUE: 'OVERDUE',
  WAIVED: 'WAIVED'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]


export const NotificationType = {
  TRANSACTION: 'TRANSACTION',
  REQUEST_UPDATE: 'REQUEST_UPDATE',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
  ACCOUNT_UPDATE: 'ACCOUNT_UPDATE'
} as const

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType]


export const NotificationPriority = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
} as const

export type NotificationPriority = (typeof NotificationPriority)[keyof typeof NotificationPriority]


export const UploadStatus = {
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  PARTIALLY_COMPLETED: 'PARTIALLY_COMPLETED',
  CANCELLED: 'CANCELLED'
} as const

export type UploadStatus = (typeof UploadStatus)[keyof typeof UploadStatus]


export const PersonalSavingsStatus = {
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
  SUSPENDED: 'SUSPENDED',
  PENDING: 'PENDING'
} as const

export type PersonalSavingsStatus = (typeof PersonalSavingsStatus)[keyof typeof PersonalSavingsStatus]
