
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Role'
export type * from './models/UserRole'
export type * from './models/AdminUserProfile'
export type * from './models/AccountInfo'
export type * from './models/Bank'
export type * from './models/Biodata'
export type * from './models/OtpVerification'
export type * from './models/Savings'
export type * from './models/PersonalSavingsPlan'
export type * from './models/PersonalSavings'
export type * from './models/Shares'
export type * from './models/LoanType'
export type * from './models/Loan'
export type * from './models/LoanSchedule'
export type * from './models/BulkRepaymentUpload'
export type * from './models/LoanRepayment'
export type * from './models/LoanStatusHistory'
export type * from './models/Request'
export type * from './models/RequestApproval'
export type * from './models/Notification'
export type * from './models/Session'
export type * from './models/Transaction'
export type * from './models/SystemSettings'
export type * from './models/SystemSettingsHistory'
export type * from './models/Cooperative'
export type * from './commonInputTypes'