
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AccountInfo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AccountInfo
 * 
 */
export type AccountInfoModel = runtime.Types.Result.DefaultSelection<Prisma.$AccountInfoPayload>

export type AggregateAccountInfo = {
  _count: AccountInfoCountAggregateOutputType | null
  _min: AccountInfoMinAggregateOutputType | null
  _max: AccountInfoMaxAggregateOutputType | null
}

export type AccountInfoMinAggregateOutputType = {
  id: string | null
  biodataId: string | null
  bankId: string | null
  accountNumber: string | null
  bvn: string | null
  accountName: string | null
  isVerified: boolean | null
  verificationDate: Date | null
  verifiedBy: string | null
}

export type AccountInfoMaxAggregateOutputType = {
  id: string | null
  biodataId: string | null
  bankId: string | null
  accountNumber: string | null
  bvn: string | null
  accountName: string | null
  isVerified: boolean | null
  verificationDate: Date | null
  verifiedBy: string | null
}

export type AccountInfoCountAggregateOutputType = {
  id: number
  biodataId: number
  bankId: number
  accountNumber: number
  bvn: number
  accountName: number
  isVerified: number
  verificationDate: number
  verifiedBy: number
  _all: number
}


export type AccountInfoMinAggregateInputType = {
  id?: true
  biodataId?: true
  bankId?: true
  accountNumber?: true
  bvn?: true
  accountName?: true
  isVerified?: true
  verificationDate?: true
  verifiedBy?: true
}

export type AccountInfoMaxAggregateInputType = {
  id?: true
  biodataId?: true
  bankId?: true
  accountNumber?: true
  bvn?: true
  accountName?: true
  isVerified?: true
  verificationDate?: true
  verifiedBy?: true
}

export type AccountInfoCountAggregateInputType = {
  id?: true
  biodataId?: true
  bankId?: true
  accountNumber?: true
  bvn?: true
  accountName?: true
  isVerified?: true
  verificationDate?: true
  verifiedBy?: true
  _all?: true
}

export type AccountInfoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccountInfo to aggregate.
   */
  where?: Prisma.AccountInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountInfos to fetch.
   */
  orderBy?: Prisma.AccountInfoOrderByWithRelationInput | Prisma.AccountInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccountInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AccountInfos
  **/
  _count?: true | AccountInfoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccountInfoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccountInfoMaxAggregateInputType
}

export type GetAccountInfoAggregateType<T extends AccountInfoAggregateArgs> = {
      [P in keyof T & keyof AggregateAccountInfo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccountInfo[P]>
    : Prisma.GetScalarType<T[P], AggregateAccountInfo[P]>
}




export type AccountInfoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountInfoWhereInput
  orderBy?: Prisma.AccountInfoOrderByWithAggregationInput | Prisma.AccountInfoOrderByWithAggregationInput[]
  by: Prisma.AccountInfoScalarFieldEnum[] | Prisma.AccountInfoScalarFieldEnum
  having?: Prisma.AccountInfoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccountInfoCountAggregateInputType | true
  _min?: AccountInfoMinAggregateInputType
  _max?: AccountInfoMaxAggregateInputType
}

export type AccountInfoGroupByOutputType = {
  id: string
  biodataId: string
  bankId: string
  accountNumber: string
  bvn: string
  accountName: string
  isVerified: boolean
  verificationDate: Date | null
  verifiedBy: string | null
  _count: AccountInfoCountAggregateOutputType | null
  _min: AccountInfoMinAggregateOutputType | null
  _max: AccountInfoMaxAggregateOutputType | null
}

export type GetAccountInfoGroupByPayload<T extends AccountInfoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccountInfoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccountInfoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccountInfoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccountInfoGroupByOutputType[P]>
      }
    >
  >



export type AccountInfoWhereInput = {
  AND?: Prisma.AccountInfoWhereInput | Prisma.AccountInfoWhereInput[]
  OR?: Prisma.AccountInfoWhereInput[]
  NOT?: Prisma.AccountInfoWhereInput | Prisma.AccountInfoWhereInput[]
  id?: Prisma.UuidFilter<"AccountInfo"> | string
  biodataId?: Prisma.UuidFilter<"AccountInfo"> | string
  bankId?: Prisma.UuidFilter<"AccountInfo"> | string
  accountNumber?: Prisma.StringFilter<"AccountInfo"> | string
  bvn?: Prisma.StringFilter<"AccountInfo"> | string
  accountName?: Prisma.StringFilter<"AccountInfo"> | string
  isVerified?: Prisma.BoolFilter<"AccountInfo"> | boolean
  verificationDate?: Prisma.DateTimeNullableFilter<"AccountInfo"> | Date | string | null
  verifiedBy?: Prisma.UuidNullableFilter<"AccountInfo"> | string | null
  bank?: Prisma.XOR<Prisma.BankScalarRelationFilter, Prisma.BankWhereInput>
  biodata?: Prisma.XOR<Prisma.BiodataScalarRelationFilter, Prisma.BiodataWhereInput>
}

export type AccountInfoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  biodataId?: Prisma.SortOrder
  bankId?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  bvn?: Prisma.SortOrder
  accountName?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  verificationDate?: Prisma.SortOrderInput | Prisma.SortOrder
  verifiedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  bank?: Prisma.BankOrderByWithRelationInput
  biodata?: Prisma.BiodataOrderByWithRelationInput
}

export type AccountInfoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  biodataId_bankId?: Prisma.AccountInfoBiodataIdBankIdCompoundUniqueInput
  AND?: Prisma.AccountInfoWhereInput | Prisma.AccountInfoWhereInput[]
  OR?: Prisma.AccountInfoWhereInput[]
  NOT?: Prisma.AccountInfoWhereInput | Prisma.AccountInfoWhereInput[]
  biodataId?: Prisma.UuidFilter<"AccountInfo"> | string
  bankId?: Prisma.UuidFilter<"AccountInfo"> | string
  accountNumber?: Prisma.StringFilter<"AccountInfo"> | string
  bvn?: Prisma.StringFilter<"AccountInfo"> | string
  accountName?: Prisma.StringFilter<"AccountInfo"> | string
  isVerified?: Prisma.BoolFilter<"AccountInfo"> | boolean
  verificationDate?: Prisma.DateTimeNullableFilter<"AccountInfo"> | Date | string | null
  verifiedBy?: Prisma.UuidNullableFilter<"AccountInfo"> | string | null
  bank?: Prisma.XOR<Prisma.BankScalarRelationFilter, Prisma.BankWhereInput>
  biodata?: Prisma.XOR<Prisma.BiodataScalarRelationFilter, Prisma.BiodataWhereInput>
}, "id" | "biodataId_bankId">

export type AccountInfoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  biodataId?: Prisma.SortOrder
  bankId?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  bvn?: Prisma.SortOrder
  accountName?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  verificationDate?: Prisma.SortOrderInput | Prisma.SortOrder
  verifiedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AccountInfoCountOrderByAggregateInput
  _max?: Prisma.AccountInfoMaxOrderByAggregateInput
  _min?: Prisma.AccountInfoMinOrderByAggregateInput
}

export type AccountInfoScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccountInfoScalarWhereWithAggregatesInput | Prisma.AccountInfoScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccountInfoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccountInfoScalarWhereWithAggregatesInput | Prisma.AccountInfoScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"AccountInfo"> | string
  biodataId?: Prisma.UuidWithAggregatesFilter<"AccountInfo"> | string
  bankId?: Prisma.UuidWithAggregatesFilter<"AccountInfo"> | string
  accountNumber?: Prisma.StringWithAggregatesFilter<"AccountInfo"> | string
  bvn?: Prisma.StringWithAggregatesFilter<"AccountInfo"> | string
  accountName?: Prisma.StringWithAggregatesFilter<"AccountInfo"> | string
  isVerified?: Prisma.BoolWithAggregatesFilter<"AccountInfo"> | boolean
  verificationDate?: Prisma.DateTimeNullableWithAggregatesFilter<"AccountInfo"> | Date | string | null
  verifiedBy?: Prisma.UuidNullableWithAggregatesFilter<"AccountInfo"> | string | null
}

export type AccountInfoCreateInput = {
  id?: string
  accountNumber: string
  bvn: string
  accountName: string
  isVerified?: boolean
  verificationDate?: Date | string | null
  verifiedBy?: string | null
  bank: Prisma.BankCreateNestedOneWithoutAccountsInput
  biodata: Prisma.BiodataCreateNestedOneWithoutAccountInfoInput
}

export type AccountInfoUncheckedCreateInput = {
  id?: string
  biodataId: string
  bankId: string
  accountNumber: string
  bvn: string
  accountName: string
  isVerified?: boolean
  verificationDate?: Date | string | null
  verifiedBy?: string | null
}

export type AccountInfoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  bvn?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  verificationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verifiedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bank?: Prisma.BankUpdateOneRequiredWithoutAccountsNestedInput
  biodata?: Prisma.BiodataUpdateOneRequiredWithoutAccountInfoNestedInput
}

export type AccountInfoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  biodataId?: Prisma.StringFieldUpdateOperationsInput | string
  bankId?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  bvn?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  verificationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verifiedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AccountInfoCreateManyInput = {
  id?: string
  biodataId: string
  bankId: string
  accountNumber: string
  bvn: string
  accountName: string
  isVerified?: boolean
  verificationDate?: Date | string | null
  verifiedBy?: string | null
}

export type AccountInfoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  bvn?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  verificationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verifiedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AccountInfoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  biodataId?: Prisma.StringFieldUpdateOperationsInput | string
  bankId?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  bvn?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  verificationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verifiedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AccountInfoBiodataIdBankIdCompoundUniqueInput = {
  biodataId: string
  bankId: string
}

export type AccountInfoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  biodataId?: Prisma.SortOrder
  bankId?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  bvn?: Prisma.SortOrder
  accountName?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  verificationDate?: Prisma.SortOrder
  verifiedBy?: Prisma.SortOrder
}

export type AccountInfoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  biodataId?: Prisma.SortOrder
  bankId?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  bvn?: Prisma.SortOrder
  accountName?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  verificationDate?: Prisma.SortOrder
  verifiedBy?: Prisma.SortOrder
}

export type AccountInfoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  biodataId?: Prisma.SortOrder
  bankId?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  bvn?: Prisma.SortOrder
  accountName?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  verificationDate?: Prisma.SortOrder
  verifiedBy?: Prisma.SortOrder
}

export type AccountInfoListRelationFilter = {
  every?: Prisma.AccountInfoWhereInput
  some?: Prisma.AccountInfoWhereInput
  none?: Prisma.AccountInfoWhereInput
}

export type AccountInfoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AccountInfoCreateNestedManyWithoutBankInput = {
  create?: Prisma.XOR<Prisma.AccountInfoCreateWithoutBankInput, Prisma.AccountInfoUncheckedCreateWithoutBankInput> | Prisma.AccountInfoCreateWithoutBankInput[] | Prisma.AccountInfoUncheckedCreateWithoutBankInput[]
  connectOrCreate?: Prisma.AccountInfoCreateOrConnectWithoutBankInput | Prisma.AccountInfoCreateOrConnectWithoutBankInput[]
  createMany?: Prisma.AccountInfoCreateManyBankInputEnvelope
  connect?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
}

export type AccountInfoUncheckedCreateNestedManyWithoutBankInput = {
  create?: Prisma.XOR<Prisma.AccountInfoCreateWithoutBankInput, Prisma.AccountInfoUncheckedCreateWithoutBankInput> | Prisma.AccountInfoCreateWithoutBankInput[] | Prisma.AccountInfoUncheckedCreateWithoutBankInput[]
  connectOrCreate?: Prisma.AccountInfoCreateOrConnectWithoutBankInput | Prisma.AccountInfoCreateOrConnectWithoutBankInput[]
  createMany?: Prisma.AccountInfoCreateManyBankInputEnvelope
  connect?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
}

export type AccountInfoUpdateManyWithoutBankNestedInput = {
  create?: Prisma.XOR<Prisma.AccountInfoCreateWithoutBankInput, Prisma.AccountInfoUncheckedCreateWithoutBankInput> | Prisma.AccountInfoCreateWithoutBankInput[] | Prisma.AccountInfoUncheckedCreateWithoutBankInput[]
  connectOrCreate?: Prisma.AccountInfoCreateOrConnectWithoutBankInput | Prisma.AccountInfoCreateOrConnectWithoutBankInput[]
  upsert?: Prisma.AccountInfoUpsertWithWhereUniqueWithoutBankInput | Prisma.AccountInfoUpsertWithWhereUniqueWithoutBankInput[]
  createMany?: Prisma.AccountInfoCreateManyBankInputEnvelope
  set?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  disconnect?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  delete?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  connect?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  update?: Prisma.AccountInfoUpdateWithWhereUniqueWithoutBankInput | Prisma.AccountInfoUpdateWithWhereUniqueWithoutBankInput[]
  updateMany?: Prisma.AccountInfoUpdateManyWithWhereWithoutBankInput | Prisma.AccountInfoUpdateManyWithWhereWithoutBankInput[]
  deleteMany?: Prisma.AccountInfoScalarWhereInput | Prisma.AccountInfoScalarWhereInput[]
}

export type AccountInfoUncheckedUpdateManyWithoutBankNestedInput = {
  create?: Prisma.XOR<Prisma.AccountInfoCreateWithoutBankInput, Prisma.AccountInfoUncheckedCreateWithoutBankInput> | Prisma.AccountInfoCreateWithoutBankInput[] | Prisma.AccountInfoUncheckedCreateWithoutBankInput[]
  connectOrCreate?: Prisma.AccountInfoCreateOrConnectWithoutBankInput | Prisma.AccountInfoCreateOrConnectWithoutBankInput[]
  upsert?: Prisma.AccountInfoUpsertWithWhereUniqueWithoutBankInput | Prisma.AccountInfoUpsertWithWhereUniqueWithoutBankInput[]
  createMany?: Prisma.AccountInfoCreateManyBankInputEnvelope
  set?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  disconnect?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  delete?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  connect?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  update?: Prisma.AccountInfoUpdateWithWhereUniqueWithoutBankInput | Prisma.AccountInfoUpdateWithWhereUniqueWithoutBankInput[]
  updateMany?: Prisma.AccountInfoUpdateManyWithWhereWithoutBankInput | Prisma.AccountInfoUpdateManyWithWhereWithoutBankInput[]
  deleteMany?: Prisma.AccountInfoScalarWhereInput | Prisma.AccountInfoScalarWhereInput[]
}

export type AccountInfoCreateNestedManyWithoutBiodataInput = {
  create?: Prisma.XOR<Prisma.AccountInfoCreateWithoutBiodataInput, Prisma.AccountInfoUncheckedCreateWithoutBiodataInput> | Prisma.AccountInfoCreateWithoutBiodataInput[] | Prisma.AccountInfoUncheckedCreateWithoutBiodataInput[]
  connectOrCreate?: Prisma.AccountInfoCreateOrConnectWithoutBiodataInput | Prisma.AccountInfoCreateOrConnectWithoutBiodataInput[]
  createMany?: Prisma.AccountInfoCreateManyBiodataInputEnvelope
  connect?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
}

export type AccountInfoUncheckedCreateNestedManyWithoutBiodataInput = {
  create?: Prisma.XOR<Prisma.AccountInfoCreateWithoutBiodataInput, Prisma.AccountInfoUncheckedCreateWithoutBiodataInput> | Prisma.AccountInfoCreateWithoutBiodataInput[] | Prisma.AccountInfoUncheckedCreateWithoutBiodataInput[]
  connectOrCreate?: Prisma.AccountInfoCreateOrConnectWithoutBiodataInput | Prisma.AccountInfoCreateOrConnectWithoutBiodataInput[]
  createMany?: Prisma.AccountInfoCreateManyBiodataInputEnvelope
  connect?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
}

export type AccountInfoUpdateManyWithoutBiodataNestedInput = {
  create?: Prisma.XOR<Prisma.AccountInfoCreateWithoutBiodataInput, Prisma.AccountInfoUncheckedCreateWithoutBiodataInput> | Prisma.AccountInfoCreateWithoutBiodataInput[] | Prisma.AccountInfoUncheckedCreateWithoutBiodataInput[]
  connectOrCreate?: Prisma.AccountInfoCreateOrConnectWithoutBiodataInput | Prisma.AccountInfoCreateOrConnectWithoutBiodataInput[]
  upsert?: Prisma.AccountInfoUpsertWithWhereUniqueWithoutBiodataInput | Prisma.AccountInfoUpsertWithWhereUniqueWithoutBiodataInput[]
  createMany?: Prisma.AccountInfoCreateManyBiodataInputEnvelope
  set?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  disconnect?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  delete?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  connect?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  update?: Prisma.AccountInfoUpdateWithWhereUniqueWithoutBiodataInput | Prisma.AccountInfoUpdateWithWhereUniqueWithoutBiodataInput[]
  updateMany?: Prisma.AccountInfoUpdateManyWithWhereWithoutBiodataInput | Prisma.AccountInfoUpdateManyWithWhereWithoutBiodataInput[]
  deleteMany?: Prisma.AccountInfoScalarWhereInput | Prisma.AccountInfoScalarWhereInput[]
}

export type AccountInfoUncheckedUpdateManyWithoutBiodataNestedInput = {
  create?: Prisma.XOR<Prisma.AccountInfoCreateWithoutBiodataInput, Prisma.AccountInfoUncheckedCreateWithoutBiodataInput> | Prisma.AccountInfoCreateWithoutBiodataInput[] | Prisma.AccountInfoUncheckedCreateWithoutBiodataInput[]
  connectOrCreate?: Prisma.AccountInfoCreateOrConnectWithoutBiodataInput | Prisma.AccountInfoCreateOrConnectWithoutBiodataInput[]
  upsert?: Prisma.AccountInfoUpsertWithWhereUniqueWithoutBiodataInput | Prisma.AccountInfoUpsertWithWhereUniqueWithoutBiodataInput[]
  createMany?: Prisma.AccountInfoCreateManyBiodataInputEnvelope
  set?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  disconnect?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  delete?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  connect?: Prisma.AccountInfoWhereUniqueInput | Prisma.AccountInfoWhereUniqueInput[]
  update?: Prisma.AccountInfoUpdateWithWhereUniqueWithoutBiodataInput | Prisma.AccountInfoUpdateWithWhereUniqueWithoutBiodataInput[]
  updateMany?: Prisma.AccountInfoUpdateManyWithWhereWithoutBiodataInput | Prisma.AccountInfoUpdateManyWithWhereWithoutBiodataInput[]
  deleteMany?: Prisma.AccountInfoScalarWhereInput | Prisma.AccountInfoScalarWhereInput[]
}

export type AccountInfoCreateWithoutBankInput = {
  id?: string
  accountNumber: string
  bvn: string
  accountName: string
  isVerified?: boolean
  verificationDate?: Date | string | null
  verifiedBy?: string | null
  biodata: Prisma.BiodataCreateNestedOneWithoutAccountInfoInput
}

export type AccountInfoUncheckedCreateWithoutBankInput = {
  id?: string
  biodataId: string
  accountNumber: string
  bvn: string
  accountName: string
  isVerified?: boolean
  verificationDate?: Date | string | null
  verifiedBy?: string | null
}

export type AccountInfoCreateOrConnectWithoutBankInput = {
  where: Prisma.AccountInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountInfoCreateWithoutBankInput, Prisma.AccountInfoUncheckedCreateWithoutBankInput>
}

export type AccountInfoCreateManyBankInputEnvelope = {
  data: Prisma.AccountInfoCreateManyBankInput | Prisma.AccountInfoCreateManyBankInput[]
  skipDuplicates?: boolean
}

export type AccountInfoUpsertWithWhereUniqueWithoutBankInput = {
  where: Prisma.AccountInfoWhereUniqueInput
  update: Prisma.XOR<Prisma.AccountInfoUpdateWithoutBankInput, Prisma.AccountInfoUncheckedUpdateWithoutBankInput>
  create: Prisma.XOR<Prisma.AccountInfoCreateWithoutBankInput, Prisma.AccountInfoUncheckedCreateWithoutBankInput>
}

export type AccountInfoUpdateWithWhereUniqueWithoutBankInput = {
  where: Prisma.AccountInfoWhereUniqueInput
  data: Prisma.XOR<Prisma.AccountInfoUpdateWithoutBankInput, Prisma.AccountInfoUncheckedUpdateWithoutBankInput>
}

export type AccountInfoUpdateManyWithWhereWithoutBankInput = {
  where: Prisma.AccountInfoScalarWhereInput
  data: Prisma.XOR<Prisma.AccountInfoUpdateManyMutationInput, Prisma.AccountInfoUncheckedUpdateManyWithoutBankInput>
}

export type AccountInfoScalarWhereInput = {
  AND?: Prisma.AccountInfoScalarWhereInput | Prisma.AccountInfoScalarWhereInput[]
  OR?: Prisma.AccountInfoScalarWhereInput[]
  NOT?: Prisma.AccountInfoScalarWhereInput | Prisma.AccountInfoScalarWhereInput[]
  id?: Prisma.UuidFilter<"AccountInfo"> | string
  biodataId?: Prisma.UuidFilter<"AccountInfo"> | string
  bankId?: Prisma.UuidFilter<"AccountInfo"> | string
  accountNumber?: Prisma.StringFilter<"AccountInfo"> | string
  bvn?: Prisma.StringFilter<"AccountInfo"> | string
  accountName?: Prisma.StringFilter<"AccountInfo"> | string
  isVerified?: Prisma.BoolFilter<"AccountInfo"> | boolean
  verificationDate?: Prisma.DateTimeNullableFilter<"AccountInfo"> | Date | string | null
  verifiedBy?: Prisma.UuidNullableFilter<"AccountInfo"> | string | null
}

export type AccountInfoCreateWithoutBiodataInput = {
  id?: string
  accountNumber: string
  bvn: string
  accountName: string
  isVerified?: boolean
  verificationDate?: Date | string | null
  verifiedBy?: string | null
  bank: Prisma.BankCreateNestedOneWithoutAccountsInput
}

export type AccountInfoUncheckedCreateWithoutBiodataInput = {
  id?: string
  bankId: string
  accountNumber: string
  bvn: string
  accountName: string
  isVerified?: boolean
  verificationDate?: Date | string | null
  verifiedBy?: string | null
}

export type AccountInfoCreateOrConnectWithoutBiodataInput = {
  where: Prisma.AccountInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountInfoCreateWithoutBiodataInput, Prisma.AccountInfoUncheckedCreateWithoutBiodataInput>
}

export type AccountInfoCreateManyBiodataInputEnvelope = {
  data: Prisma.AccountInfoCreateManyBiodataInput | Prisma.AccountInfoCreateManyBiodataInput[]
  skipDuplicates?: boolean
}

export type AccountInfoUpsertWithWhereUniqueWithoutBiodataInput = {
  where: Prisma.AccountInfoWhereUniqueInput
  update: Prisma.XOR<Prisma.AccountInfoUpdateWithoutBiodataInput, Prisma.AccountInfoUncheckedUpdateWithoutBiodataInput>
  create: Prisma.XOR<Prisma.AccountInfoCreateWithoutBiodataInput, Prisma.AccountInfoUncheckedCreateWithoutBiodataInput>
}

export type AccountInfoUpdateWithWhereUniqueWithoutBiodataInput = {
  where: Prisma.AccountInfoWhereUniqueInput
  data: Prisma.XOR<Prisma.AccountInfoUpdateWithoutBiodataInput, Prisma.AccountInfoUncheckedUpdateWithoutBiodataInput>
}

export type AccountInfoUpdateManyWithWhereWithoutBiodataInput = {
  where: Prisma.AccountInfoScalarWhereInput
  data: Prisma.XOR<Prisma.AccountInfoUpdateManyMutationInput, Prisma.AccountInfoUncheckedUpdateManyWithoutBiodataInput>
}

export type AccountInfoCreateManyBankInput = {
  id?: string
  biodataId: string
  accountNumber: string
  bvn: string
  accountName: string
  isVerified?: boolean
  verificationDate?: Date | string | null
  verifiedBy?: string | null
}

export type AccountInfoUpdateWithoutBankInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  bvn?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  verificationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verifiedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  biodata?: Prisma.BiodataUpdateOneRequiredWithoutAccountInfoNestedInput
}

export type AccountInfoUncheckedUpdateWithoutBankInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  biodataId?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  bvn?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  verificationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verifiedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AccountInfoUncheckedUpdateManyWithoutBankInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  biodataId?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  bvn?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  verificationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verifiedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AccountInfoCreateManyBiodataInput = {
  id?: string
  bankId: string
  accountNumber: string
  bvn: string
  accountName: string
  isVerified?: boolean
  verificationDate?: Date | string | null
  verifiedBy?: string | null
}

export type AccountInfoUpdateWithoutBiodataInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  bvn?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  verificationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verifiedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bank?: Prisma.BankUpdateOneRequiredWithoutAccountsNestedInput
}

export type AccountInfoUncheckedUpdateWithoutBiodataInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bankId?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  bvn?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  verificationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verifiedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AccountInfoUncheckedUpdateManyWithoutBiodataInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bankId?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  bvn?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  verificationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  verifiedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type AccountInfoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  biodataId?: boolean
  bankId?: boolean
  accountNumber?: boolean
  bvn?: boolean
  accountName?: boolean
  isVerified?: boolean
  verificationDate?: boolean
  verifiedBy?: boolean
  bank?: boolean | Prisma.BankDefaultArgs<ExtArgs>
  biodata?: boolean | Prisma.BiodataDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accountInfo"]>

export type AccountInfoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  biodataId?: boolean
  bankId?: boolean
  accountNumber?: boolean
  bvn?: boolean
  accountName?: boolean
  isVerified?: boolean
  verificationDate?: boolean
  verifiedBy?: boolean
  bank?: boolean | Prisma.BankDefaultArgs<ExtArgs>
  biodata?: boolean | Prisma.BiodataDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accountInfo"]>

export type AccountInfoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  biodataId?: boolean
  bankId?: boolean
  accountNumber?: boolean
  bvn?: boolean
  accountName?: boolean
  isVerified?: boolean
  verificationDate?: boolean
  verifiedBy?: boolean
  bank?: boolean | Prisma.BankDefaultArgs<ExtArgs>
  biodata?: boolean | Prisma.BiodataDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accountInfo"]>

export type AccountInfoSelectScalar = {
  id?: boolean
  biodataId?: boolean
  bankId?: boolean
  accountNumber?: boolean
  bvn?: boolean
  accountName?: boolean
  isVerified?: boolean
  verificationDate?: boolean
  verifiedBy?: boolean
}

export type AccountInfoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "biodataId" | "bankId" | "accountNumber" | "bvn" | "accountName" | "isVerified" | "verificationDate" | "verifiedBy", ExtArgs["result"]["accountInfo"]>
export type AccountInfoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bank?: boolean | Prisma.BankDefaultArgs<ExtArgs>
  biodata?: boolean | Prisma.BiodataDefaultArgs<ExtArgs>
}
export type AccountInfoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bank?: boolean | Prisma.BankDefaultArgs<ExtArgs>
  biodata?: boolean | Prisma.BiodataDefaultArgs<ExtArgs>
}
export type AccountInfoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bank?: boolean | Prisma.BankDefaultArgs<ExtArgs>
  biodata?: boolean | Prisma.BiodataDefaultArgs<ExtArgs>
}

export type $AccountInfoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AccountInfo"
  objects: {
    bank: Prisma.$BankPayload<ExtArgs>
    biodata: Prisma.$BiodataPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    biodataId: string
    bankId: string
    accountNumber: string
    bvn: string
    accountName: string
    isVerified: boolean
    verificationDate: Date | null
    verifiedBy: string | null
  }, ExtArgs["result"]["accountInfo"]>
  composites: {}
}

export type AccountInfoGetPayload<S extends boolean | null | undefined | AccountInfoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccountInfoPayload, S>

export type AccountInfoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccountInfoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccountInfoCountAggregateInputType | true
  }

export interface AccountInfoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AccountInfo'], meta: { name: 'AccountInfo' } }
  /**
   * Find zero or one AccountInfo that matches the filter.
   * @param {AccountInfoFindUniqueArgs} args - Arguments to find a AccountInfo
   * @example
   * // Get one AccountInfo
   * const accountInfo = await prisma.accountInfo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccountInfoFindUniqueArgs>(args: Prisma.SelectSubset<T, AccountInfoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccountInfoClient<runtime.Types.Result.GetResult<Prisma.$AccountInfoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AccountInfo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccountInfoFindUniqueOrThrowArgs} args - Arguments to find a AccountInfo
   * @example
   * // Get one AccountInfo
   * const accountInfo = await prisma.accountInfo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccountInfoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccountInfoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountInfoClient<runtime.Types.Result.GetResult<Prisma.$AccountInfoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccountInfo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountInfoFindFirstArgs} args - Arguments to find a AccountInfo
   * @example
   * // Get one AccountInfo
   * const accountInfo = await prisma.accountInfo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccountInfoFindFirstArgs>(args?: Prisma.SelectSubset<T, AccountInfoFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccountInfoClient<runtime.Types.Result.GetResult<Prisma.$AccountInfoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccountInfo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountInfoFindFirstOrThrowArgs} args - Arguments to find a AccountInfo
   * @example
   * // Get one AccountInfo
   * const accountInfo = await prisma.accountInfo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccountInfoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccountInfoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountInfoClient<runtime.Types.Result.GetResult<Prisma.$AccountInfoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AccountInfos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountInfoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AccountInfos
   * const accountInfos = await prisma.accountInfo.findMany()
   * 
   * // Get first 10 AccountInfos
   * const accountInfos = await prisma.accountInfo.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accountInfoWithIdOnly = await prisma.accountInfo.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccountInfoFindManyArgs>(args?: Prisma.SelectSubset<T, AccountInfoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountInfoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AccountInfo.
   * @param {AccountInfoCreateArgs} args - Arguments to create a AccountInfo.
   * @example
   * // Create one AccountInfo
   * const AccountInfo = await prisma.accountInfo.create({
   *   data: {
   *     // ... data to create a AccountInfo
   *   }
   * })
   * 
   */
  create<T extends AccountInfoCreateArgs>(args: Prisma.SelectSubset<T, AccountInfoCreateArgs<ExtArgs>>): Prisma.Prisma__AccountInfoClient<runtime.Types.Result.GetResult<Prisma.$AccountInfoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AccountInfos.
   * @param {AccountInfoCreateManyArgs} args - Arguments to create many AccountInfos.
   * @example
   * // Create many AccountInfos
   * const accountInfo = await prisma.accountInfo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccountInfoCreateManyArgs>(args?: Prisma.SelectSubset<T, AccountInfoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AccountInfos and returns the data saved in the database.
   * @param {AccountInfoCreateManyAndReturnArgs} args - Arguments to create many AccountInfos.
   * @example
   * // Create many AccountInfos
   * const accountInfo = await prisma.accountInfo.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AccountInfos and only return the `id`
   * const accountInfoWithIdOnly = await prisma.accountInfo.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccountInfoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccountInfoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountInfoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AccountInfo.
   * @param {AccountInfoDeleteArgs} args - Arguments to delete one AccountInfo.
   * @example
   * // Delete one AccountInfo
   * const AccountInfo = await prisma.accountInfo.delete({
   *   where: {
   *     // ... filter to delete one AccountInfo
   *   }
   * })
   * 
   */
  delete<T extends AccountInfoDeleteArgs>(args: Prisma.SelectSubset<T, AccountInfoDeleteArgs<ExtArgs>>): Prisma.Prisma__AccountInfoClient<runtime.Types.Result.GetResult<Prisma.$AccountInfoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AccountInfo.
   * @param {AccountInfoUpdateArgs} args - Arguments to update one AccountInfo.
   * @example
   * // Update one AccountInfo
   * const accountInfo = await prisma.accountInfo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccountInfoUpdateArgs>(args: Prisma.SelectSubset<T, AccountInfoUpdateArgs<ExtArgs>>): Prisma.Prisma__AccountInfoClient<runtime.Types.Result.GetResult<Prisma.$AccountInfoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AccountInfos.
   * @param {AccountInfoDeleteManyArgs} args - Arguments to filter AccountInfos to delete.
   * @example
   * // Delete a few AccountInfos
   * const { count } = await prisma.accountInfo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccountInfoDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccountInfoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccountInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountInfoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AccountInfos
   * const accountInfo = await prisma.accountInfo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccountInfoUpdateManyArgs>(args: Prisma.SelectSubset<T, AccountInfoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccountInfos and returns the data updated in the database.
   * @param {AccountInfoUpdateManyAndReturnArgs} args - Arguments to update many AccountInfos.
   * @example
   * // Update many AccountInfos
   * const accountInfo = await prisma.accountInfo.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AccountInfos and only return the `id`
   * const accountInfoWithIdOnly = await prisma.accountInfo.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccountInfoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccountInfoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountInfoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AccountInfo.
   * @param {AccountInfoUpsertArgs} args - Arguments to update or create a AccountInfo.
   * @example
   * // Update or create a AccountInfo
   * const accountInfo = await prisma.accountInfo.upsert({
   *   create: {
   *     // ... data to create a AccountInfo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AccountInfo we want to update
   *   }
   * })
   */
  upsert<T extends AccountInfoUpsertArgs>(args: Prisma.SelectSubset<T, AccountInfoUpsertArgs<ExtArgs>>): Prisma.Prisma__AccountInfoClient<runtime.Types.Result.GetResult<Prisma.$AccountInfoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AccountInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountInfoCountArgs} args - Arguments to filter AccountInfos to count.
   * @example
   * // Count the number of AccountInfos
   * const count = await prisma.accountInfo.count({
   *   where: {
   *     // ... the filter for the AccountInfos we want to count
   *   }
   * })
  **/
  count<T extends AccountInfoCountArgs>(
    args?: Prisma.Subset<T, AccountInfoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccountInfoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AccountInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountInfoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccountInfoAggregateArgs>(args: Prisma.Subset<T, AccountInfoAggregateArgs>): Prisma.PrismaPromise<GetAccountInfoAggregateType<T>>

  /**
   * Group by AccountInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountInfoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccountInfoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccountInfoGroupByArgs['orderBy'] }
      : { orderBy?: AccountInfoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccountInfoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccountInfoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AccountInfo model
 */
readonly fields: AccountInfoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AccountInfo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccountInfoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bank<T extends Prisma.BankDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BankDefaultArgs<ExtArgs>>): Prisma.Prisma__BankClient<runtime.Types.Result.GetResult<Prisma.$BankPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  biodata<T extends Prisma.BiodataDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BiodataDefaultArgs<ExtArgs>>): Prisma.Prisma__BiodataClient<runtime.Types.Result.GetResult<Prisma.$BiodataPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AccountInfo model
 */
export interface AccountInfoFieldRefs {
  readonly id: Prisma.FieldRef<"AccountInfo", 'String'>
  readonly biodataId: Prisma.FieldRef<"AccountInfo", 'String'>
  readonly bankId: Prisma.FieldRef<"AccountInfo", 'String'>
  readonly accountNumber: Prisma.FieldRef<"AccountInfo", 'String'>
  readonly bvn: Prisma.FieldRef<"AccountInfo", 'String'>
  readonly accountName: Prisma.FieldRef<"AccountInfo", 'String'>
  readonly isVerified: Prisma.FieldRef<"AccountInfo", 'Boolean'>
  readonly verificationDate: Prisma.FieldRef<"AccountInfo", 'DateTime'>
  readonly verifiedBy: Prisma.FieldRef<"AccountInfo", 'String'>
}
    

// Custom InputTypes
/**
 * AccountInfo findUnique
 */
export type AccountInfoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountInfo
   */
  select?: Prisma.AccountInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountInfo
   */
  omit?: Prisma.AccountInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInfoInclude<ExtArgs> | null
  /**
   * Filter, which AccountInfo to fetch.
   */
  where: Prisma.AccountInfoWhereUniqueInput
}

/**
 * AccountInfo findUniqueOrThrow
 */
export type AccountInfoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountInfo
   */
  select?: Prisma.AccountInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountInfo
   */
  omit?: Prisma.AccountInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInfoInclude<ExtArgs> | null
  /**
   * Filter, which AccountInfo to fetch.
   */
  where: Prisma.AccountInfoWhereUniqueInput
}

/**
 * AccountInfo findFirst
 */
export type AccountInfoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountInfo
   */
  select?: Prisma.AccountInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountInfo
   */
  omit?: Prisma.AccountInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInfoInclude<ExtArgs> | null
  /**
   * Filter, which AccountInfo to fetch.
   */
  where?: Prisma.AccountInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountInfos to fetch.
   */
  orderBy?: Prisma.AccountInfoOrderByWithRelationInput | Prisma.AccountInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccountInfos.
   */
  cursor?: Prisma.AccountInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountInfos.
   */
  distinct?: Prisma.AccountInfoScalarFieldEnum | Prisma.AccountInfoScalarFieldEnum[]
}

/**
 * AccountInfo findFirstOrThrow
 */
export type AccountInfoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountInfo
   */
  select?: Prisma.AccountInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountInfo
   */
  omit?: Prisma.AccountInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInfoInclude<ExtArgs> | null
  /**
   * Filter, which AccountInfo to fetch.
   */
  where?: Prisma.AccountInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountInfos to fetch.
   */
  orderBy?: Prisma.AccountInfoOrderByWithRelationInput | Prisma.AccountInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccountInfos.
   */
  cursor?: Prisma.AccountInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountInfos.
   */
  distinct?: Prisma.AccountInfoScalarFieldEnum | Prisma.AccountInfoScalarFieldEnum[]
}

/**
 * AccountInfo findMany
 */
export type AccountInfoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountInfo
   */
  select?: Prisma.AccountInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountInfo
   */
  omit?: Prisma.AccountInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInfoInclude<ExtArgs> | null
  /**
   * Filter, which AccountInfos to fetch.
   */
  where?: Prisma.AccountInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountInfos to fetch.
   */
  orderBy?: Prisma.AccountInfoOrderByWithRelationInput | Prisma.AccountInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AccountInfos.
   */
  cursor?: Prisma.AccountInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountInfos.
   */
  distinct?: Prisma.AccountInfoScalarFieldEnum | Prisma.AccountInfoScalarFieldEnum[]
}

/**
 * AccountInfo create
 */
export type AccountInfoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountInfo
   */
  select?: Prisma.AccountInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountInfo
   */
  omit?: Prisma.AccountInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInfoInclude<ExtArgs> | null
  /**
   * The data needed to create a AccountInfo.
   */
  data: Prisma.XOR<Prisma.AccountInfoCreateInput, Prisma.AccountInfoUncheckedCreateInput>
}

/**
 * AccountInfo createMany
 */
export type AccountInfoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AccountInfos.
   */
  data: Prisma.AccountInfoCreateManyInput | Prisma.AccountInfoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccountInfo createManyAndReturn
 */
export type AccountInfoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountInfo
   */
  select?: Prisma.AccountInfoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccountInfo
   */
  omit?: Prisma.AccountInfoOmit<ExtArgs> | null
  /**
   * The data used to create many AccountInfos.
   */
  data: Prisma.AccountInfoCreateManyInput | Prisma.AccountInfoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInfoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AccountInfo update
 */
export type AccountInfoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountInfo
   */
  select?: Prisma.AccountInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountInfo
   */
  omit?: Prisma.AccountInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInfoInclude<ExtArgs> | null
  /**
   * The data needed to update a AccountInfo.
   */
  data: Prisma.XOR<Prisma.AccountInfoUpdateInput, Prisma.AccountInfoUncheckedUpdateInput>
  /**
   * Choose, which AccountInfo to update.
   */
  where: Prisma.AccountInfoWhereUniqueInput
}

/**
 * AccountInfo updateMany
 */
export type AccountInfoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AccountInfos.
   */
  data: Prisma.XOR<Prisma.AccountInfoUpdateManyMutationInput, Prisma.AccountInfoUncheckedUpdateManyInput>
  /**
   * Filter which AccountInfos to update
   */
  where?: Prisma.AccountInfoWhereInput
  /**
   * Limit how many AccountInfos to update.
   */
  limit?: number
}

/**
 * AccountInfo updateManyAndReturn
 */
export type AccountInfoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountInfo
   */
  select?: Prisma.AccountInfoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccountInfo
   */
  omit?: Prisma.AccountInfoOmit<ExtArgs> | null
  /**
   * The data used to update AccountInfos.
   */
  data: Prisma.XOR<Prisma.AccountInfoUpdateManyMutationInput, Prisma.AccountInfoUncheckedUpdateManyInput>
  /**
   * Filter which AccountInfos to update
   */
  where?: Prisma.AccountInfoWhereInput
  /**
   * Limit how many AccountInfos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInfoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AccountInfo upsert
 */
export type AccountInfoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountInfo
   */
  select?: Prisma.AccountInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountInfo
   */
  omit?: Prisma.AccountInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInfoInclude<ExtArgs> | null
  /**
   * The filter to search for the AccountInfo to update in case it exists.
   */
  where: Prisma.AccountInfoWhereUniqueInput
  /**
   * In case the AccountInfo found by the `where` argument doesn't exist, create a new AccountInfo with this data.
   */
  create: Prisma.XOR<Prisma.AccountInfoCreateInput, Prisma.AccountInfoUncheckedCreateInput>
  /**
   * In case the AccountInfo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccountInfoUpdateInput, Prisma.AccountInfoUncheckedUpdateInput>
}

/**
 * AccountInfo delete
 */
export type AccountInfoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountInfo
   */
  select?: Prisma.AccountInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountInfo
   */
  omit?: Prisma.AccountInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInfoInclude<ExtArgs> | null
  /**
   * Filter which AccountInfo to delete.
   */
  where: Prisma.AccountInfoWhereUniqueInput
}

/**
 * AccountInfo deleteMany
 */
export type AccountInfoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccountInfos to delete
   */
  where?: Prisma.AccountInfoWhereInput
  /**
   * Limit how many AccountInfos to delete.
   */
  limit?: number
}

/**
 * AccountInfo without action
 */
export type AccountInfoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountInfo
   */
  select?: Prisma.AccountInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountInfo
   */
  omit?: Prisma.AccountInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInfoInclude<ExtArgs> | null
}
