
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AdminUserProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AdminUserProfile
 * 
 */
export type AdminUserProfileModel = runtime.Types.Result.DefaultSelection<Prisma.$AdminUserProfilePayload>

export type AggregateAdminUserProfile = {
  _count: AdminUserProfileCountAggregateOutputType | null
  _min: AdminUserProfileMinAggregateOutputType | null
  _max: AdminUserProfileMaxAggregateOutputType | null
}

export type AdminUserProfileMinAggregateOutputType = {
  id: string | null
  userId: string | null
  firstName: string | null
  lastName: string | null
  emailAddress: string | null
  phoneNumber: string | null
  department: string | null
  position: string | null
  staffId: string | null
  isActive: boolean | null
  isVerified: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AdminUserProfileMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  firstName: string | null
  lastName: string | null
  emailAddress: string | null
  phoneNumber: string | null
  department: string | null
  position: string | null
  staffId: string | null
  isActive: boolean | null
  isVerified: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AdminUserProfileCountAggregateOutputType = {
  id: number
  userId: number
  firstName: number
  lastName: number
  emailAddress: number
  phoneNumber: number
  department: number
  position: number
  staffId: number
  isActive: number
  isVerified: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AdminUserProfileMinAggregateInputType = {
  id?: true
  userId?: true
  firstName?: true
  lastName?: true
  emailAddress?: true
  phoneNumber?: true
  department?: true
  position?: true
  staffId?: true
  isActive?: true
  isVerified?: true
  createdAt?: true
  updatedAt?: true
}

export type AdminUserProfileMaxAggregateInputType = {
  id?: true
  userId?: true
  firstName?: true
  lastName?: true
  emailAddress?: true
  phoneNumber?: true
  department?: true
  position?: true
  staffId?: true
  isActive?: true
  isVerified?: true
  createdAt?: true
  updatedAt?: true
}

export type AdminUserProfileCountAggregateInputType = {
  id?: true
  userId?: true
  firstName?: true
  lastName?: true
  emailAddress?: true
  phoneNumber?: true
  department?: true
  position?: true
  staffId?: true
  isActive?: true
  isVerified?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AdminUserProfileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AdminUserProfile to aggregate.
   */
  where?: Prisma.AdminUserProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdminUserProfiles to fetch.
   */
  orderBy?: Prisma.AdminUserProfileOrderByWithRelationInput | Prisma.AdminUserProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AdminUserProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdminUserProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdminUserProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AdminUserProfiles
  **/
  _count?: true | AdminUserProfileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AdminUserProfileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AdminUserProfileMaxAggregateInputType
}

export type GetAdminUserProfileAggregateType<T extends AdminUserProfileAggregateArgs> = {
      [P in keyof T & keyof AggregateAdminUserProfile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAdminUserProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateAdminUserProfile[P]>
}




export type AdminUserProfileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AdminUserProfileWhereInput
  orderBy?: Prisma.AdminUserProfileOrderByWithAggregationInput | Prisma.AdminUserProfileOrderByWithAggregationInput[]
  by: Prisma.AdminUserProfileScalarFieldEnum[] | Prisma.AdminUserProfileScalarFieldEnum
  having?: Prisma.AdminUserProfileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AdminUserProfileCountAggregateInputType | true
  _min?: AdminUserProfileMinAggregateInputType
  _max?: AdminUserProfileMaxAggregateInputType
}

export type AdminUserProfileGroupByOutputType = {
  id: string
  userId: string | null
  firstName: string
  lastName: string
  emailAddress: string
  phoneNumber: string
  department: string
  position: string
  staffId: string
  isActive: boolean
  isVerified: boolean
  createdAt: Date
  updatedAt: Date
  _count: AdminUserProfileCountAggregateOutputType | null
  _min: AdminUserProfileMinAggregateOutputType | null
  _max: AdminUserProfileMaxAggregateOutputType | null
}

export type GetAdminUserProfileGroupByPayload<T extends AdminUserProfileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AdminUserProfileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AdminUserProfileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AdminUserProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AdminUserProfileGroupByOutputType[P]>
      }
    >
  >



export type AdminUserProfileWhereInput = {
  AND?: Prisma.AdminUserProfileWhereInput | Prisma.AdminUserProfileWhereInput[]
  OR?: Prisma.AdminUserProfileWhereInput[]
  NOT?: Prisma.AdminUserProfileWhereInput | Prisma.AdminUserProfileWhereInput[]
  id?: Prisma.UuidFilter<"AdminUserProfile"> | string
  userId?: Prisma.UuidNullableFilter<"AdminUserProfile"> | string | null
  firstName?: Prisma.StringFilter<"AdminUserProfile"> | string
  lastName?: Prisma.StringFilter<"AdminUserProfile"> | string
  emailAddress?: Prisma.StringFilter<"AdminUserProfile"> | string
  phoneNumber?: Prisma.StringFilter<"AdminUserProfile"> | string
  department?: Prisma.StringFilter<"AdminUserProfile"> | string
  position?: Prisma.StringFilter<"AdminUserProfile"> | string
  staffId?: Prisma.StringFilter<"AdminUserProfile"> | string
  isActive?: Prisma.BoolFilter<"AdminUserProfile"> | boolean
  isVerified?: Prisma.BoolFilter<"AdminUserProfile"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AdminUserProfile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AdminUserProfile"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type AdminUserProfileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  emailAddress?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  department?: Prisma.SortOrder
  position?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type AdminUserProfileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  emailAddress?: string
  phoneNumber?: string
  staffId?: string
  AND?: Prisma.AdminUserProfileWhereInput | Prisma.AdminUserProfileWhereInput[]
  OR?: Prisma.AdminUserProfileWhereInput[]
  NOT?: Prisma.AdminUserProfileWhereInput | Prisma.AdminUserProfileWhereInput[]
  firstName?: Prisma.StringFilter<"AdminUserProfile"> | string
  lastName?: Prisma.StringFilter<"AdminUserProfile"> | string
  department?: Prisma.StringFilter<"AdminUserProfile"> | string
  position?: Prisma.StringFilter<"AdminUserProfile"> | string
  isActive?: Prisma.BoolFilter<"AdminUserProfile"> | boolean
  isVerified?: Prisma.BoolFilter<"AdminUserProfile"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AdminUserProfile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AdminUserProfile"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "userId" | "emailAddress" | "phoneNumber" | "staffId">

export type AdminUserProfileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  emailAddress?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  department?: Prisma.SortOrder
  position?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AdminUserProfileCountOrderByAggregateInput
  _max?: Prisma.AdminUserProfileMaxOrderByAggregateInput
  _min?: Prisma.AdminUserProfileMinOrderByAggregateInput
}

export type AdminUserProfileScalarWhereWithAggregatesInput = {
  AND?: Prisma.AdminUserProfileScalarWhereWithAggregatesInput | Prisma.AdminUserProfileScalarWhereWithAggregatesInput[]
  OR?: Prisma.AdminUserProfileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AdminUserProfileScalarWhereWithAggregatesInput | Prisma.AdminUserProfileScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"AdminUserProfile"> | string
  userId?: Prisma.UuidNullableWithAggregatesFilter<"AdminUserProfile"> | string | null
  firstName?: Prisma.StringWithAggregatesFilter<"AdminUserProfile"> | string
  lastName?: Prisma.StringWithAggregatesFilter<"AdminUserProfile"> | string
  emailAddress?: Prisma.StringWithAggregatesFilter<"AdminUserProfile"> | string
  phoneNumber?: Prisma.StringWithAggregatesFilter<"AdminUserProfile"> | string
  department?: Prisma.StringWithAggregatesFilter<"AdminUserProfile"> | string
  position?: Prisma.StringWithAggregatesFilter<"AdminUserProfile"> | string
  staffId?: Prisma.StringWithAggregatesFilter<"AdminUserProfile"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"AdminUserProfile"> | boolean
  isVerified?: Prisma.BoolWithAggregatesFilter<"AdminUserProfile"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AdminUserProfile"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AdminUserProfile"> | Date | string
}

export type AdminUserProfileCreateInput = {
  id?: string
  firstName: string
  lastName: string
  emailAddress: string
  phoneNumber: string
  department: string
  position: string
  staffId: string
  isActive?: boolean
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutAdminProfileInput
}

export type AdminUserProfileUncheckedCreateInput = {
  id?: string
  userId?: string | null
  firstName: string
  lastName: string
  emailAddress: string
  phoneNumber: string
  department: string
  position: string
  staffId: string
  isActive?: boolean
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AdminUserProfileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  emailAddress?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutAdminProfileNestedInput
}

export type AdminUserProfileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  emailAddress?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdminUserProfileCreateManyInput = {
  id?: string
  userId?: string | null
  firstName: string
  lastName: string
  emailAddress: string
  phoneNumber: string
  department: string
  position: string
  staffId: string
  isActive?: boolean
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AdminUserProfileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  emailAddress?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdminUserProfileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  emailAddress?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdminUserProfileNullableScalarRelationFilter = {
  is?: Prisma.AdminUserProfileWhereInput | null
  isNot?: Prisma.AdminUserProfileWhereInput | null
}

export type AdminUserProfileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  emailAddress?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  department?: Prisma.SortOrder
  position?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AdminUserProfileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  emailAddress?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  department?: Prisma.SortOrder
  position?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AdminUserProfileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  emailAddress?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  department?: Prisma.SortOrder
  position?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AdminUserProfileCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AdminUserProfileCreateWithoutUserInput, Prisma.AdminUserProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AdminUserProfileCreateOrConnectWithoutUserInput
  connect?: Prisma.AdminUserProfileWhereUniqueInput
}

export type AdminUserProfileUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AdminUserProfileCreateWithoutUserInput, Prisma.AdminUserProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AdminUserProfileCreateOrConnectWithoutUserInput
  connect?: Prisma.AdminUserProfileWhereUniqueInput
}

export type AdminUserProfileUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AdminUserProfileCreateWithoutUserInput, Prisma.AdminUserProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AdminUserProfileCreateOrConnectWithoutUserInput
  upsert?: Prisma.AdminUserProfileUpsertWithoutUserInput
  disconnect?: Prisma.AdminUserProfileWhereInput | boolean
  delete?: Prisma.AdminUserProfileWhereInput | boolean
  connect?: Prisma.AdminUserProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AdminUserProfileUpdateToOneWithWhereWithoutUserInput, Prisma.AdminUserProfileUpdateWithoutUserInput>, Prisma.AdminUserProfileUncheckedUpdateWithoutUserInput>
}

export type AdminUserProfileUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AdminUserProfileCreateWithoutUserInput, Prisma.AdminUserProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AdminUserProfileCreateOrConnectWithoutUserInput
  upsert?: Prisma.AdminUserProfileUpsertWithoutUserInput
  disconnect?: Prisma.AdminUserProfileWhereInput | boolean
  delete?: Prisma.AdminUserProfileWhereInput | boolean
  connect?: Prisma.AdminUserProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AdminUserProfileUpdateToOneWithWhereWithoutUserInput, Prisma.AdminUserProfileUpdateWithoutUserInput>, Prisma.AdminUserProfileUncheckedUpdateWithoutUserInput>
}

export type AdminUserProfileCreateWithoutUserInput = {
  id?: string
  firstName: string
  lastName: string
  emailAddress: string
  phoneNumber: string
  department: string
  position: string
  staffId: string
  isActive?: boolean
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AdminUserProfileUncheckedCreateWithoutUserInput = {
  id?: string
  firstName: string
  lastName: string
  emailAddress: string
  phoneNumber: string
  department: string
  position: string
  staffId: string
  isActive?: boolean
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AdminUserProfileCreateOrConnectWithoutUserInput = {
  where: Prisma.AdminUserProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.AdminUserProfileCreateWithoutUserInput, Prisma.AdminUserProfileUncheckedCreateWithoutUserInput>
}

export type AdminUserProfileUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.AdminUserProfileUpdateWithoutUserInput, Prisma.AdminUserProfileUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AdminUserProfileCreateWithoutUserInput, Prisma.AdminUserProfileUncheckedCreateWithoutUserInput>
  where?: Prisma.AdminUserProfileWhereInput
}

export type AdminUserProfileUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.AdminUserProfileWhereInput
  data: Prisma.XOR<Prisma.AdminUserProfileUpdateWithoutUserInput, Prisma.AdminUserProfileUncheckedUpdateWithoutUserInput>
}

export type AdminUserProfileUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  emailAddress?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdminUserProfileUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  emailAddress?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AdminUserProfileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  firstName?: boolean
  lastName?: boolean
  emailAddress?: boolean
  phoneNumber?: boolean
  department?: boolean
  position?: boolean
  staffId?: boolean
  isActive?: boolean
  isVerified?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.AdminUserProfile$userArgs<ExtArgs>
}, ExtArgs["result"]["adminUserProfile"]>

export type AdminUserProfileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  firstName?: boolean
  lastName?: boolean
  emailAddress?: boolean
  phoneNumber?: boolean
  department?: boolean
  position?: boolean
  staffId?: boolean
  isActive?: boolean
  isVerified?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.AdminUserProfile$userArgs<ExtArgs>
}, ExtArgs["result"]["adminUserProfile"]>

export type AdminUserProfileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  firstName?: boolean
  lastName?: boolean
  emailAddress?: boolean
  phoneNumber?: boolean
  department?: boolean
  position?: boolean
  staffId?: boolean
  isActive?: boolean
  isVerified?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.AdminUserProfile$userArgs<ExtArgs>
}, ExtArgs["result"]["adminUserProfile"]>

export type AdminUserProfileSelectScalar = {
  id?: boolean
  userId?: boolean
  firstName?: boolean
  lastName?: boolean
  emailAddress?: boolean
  phoneNumber?: boolean
  department?: boolean
  position?: boolean
  staffId?: boolean
  isActive?: boolean
  isVerified?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AdminUserProfileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "firstName" | "lastName" | "emailAddress" | "phoneNumber" | "department" | "position" | "staffId" | "isActive" | "isVerified" | "createdAt" | "updatedAt", ExtArgs["result"]["adminUserProfile"]>
export type AdminUserProfileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.AdminUserProfile$userArgs<ExtArgs>
}
export type AdminUserProfileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.AdminUserProfile$userArgs<ExtArgs>
}
export type AdminUserProfileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.AdminUserProfile$userArgs<ExtArgs>
}

export type $AdminUserProfilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AdminUserProfile"
  objects: {
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string | null
    firstName: string
    lastName: string
    emailAddress: string
    phoneNumber: string
    department: string
    position: string
    staffId: string
    isActive: boolean
    isVerified: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["adminUserProfile"]>
  composites: {}
}

export type AdminUserProfileGetPayload<S extends boolean | null | undefined | AdminUserProfileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AdminUserProfilePayload, S>

export type AdminUserProfileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AdminUserProfileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AdminUserProfileCountAggregateInputType | true
  }

export interface AdminUserProfileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AdminUserProfile'], meta: { name: 'AdminUserProfile' } }
  /**
   * Find zero or one AdminUserProfile that matches the filter.
   * @param {AdminUserProfileFindUniqueArgs} args - Arguments to find a AdminUserProfile
   * @example
   * // Get one AdminUserProfile
   * const adminUserProfile = await prisma.adminUserProfile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AdminUserProfileFindUniqueArgs>(args: Prisma.SelectSubset<T, AdminUserProfileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AdminUserProfileClient<runtime.Types.Result.GetResult<Prisma.$AdminUserProfilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AdminUserProfile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AdminUserProfileFindUniqueOrThrowArgs} args - Arguments to find a AdminUserProfile
   * @example
   * // Get one AdminUserProfile
   * const adminUserProfile = await prisma.adminUserProfile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AdminUserProfileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AdminUserProfileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdminUserProfileClient<runtime.Types.Result.GetResult<Prisma.$AdminUserProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AdminUserProfile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminUserProfileFindFirstArgs} args - Arguments to find a AdminUserProfile
   * @example
   * // Get one AdminUserProfile
   * const adminUserProfile = await prisma.adminUserProfile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AdminUserProfileFindFirstArgs>(args?: Prisma.SelectSubset<T, AdminUserProfileFindFirstArgs<ExtArgs>>): Prisma.Prisma__AdminUserProfileClient<runtime.Types.Result.GetResult<Prisma.$AdminUserProfilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AdminUserProfile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminUserProfileFindFirstOrThrowArgs} args - Arguments to find a AdminUserProfile
   * @example
   * // Get one AdminUserProfile
   * const adminUserProfile = await prisma.adminUserProfile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AdminUserProfileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AdminUserProfileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdminUserProfileClient<runtime.Types.Result.GetResult<Prisma.$AdminUserProfilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AdminUserProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminUserProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AdminUserProfiles
   * const adminUserProfiles = await prisma.adminUserProfile.findMany()
   * 
   * // Get first 10 AdminUserProfiles
   * const adminUserProfiles = await prisma.adminUserProfile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const adminUserProfileWithIdOnly = await prisma.adminUserProfile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AdminUserProfileFindManyArgs>(args?: Prisma.SelectSubset<T, AdminUserProfileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdminUserProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AdminUserProfile.
   * @param {AdminUserProfileCreateArgs} args - Arguments to create a AdminUserProfile.
   * @example
   * // Create one AdminUserProfile
   * const AdminUserProfile = await prisma.adminUserProfile.create({
   *   data: {
   *     // ... data to create a AdminUserProfile
   *   }
   * })
   * 
   */
  create<T extends AdminUserProfileCreateArgs>(args: Prisma.SelectSubset<T, AdminUserProfileCreateArgs<ExtArgs>>): Prisma.Prisma__AdminUserProfileClient<runtime.Types.Result.GetResult<Prisma.$AdminUserProfilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AdminUserProfiles.
   * @param {AdminUserProfileCreateManyArgs} args - Arguments to create many AdminUserProfiles.
   * @example
   * // Create many AdminUserProfiles
   * const adminUserProfile = await prisma.adminUserProfile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AdminUserProfileCreateManyArgs>(args?: Prisma.SelectSubset<T, AdminUserProfileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AdminUserProfiles and returns the data saved in the database.
   * @param {AdminUserProfileCreateManyAndReturnArgs} args - Arguments to create many AdminUserProfiles.
   * @example
   * // Create many AdminUserProfiles
   * const adminUserProfile = await prisma.adminUserProfile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AdminUserProfiles and only return the `id`
   * const adminUserProfileWithIdOnly = await prisma.adminUserProfile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AdminUserProfileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AdminUserProfileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdminUserProfilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AdminUserProfile.
   * @param {AdminUserProfileDeleteArgs} args - Arguments to delete one AdminUserProfile.
   * @example
   * // Delete one AdminUserProfile
   * const AdminUserProfile = await prisma.adminUserProfile.delete({
   *   where: {
   *     // ... filter to delete one AdminUserProfile
   *   }
   * })
   * 
   */
  delete<T extends AdminUserProfileDeleteArgs>(args: Prisma.SelectSubset<T, AdminUserProfileDeleteArgs<ExtArgs>>): Prisma.Prisma__AdminUserProfileClient<runtime.Types.Result.GetResult<Prisma.$AdminUserProfilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AdminUserProfile.
   * @param {AdminUserProfileUpdateArgs} args - Arguments to update one AdminUserProfile.
   * @example
   * // Update one AdminUserProfile
   * const adminUserProfile = await prisma.adminUserProfile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AdminUserProfileUpdateArgs>(args: Prisma.SelectSubset<T, AdminUserProfileUpdateArgs<ExtArgs>>): Prisma.Prisma__AdminUserProfileClient<runtime.Types.Result.GetResult<Prisma.$AdminUserProfilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AdminUserProfiles.
   * @param {AdminUserProfileDeleteManyArgs} args - Arguments to filter AdminUserProfiles to delete.
   * @example
   * // Delete a few AdminUserProfiles
   * const { count } = await prisma.adminUserProfile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AdminUserProfileDeleteManyArgs>(args?: Prisma.SelectSubset<T, AdminUserProfileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AdminUserProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminUserProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AdminUserProfiles
   * const adminUserProfile = await prisma.adminUserProfile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AdminUserProfileUpdateManyArgs>(args: Prisma.SelectSubset<T, AdminUserProfileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AdminUserProfiles and returns the data updated in the database.
   * @param {AdminUserProfileUpdateManyAndReturnArgs} args - Arguments to update many AdminUserProfiles.
   * @example
   * // Update many AdminUserProfiles
   * const adminUserProfile = await prisma.adminUserProfile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AdminUserProfiles and only return the `id`
   * const adminUserProfileWithIdOnly = await prisma.adminUserProfile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AdminUserProfileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AdminUserProfileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdminUserProfilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AdminUserProfile.
   * @param {AdminUserProfileUpsertArgs} args - Arguments to update or create a AdminUserProfile.
   * @example
   * // Update or create a AdminUserProfile
   * const adminUserProfile = await prisma.adminUserProfile.upsert({
   *   create: {
   *     // ... data to create a AdminUserProfile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AdminUserProfile we want to update
   *   }
   * })
   */
  upsert<T extends AdminUserProfileUpsertArgs>(args: Prisma.SelectSubset<T, AdminUserProfileUpsertArgs<ExtArgs>>): Prisma.Prisma__AdminUserProfileClient<runtime.Types.Result.GetResult<Prisma.$AdminUserProfilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AdminUserProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminUserProfileCountArgs} args - Arguments to filter AdminUserProfiles to count.
   * @example
   * // Count the number of AdminUserProfiles
   * const count = await prisma.adminUserProfile.count({
   *   where: {
   *     // ... the filter for the AdminUserProfiles we want to count
   *   }
   * })
  **/
  count<T extends AdminUserProfileCountArgs>(
    args?: Prisma.Subset<T, AdminUserProfileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AdminUserProfileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AdminUserProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminUserProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AdminUserProfileAggregateArgs>(args: Prisma.Subset<T, AdminUserProfileAggregateArgs>): Prisma.PrismaPromise<GetAdminUserProfileAggregateType<T>>

  /**
   * Group by AdminUserProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminUserProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AdminUserProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AdminUserProfileGroupByArgs['orderBy'] }
      : { orderBy?: AdminUserProfileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AdminUserProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAdminUserProfileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AdminUserProfile model
 */
readonly fields: AdminUserProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AdminUserProfile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AdminUserProfileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.AdminUserProfile$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AdminUserProfile$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AdminUserProfile model
 */
export interface AdminUserProfileFieldRefs {
  readonly id: Prisma.FieldRef<"AdminUserProfile", 'String'>
  readonly userId: Prisma.FieldRef<"AdminUserProfile", 'String'>
  readonly firstName: Prisma.FieldRef<"AdminUserProfile", 'String'>
  readonly lastName: Prisma.FieldRef<"AdminUserProfile", 'String'>
  readonly emailAddress: Prisma.FieldRef<"AdminUserProfile", 'String'>
  readonly phoneNumber: Prisma.FieldRef<"AdminUserProfile", 'String'>
  readonly department: Prisma.FieldRef<"AdminUserProfile", 'String'>
  readonly position: Prisma.FieldRef<"AdminUserProfile", 'String'>
  readonly staffId: Prisma.FieldRef<"AdminUserProfile", 'String'>
  readonly isActive: Prisma.FieldRef<"AdminUserProfile", 'Boolean'>
  readonly isVerified: Prisma.FieldRef<"AdminUserProfile", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"AdminUserProfile", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AdminUserProfile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AdminUserProfile findUnique
 */
export type AdminUserProfileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminUserProfile
   */
  select?: Prisma.AdminUserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminUserProfile
   */
  omit?: Prisma.AdminUserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminUserProfileInclude<ExtArgs> | null
  /**
   * Filter, which AdminUserProfile to fetch.
   */
  where: Prisma.AdminUserProfileWhereUniqueInput
}

/**
 * AdminUserProfile findUniqueOrThrow
 */
export type AdminUserProfileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminUserProfile
   */
  select?: Prisma.AdminUserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminUserProfile
   */
  omit?: Prisma.AdminUserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminUserProfileInclude<ExtArgs> | null
  /**
   * Filter, which AdminUserProfile to fetch.
   */
  where: Prisma.AdminUserProfileWhereUniqueInput
}

/**
 * AdminUserProfile findFirst
 */
export type AdminUserProfileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminUserProfile
   */
  select?: Prisma.AdminUserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminUserProfile
   */
  omit?: Prisma.AdminUserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminUserProfileInclude<ExtArgs> | null
  /**
   * Filter, which AdminUserProfile to fetch.
   */
  where?: Prisma.AdminUserProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdminUserProfiles to fetch.
   */
  orderBy?: Prisma.AdminUserProfileOrderByWithRelationInput | Prisma.AdminUserProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AdminUserProfiles.
   */
  cursor?: Prisma.AdminUserProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdminUserProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdminUserProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdminUserProfiles.
   */
  distinct?: Prisma.AdminUserProfileScalarFieldEnum | Prisma.AdminUserProfileScalarFieldEnum[]
}

/**
 * AdminUserProfile findFirstOrThrow
 */
export type AdminUserProfileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminUserProfile
   */
  select?: Prisma.AdminUserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminUserProfile
   */
  omit?: Prisma.AdminUserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminUserProfileInclude<ExtArgs> | null
  /**
   * Filter, which AdminUserProfile to fetch.
   */
  where?: Prisma.AdminUserProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdminUserProfiles to fetch.
   */
  orderBy?: Prisma.AdminUserProfileOrderByWithRelationInput | Prisma.AdminUserProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AdminUserProfiles.
   */
  cursor?: Prisma.AdminUserProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdminUserProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdminUserProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdminUserProfiles.
   */
  distinct?: Prisma.AdminUserProfileScalarFieldEnum | Prisma.AdminUserProfileScalarFieldEnum[]
}

/**
 * AdminUserProfile findMany
 */
export type AdminUserProfileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminUserProfile
   */
  select?: Prisma.AdminUserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminUserProfile
   */
  omit?: Prisma.AdminUserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminUserProfileInclude<ExtArgs> | null
  /**
   * Filter, which AdminUserProfiles to fetch.
   */
  where?: Prisma.AdminUserProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdminUserProfiles to fetch.
   */
  orderBy?: Prisma.AdminUserProfileOrderByWithRelationInput | Prisma.AdminUserProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AdminUserProfiles.
   */
  cursor?: Prisma.AdminUserProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdminUserProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdminUserProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdminUserProfiles.
   */
  distinct?: Prisma.AdminUserProfileScalarFieldEnum | Prisma.AdminUserProfileScalarFieldEnum[]
}

/**
 * AdminUserProfile create
 */
export type AdminUserProfileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminUserProfile
   */
  select?: Prisma.AdminUserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminUserProfile
   */
  omit?: Prisma.AdminUserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminUserProfileInclude<ExtArgs> | null
  /**
   * The data needed to create a AdminUserProfile.
   */
  data: Prisma.XOR<Prisma.AdminUserProfileCreateInput, Prisma.AdminUserProfileUncheckedCreateInput>
}

/**
 * AdminUserProfile createMany
 */
export type AdminUserProfileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AdminUserProfiles.
   */
  data: Prisma.AdminUserProfileCreateManyInput | Prisma.AdminUserProfileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AdminUserProfile createManyAndReturn
 */
export type AdminUserProfileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminUserProfile
   */
  select?: Prisma.AdminUserProfileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AdminUserProfile
   */
  omit?: Prisma.AdminUserProfileOmit<ExtArgs> | null
  /**
   * The data used to create many AdminUserProfiles.
   */
  data: Prisma.AdminUserProfileCreateManyInput | Prisma.AdminUserProfileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminUserProfileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AdminUserProfile update
 */
export type AdminUserProfileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminUserProfile
   */
  select?: Prisma.AdminUserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminUserProfile
   */
  omit?: Prisma.AdminUserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminUserProfileInclude<ExtArgs> | null
  /**
   * The data needed to update a AdminUserProfile.
   */
  data: Prisma.XOR<Prisma.AdminUserProfileUpdateInput, Prisma.AdminUserProfileUncheckedUpdateInput>
  /**
   * Choose, which AdminUserProfile to update.
   */
  where: Prisma.AdminUserProfileWhereUniqueInput
}

/**
 * AdminUserProfile updateMany
 */
export type AdminUserProfileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AdminUserProfiles.
   */
  data: Prisma.XOR<Prisma.AdminUserProfileUpdateManyMutationInput, Prisma.AdminUserProfileUncheckedUpdateManyInput>
  /**
   * Filter which AdminUserProfiles to update
   */
  where?: Prisma.AdminUserProfileWhereInput
  /**
   * Limit how many AdminUserProfiles to update.
   */
  limit?: number
}

/**
 * AdminUserProfile updateManyAndReturn
 */
export type AdminUserProfileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminUserProfile
   */
  select?: Prisma.AdminUserProfileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AdminUserProfile
   */
  omit?: Prisma.AdminUserProfileOmit<ExtArgs> | null
  /**
   * The data used to update AdminUserProfiles.
   */
  data: Prisma.XOR<Prisma.AdminUserProfileUpdateManyMutationInput, Prisma.AdminUserProfileUncheckedUpdateManyInput>
  /**
   * Filter which AdminUserProfiles to update
   */
  where?: Prisma.AdminUserProfileWhereInput
  /**
   * Limit how many AdminUserProfiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminUserProfileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AdminUserProfile upsert
 */
export type AdminUserProfileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminUserProfile
   */
  select?: Prisma.AdminUserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminUserProfile
   */
  omit?: Prisma.AdminUserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminUserProfileInclude<ExtArgs> | null
  /**
   * The filter to search for the AdminUserProfile to update in case it exists.
   */
  where: Prisma.AdminUserProfileWhereUniqueInput
  /**
   * In case the AdminUserProfile found by the `where` argument doesn't exist, create a new AdminUserProfile with this data.
   */
  create: Prisma.XOR<Prisma.AdminUserProfileCreateInput, Prisma.AdminUserProfileUncheckedCreateInput>
  /**
   * In case the AdminUserProfile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AdminUserProfileUpdateInput, Prisma.AdminUserProfileUncheckedUpdateInput>
}

/**
 * AdminUserProfile delete
 */
export type AdminUserProfileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminUserProfile
   */
  select?: Prisma.AdminUserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminUserProfile
   */
  omit?: Prisma.AdminUserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminUserProfileInclude<ExtArgs> | null
  /**
   * Filter which AdminUserProfile to delete.
   */
  where: Prisma.AdminUserProfileWhereUniqueInput
}

/**
 * AdminUserProfile deleteMany
 */
export type AdminUserProfileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AdminUserProfiles to delete
   */
  where?: Prisma.AdminUserProfileWhereInput
  /**
   * Limit how many AdminUserProfiles to delete.
   */
  limit?: number
}

/**
 * AdminUserProfile.user
 */
export type AdminUserProfile$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * AdminUserProfile without action
 */
export type AdminUserProfileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminUserProfile
   */
  select?: Prisma.AdminUserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminUserProfile
   */
  omit?: Prisma.AdminUserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminUserProfileInclude<ExtArgs> | null
}
