
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LoanStatusHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LoanStatusHistory
 * 
 */
export type LoanStatusHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$LoanStatusHistoryPayload>

export type AggregateLoanStatusHistory = {
  _count: LoanStatusHistoryCountAggregateOutputType | null
  _min: LoanStatusHistoryMinAggregateOutputType | null
  _max: LoanStatusHistoryMaxAggregateOutputType | null
}

export type LoanStatusHistoryMinAggregateOutputType = {
  id: string | null
  loanId: string | null
  fromStatus: $Enums.LoanStatus | null
  toStatus: $Enums.LoanStatus | null
  changedBy: string | null
  changeDate: Date | null
  reason: string | null
}

export type LoanStatusHistoryMaxAggregateOutputType = {
  id: string | null
  loanId: string | null
  fromStatus: $Enums.LoanStatus | null
  toStatus: $Enums.LoanStatus | null
  changedBy: string | null
  changeDate: Date | null
  reason: string | null
}

export type LoanStatusHistoryCountAggregateOutputType = {
  id: number
  loanId: number
  fromStatus: number
  toStatus: number
  changedBy: number
  changeDate: number
  reason: number
  _all: number
}


export type LoanStatusHistoryMinAggregateInputType = {
  id?: true
  loanId?: true
  fromStatus?: true
  toStatus?: true
  changedBy?: true
  changeDate?: true
  reason?: true
}

export type LoanStatusHistoryMaxAggregateInputType = {
  id?: true
  loanId?: true
  fromStatus?: true
  toStatus?: true
  changedBy?: true
  changeDate?: true
  reason?: true
}

export type LoanStatusHistoryCountAggregateInputType = {
  id?: true
  loanId?: true
  fromStatus?: true
  toStatus?: true
  changedBy?: true
  changeDate?: true
  reason?: true
  _all?: true
}

export type LoanStatusHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LoanStatusHistory to aggregate.
   */
  where?: Prisma.LoanStatusHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoanStatusHistories to fetch.
   */
  orderBy?: Prisma.LoanStatusHistoryOrderByWithRelationInput | Prisma.LoanStatusHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LoanStatusHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoanStatusHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoanStatusHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LoanStatusHistories
  **/
  _count?: true | LoanStatusHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LoanStatusHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LoanStatusHistoryMaxAggregateInputType
}

export type GetLoanStatusHistoryAggregateType<T extends LoanStatusHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateLoanStatusHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLoanStatusHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateLoanStatusHistory[P]>
}




export type LoanStatusHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LoanStatusHistoryWhereInput
  orderBy?: Prisma.LoanStatusHistoryOrderByWithAggregationInput | Prisma.LoanStatusHistoryOrderByWithAggregationInput[]
  by: Prisma.LoanStatusHistoryScalarFieldEnum[] | Prisma.LoanStatusHistoryScalarFieldEnum
  having?: Prisma.LoanStatusHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LoanStatusHistoryCountAggregateInputType | true
  _min?: LoanStatusHistoryMinAggregateInputType
  _max?: LoanStatusHistoryMaxAggregateInputType
}

export type LoanStatusHistoryGroupByOutputType = {
  id: string
  loanId: string
  fromStatus: $Enums.LoanStatus
  toStatus: $Enums.LoanStatus
  changedBy: string
  changeDate: Date
  reason: string | null
  _count: LoanStatusHistoryCountAggregateOutputType | null
  _min: LoanStatusHistoryMinAggregateOutputType | null
  _max: LoanStatusHistoryMaxAggregateOutputType | null
}

export type GetLoanStatusHistoryGroupByPayload<T extends LoanStatusHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LoanStatusHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LoanStatusHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LoanStatusHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LoanStatusHistoryGroupByOutputType[P]>
      }
    >
  >



export type LoanStatusHistoryWhereInput = {
  AND?: Prisma.LoanStatusHistoryWhereInput | Prisma.LoanStatusHistoryWhereInput[]
  OR?: Prisma.LoanStatusHistoryWhereInput[]
  NOT?: Prisma.LoanStatusHistoryWhereInput | Prisma.LoanStatusHistoryWhereInput[]
  id?: Prisma.UuidFilter<"LoanStatusHistory"> | string
  loanId?: Prisma.UuidFilter<"LoanStatusHistory"> | string
  fromStatus?: Prisma.EnumLoanStatusFilter<"LoanStatusHistory"> | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFilter<"LoanStatusHistory"> | $Enums.LoanStatus
  changedBy?: Prisma.UuidFilter<"LoanStatusHistory"> | string
  changeDate?: Prisma.DateTimeFilter<"LoanStatusHistory"> | Date | string
  reason?: Prisma.StringNullableFilter<"LoanStatusHistory"> | string | null
  loan?: Prisma.XOR<Prisma.LoanScalarRelationFilter, Prisma.LoanWhereInput>
  changeUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type LoanStatusHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  fromStatus?: Prisma.SortOrder
  toStatus?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  changeDate?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  loan?: Prisma.LoanOrderByWithRelationInput
  changeUser?: Prisma.UserOrderByWithRelationInput
}

export type LoanStatusHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LoanStatusHistoryWhereInput | Prisma.LoanStatusHistoryWhereInput[]
  OR?: Prisma.LoanStatusHistoryWhereInput[]
  NOT?: Prisma.LoanStatusHistoryWhereInput | Prisma.LoanStatusHistoryWhereInput[]
  loanId?: Prisma.UuidFilter<"LoanStatusHistory"> | string
  fromStatus?: Prisma.EnumLoanStatusFilter<"LoanStatusHistory"> | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFilter<"LoanStatusHistory"> | $Enums.LoanStatus
  changedBy?: Prisma.UuidFilter<"LoanStatusHistory"> | string
  changeDate?: Prisma.DateTimeFilter<"LoanStatusHistory"> | Date | string
  reason?: Prisma.StringNullableFilter<"LoanStatusHistory"> | string | null
  loan?: Prisma.XOR<Prisma.LoanScalarRelationFilter, Prisma.LoanWhereInput>
  changeUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type LoanStatusHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  fromStatus?: Prisma.SortOrder
  toStatus?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  changeDate?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.LoanStatusHistoryCountOrderByAggregateInput
  _max?: Prisma.LoanStatusHistoryMaxOrderByAggregateInput
  _min?: Prisma.LoanStatusHistoryMinOrderByAggregateInput
}

export type LoanStatusHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.LoanStatusHistoryScalarWhereWithAggregatesInput | Prisma.LoanStatusHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.LoanStatusHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LoanStatusHistoryScalarWhereWithAggregatesInput | Prisma.LoanStatusHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"LoanStatusHistory"> | string
  loanId?: Prisma.UuidWithAggregatesFilter<"LoanStatusHistory"> | string
  fromStatus?: Prisma.EnumLoanStatusWithAggregatesFilter<"LoanStatusHistory"> | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusWithAggregatesFilter<"LoanStatusHistory"> | $Enums.LoanStatus
  changedBy?: Prisma.UuidWithAggregatesFilter<"LoanStatusHistory"> | string
  changeDate?: Prisma.DateTimeWithAggregatesFilter<"LoanStatusHistory"> | Date | string
  reason?: Prisma.StringNullableWithAggregatesFilter<"LoanStatusHistory"> | string | null
}

export type LoanStatusHistoryCreateInput = {
  id?: string
  fromStatus: $Enums.LoanStatus
  toStatus: $Enums.LoanStatus
  changeDate?: Date | string
  reason?: string | null
  loan: Prisma.LoanCreateNestedOneWithoutStatusHistoryInput
  changeUser: Prisma.UserCreateNestedOneWithoutStatusChangesInput
}

export type LoanStatusHistoryUncheckedCreateInput = {
  id?: string
  loanId: string
  fromStatus: $Enums.LoanStatus
  toStatus: $Enums.LoanStatus
  changedBy: string
  changeDate?: Date | string
  reason?: string | null
}

export type LoanStatusHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  changeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loan?: Prisma.LoanUpdateOneRequiredWithoutStatusHistoryNestedInput
  changeUser?: Prisma.UserUpdateOneRequiredWithoutStatusChangesNestedInput
}

export type LoanStatusHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.StringFieldUpdateOperationsInput | string
  fromStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  changeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LoanStatusHistoryCreateManyInput = {
  id?: string
  loanId: string
  fromStatus: $Enums.LoanStatus
  toStatus: $Enums.LoanStatus
  changedBy: string
  changeDate?: Date | string
  reason?: string | null
}

export type LoanStatusHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  changeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LoanStatusHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.StringFieldUpdateOperationsInput | string
  fromStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  changeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LoanStatusHistoryListRelationFilter = {
  every?: Prisma.LoanStatusHistoryWhereInput
  some?: Prisma.LoanStatusHistoryWhereInput
  none?: Prisma.LoanStatusHistoryWhereInput
}

export type LoanStatusHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LoanStatusHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  fromStatus?: Prisma.SortOrder
  toStatus?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  changeDate?: Prisma.SortOrder
  reason?: Prisma.SortOrder
}

export type LoanStatusHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  fromStatus?: Prisma.SortOrder
  toStatus?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  changeDate?: Prisma.SortOrder
  reason?: Prisma.SortOrder
}

export type LoanStatusHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  fromStatus?: Prisma.SortOrder
  toStatus?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  changeDate?: Prisma.SortOrder
  reason?: Prisma.SortOrder
}

export type LoanStatusHistoryCreateNestedManyWithoutChangeUserInput = {
  create?: Prisma.XOR<Prisma.LoanStatusHistoryCreateWithoutChangeUserInput, Prisma.LoanStatusHistoryUncheckedCreateWithoutChangeUserInput> | Prisma.LoanStatusHistoryCreateWithoutChangeUserInput[] | Prisma.LoanStatusHistoryUncheckedCreateWithoutChangeUserInput[]
  connectOrCreate?: Prisma.LoanStatusHistoryCreateOrConnectWithoutChangeUserInput | Prisma.LoanStatusHistoryCreateOrConnectWithoutChangeUserInput[]
  createMany?: Prisma.LoanStatusHistoryCreateManyChangeUserInputEnvelope
  connect?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
}

export type LoanStatusHistoryUncheckedCreateNestedManyWithoutChangeUserInput = {
  create?: Prisma.XOR<Prisma.LoanStatusHistoryCreateWithoutChangeUserInput, Prisma.LoanStatusHistoryUncheckedCreateWithoutChangeUserInput> | Prisma.LoanStatusHistoryCreateWithoutChangeUserInput[] | Prisma.LoanStatusHistoryUncheckedCreateWithoutChangeUserInput[]
  connectOrCreate?: Prisma.LoanStatusHistoryCreateOrConnectWithoutChangeUserInput | Prisma.LoanStatusHistoryCreateOrConnectWithoutChangeUserInput[]
  createMany?: Prisma.LoanStatusHistoryCreateManyChangeUserInputEnvelope
  connect?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
}

export type LoanStatusHistoryUpdateManyWithoutChangeUserNestedInput = {
  create?: Prisma.XOR<Prisma.LoanStatusHistoryCreateWithoutChangeUserInput, Prisma.LoanStatusHistoryUncheckedCreateWithoutChangeUserInput> | Prisma.LoanStatusHistoryCreateWithoutChangeUserInput[] | Prisma.LoanStatusHistoryUncheckedCreateWithoutChangeUserInput[]
  connectOrCreate?: Prisma.LoanStatusHistoryCreateOrConnectWithoutChangeUserInput | Prisma.LoanStatusHistoryCreateOrConnectWithoutChangeUserInput[]
  upsert?: Prisma.LoanStatusHistoryUpsertWithWhereUniqueWithoutChangeUserInput | Prisma.LoanStatusHistoryUpsertWithWhereUniqueWithoutChangeUserInput[]
  createMany?: Prisma.LoanStatusHistoryCreateManyChangeUserInputEnvelope
  set?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  disconnect?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  delete?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  connect?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  update?: Prisma.LoanStatusHistoryUpdateWithWhereUniqueWithoutChangeUserInput | Prisma.LoanStatusHistoryUpdateWithWhereUniqueWithoutChangeUserInput[]
  updateMany?: Prisma.LoanStatusHistoryUpdateManyWithWhereWithoutChangeUserInput | Prisma.LoanStatusHistoryUpdateManyWithWhereWithoutChangeUserInput[]
  deleteMany?: Prisma.LoanStatusHistoryScalarWhereInput | Prisma.LoanStatusHistoryScalarWhereInput[]
}

export type LoanStatusHistoryUncheckedUpdateManyWithoutChangeUserNestedInput = {
  create?: Prisma.XOR<Prisma.LoanStatusHistoryCreateWithoutChangeUserInput, Prisma.LoanStatusHistoryUncheckedCreateWithoutChangeUserInput> | Prisma.LoanStatusHistoryCreateWithoutChangeUserInput[] | Prisma.LoanStatusHistoryUncheckedCreateWithoutChangeUserInput[]
  connectOrCreate?: Prisma.LoanStatusHistoryCreateOrConnectWithoutChangeUserInput | Prisma.LoanStatusHistoryCreateOrConnectWithoutChangeUserInput[]
  upsert?: Prisma.LoanStatusHistoryUpsertWithWhereUniqueWithoutChangeUserInput | Prisma.LoanStatusHistoryUpsertWithWhereUniqueWithoutChangeUserInput[]
  createMany?: Prisma.LoanStatusHistoryCreateManyChangeUserInputEnvelope
  set?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  disconnect?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  delete?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  connect?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  update?: Prisma.LoanStatusHistoryUpdateWithWhereUniqueWithoutChangeUserInput | Prisma.LoanStatusHistoryUpdateWithWhereUniqueWithoutChangeUserInput[]
  updateMany?: Prisma.LoanStatusHistoryUpdateManyWithWhereWithoutChangeUserInput | Prisma.LoanStatusHistoryUpdateManyWithWhereWithoutChangeUserInput[]
  deleteMany?: Prisma.LoanStatusHistoryScalarWhereInput | Prisma.LoanStatusHistoryScalarWhereInput[]
}

export type LoanStatusHistoryCreateNestedManyWithoutLoanInput = {
  create?: Prisma.XOR<Prisma.LoanStatusHistoryCreateWithoutLoanInput, Prisma.LoanStatusHistoryUncheckedCreateWithoutLoanInput> | Prisma.LoanStatusHistoryCreateWithoutLoanInput[] | Prisma.LoanStatusHistoryUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.LoanStatusHistoryCreateOrConnectWithoutLoanInput | Prisma.LoanStatusHistoryCreateOrConnectWithoutLoanInput[]
  createMany?: Prisma.LoanStatusHistoryCreateManyLoanInputEnvelope
  connect?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
}

export type LoanStatusHistoryUncheckedCreateNestedManyWithoutLoanInput = {
  create?: Prisma.XOR<Prisma.LoanStatusHistoryCreateWithoutLoanInput, Prisma.LoanStatusHistoryUncheckedCreateWithoutLoanInput> | Prisma.LoanStatusHistoryCreateWithoutLoanInput[] | Prisma.LoanStatusHistoryUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.LoanStatusHistoryCreateOrConnectWithoutLoanInput | Prisma.LoanStatusHistoryCreateOrConnectWithoutLoanInput[]
  createMany?: Prisma.LoanStatusHistoryCreateManyLoanInputEnvelope
  connect?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
}

export type LoanStatusHistoryUpdateManyWithoutLoanNestedInput = {
  create?: Prisma.XOR<Prisma.LoanStatusHistoryCreateWithoutLoanInput, Prisma.LoanStatusHistoryUncheckedCreateWithoutLoanInput> | Prisma.LoanStatusHistoryCreateWithoutLoanInput[] | Prisma.LoanStatusHistoryUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.LoanStatusHistoryCreateOrConnectWithoutLoanInput | Prisma.LoanStatusHistoryCreateOrConnectWithoutLoanInput[]
  upsert?: Prisma.LoanStatusHistoryUpsertWithWhereUniqueWithoutLoanInput | Prisma.LoanStatusHistoryUpsertWithWhereUniqueWithoutLoanInput[]
  createMany?: Prisma.LoanStatusHistoryCreateManyLoanInputEnvelope
  set?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  disconnect?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  delete?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  connect?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  update?: Prisma.LoanStatusHistoryUpdateWithWhereUniqueWithoutLoanInput | Prisma.LoanStatusHistoryUpdateWithWhereUniqueWithoutLoanInput[]
  updateMany?: Prisma.LoanStatusHistoryUpdateManyWithWhereWithoutLoanInput | Prisma.LoanStatusHistoryUpdateManyWithWhereWithoutLoanInput[]
  deleteMany?: Prisma.LoanStatusHistoryScalarWhereInput | Prisma.LoanStatusHistoryScalarWhereInput[]
}

export type LoanStatusHistoryUncheckedUpdateManyWithoutLoanNestedInput = {
  create?: Prisma.XOR<Prisma.LoanStatusHistoryCreateWithoutLoanInput, Prisma.LoanStatusHistoryUncheckedCreateWithoutLoanInput> | Prisma.LoanStatusHistoryCreateWithoutLoanInput[] | Prisma.LoanStatusHistoryUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.LoanStatusHistoryCreateOrConnectWithoutLoanInput | Prisma.LoanStatusHistoryCreateOrConnectWithoutLoanInput[]
  upsert?: Prisma.LoanStatusHistoryUpsertWithWhereUniqueWithoutLoanInput | Prisma.LoanStatusHistoryUpsertWithWhereUniqueWithoutLoanInput[]
  createMany?: Prisma.LoanStatusHistoryCreateManyLoanInputEnvelope
  set?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  disconnect?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  delete?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  connect?: Prisma.LoanStatusHistoryWhereUniqueInput | Prisma.LoanStatusHistoryWhereUniqueInput[]
  update?: Prisma.LoanStatusHistoryUpdateWithWhereUniqueWithoutLoanInput | Prisma.LoanStatusHistoryUpdateWithWhereUniqueWithoutLoanInput[]
  updateMany?: Prisma.LoanStatusHistoryUpdateManyWithWhereWithoutLoanInput | Prisma.LoanStatusHistoryUpdateManyWithWhereWithoutLoanInput[]
  deleteMany?: Prisma.LoanStatusHistoryScalarWhereInput | Prisma.LoanStatusHistoryScalarWhereInput[]
}

export type LoanStatusHistoryCreateWithoutChangeUserInput = {
  id?: string
  fromStatus: $Enums.LoanStatus
  toStatus: $Enums.LoanStatus
  changeDate?: Date | string
  reason?: string | null
  loan: Prisma.LoanCreateNestedOneWithoutStatusHistoryInput
}

export type LoanStatusHistoryUncheckedCreateWithoutChangeUserInput = {
  id?: string
  loanId: string
  fromStatus: $Enums.LoanStatus
  toStatus: $Enums.LoanStatus
  changeDate?: Date | string
  reason?: string | null
}

export type LoanStatusHistoryCreateOrConnectWithoutChangeUserInput = {
  where: Prisma.LoanStatusHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.LoanStatusHistoryCreateWithoutChangeUserInput, Prisma.LoanStatusHistoryUncheckedCreateWithoutChangeUserInput>
}

export type LoanStatusHistoryCreateManyChangeUserInputEnvelope = {
  data: Prisma.LoanStatusHistoryCreateManyChangeUserInput | Prisma.LoanStatusHistoryCreateManyChangeUserInput[]
  skipDuplicates?: boolean
}

export type LoanStatusHistoryUpsertWithWhereUniqueWithoutChangeUserInput = {
  where: Prisma.LoanStatusHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.LoanStatusHistoryUpdateWithoutChangeUserInput, Prisma.LoanStatusHistoryUncheckedUpdateWithoutChangeUserInput>
  create: Prisma.XOR<Prisma.LoanStatusHistoryCreateWithoutChangeUserInput, Prisma.LoanStatusHistoryUncheckedCreateWithoutChangeUserInput>
}

export type LoanStatusHistoryUpdateWithWhereUniqueWithoutChangeUserInput = {
  where: Prisma.LoanStatusHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.LoanStatusHistoryUpdateWithoutChangeUserInput, Prisma.LoanStatusHistoryUncheckedUpdateWithoutChangeUserInput>
}

export type LoanStatusHistoryUpdateManyWithWhereWithoutChangeUserInput = {
  where: Prisma.LoanStatusHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.LoanStatusHistoryUpdateManyMutationInput, Prisma.LoanStatusHistoryUncheckedUpdateManyWithoutChangeUserInput>
}

export type LoanStatusHistoryScalarWhereInput = {
  AND?: Prisma.LoanStatusHistoryScalarWhereInput | Prisma.LoanStatusHistoryScalarWhereInput[]
  OR?: Prisma.LoanStatusHistoryScalarWhereInput[]
  NOT?: Prisma.LoanStatusHistoryScalarWhereInput | Prisma.LoanStatusHistoryScalarWhereInput[]
  id?: Prisma.UuidFilter<"LoanStatusHistory"> | string
  loanId?: Prisma.UuidFilter<"LoanStatusHistory"> | string
  fromStatus?: Prisma.EnumLoanStatusFilter<"LoanStatusHistory"> | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFilter<"LoanStatusHistory"> | $Enums.LoanStatus
  changedBy?: Prisma.UuidFilter<"LoanStatusHistory"> | string
  changeDate?: Prisma.DateTimeFilter<"LoanStatusHistory"> | Date | string
  reason?: Prisma.StringNullableFilter<"LoanStatusHistory"> | string | null
}

export type LoanStatusHistoryCreateWithoutLoanInput = {
  id?: string
  fromStatus: $Enums.LoanStatus
  toStatus: $Enums.LoanStatus
  changeDate?: Date | string
  reason?: string | null
  changeUser: Prisma.UserCreateNestedOneWithoutStatusChangesInput
}

export type LoanStatusHistoryUncheckedCreateWithoutLoanInput = {
  id?: string
  fromStatus: $Enums.LoanStatus
  toStatus: $Enums.LoanStatus
  changedBy: string
  changeDate?: Date | string
  reason?: string | null
}

export type LoanStatusHistoryCreateOrConnectWithoutLoanInput = {
  where: Prisma.LoanStatusHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.LoanStatusHistoryCreateWithoutLoanInput, Prisma.LoanStatusHistoryUncheckedCreateWithoutLoanInput>
}

export type LoanStatusHistoryCreateManyLoanInputEnvelope = {
  data: Prisma.LoanStatusHistoryCreateManyLoanInput | Prisma.LoanStatusHistoryCreateManyLoanInput[]
  skipDuplicates?: boolean
}

export type LoanStatusHistoryUpsertWithWhereUniqueWithoutLoanInput = {
  where: Prisma.LoanStatusHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.LoanStatusHistoryUpdateWithoutLoanInput, Prisma.LoanStatusHistoryUncheckedUpdateWithoutLoanInput>
  create: Prisma.XOR<Prisma.LoanStatusHistoryCreateWithoutLoanInput, Prisma.LoanStatusHistoryUncheckedCreateWithoutLoanInput>
}

export type LoanStatusHistoryUpdateWithWhereUniqueWithoutLoanInput = {
  where: Prisma.LoanStatusHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.LoanStatusHistoryUpdateWithoutLoanInput, Prisma.LoanStatusHistoryUncheckedUpdateWithoutLoanInput>
}

export type LoanStatusHistoryUpdateManyWithWhereWithoutLoanInput = {
  where: Prisma.LoanStatusHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.LoanStatusHistoryUpdateManyMutationInput, Prisma.LoanStatusHistoryUncheckedUpdateManyWithoutLoanInput>
}

export type LoanStatusHistoryCreateManyChangeUserInput = {
  id?: string
  loanId: string
  fromStatus: $Enums.LoanStatus
  toStatus: $Enums.LoanStatus
  changeDate?: Date | string
  reason?: string | null
}

export type LoanStatusHistoryUpdateWithoutChangeUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  changeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loan?: Prisma.LoanUpdateOneRequiredWithoutStatusHistoryNestedInput
}

export type LoanStatusHistoryUncheckedUpdateWithoutChangeUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.StringFieldUpdateOperationsInput | string
  fromStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  changeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LoanStatusHistoryUncheckedUpdateManyWithoutChangeUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.StringFieldUpdateOperationsInput | string
  fromStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  changeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LoanStatusHistoryCreateManyLoanInput = {
  id?: string
  fromStatus: $Enums.LoanStatus
  toStatus: $Enums.LoanStatus
  changedBy: string
  changeDate?: Date | string
  reason?: string | null
}

export type LoanStatusHistoryUpdateWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  changeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changeUser?: Prisma.UserUpdateOneRequiredWithoutStatusChangesNestedInput
}

export type LoanStatusHistoryUncheckedUpdateWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  changeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LoanStatusHistoryUncheckedUpdateManyWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  toStatus?: Prisma.EnumLoanStatusFieldUpdateOperationsInput | $Enums.LoanStatus
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  changeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type LoanStatusHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  loanId?: boolean
  fromStatus?: boolean
  toStatus?: boolean
  changedBy?: boolean
  changeDate?: boolean
  reason?: boolean
  loan?: boolean | Prisma.LoanDefaultArgs<ExtArgs>
  changeUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["loanStatusHistory"]>

export type LoanStatusHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  loanId?: boolean
  fromStatus?: boolean
  toStatus?: boolean
  changedBy?: boolean
  changeDate?: boolean
  reason?: boolean
  loan?: boolean | Prisma.LoanDefaultArgs<ExtArgs>
  changeUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["loanStatusHistory"]>

export type LoanStatusHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  loanId?: boolean
  fromStatus?: boolean
  toStatus?: boolean
  changedBy?: boolean
  changeDate?: boolean
  reason?: boolean
  loan?: boolean | Prisma.LoanDefaultArgs<ExtArgs>
  changeUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["loanStatusHistory"]>

export type LoanStatusHistorySelectScalar = {
  id?: boolean
  loanId?: boolean
  fromStatus?: boolean
  toStatus?: boolean
  changedBy?: boolean
  changeDate?: boolean
  reason?: boolean
}

export type LoanStatusHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "loanId" | "fromStatus" | "toStatus" | "changedBy" | "changeDate" | "reason", ExtArgs["result"]["loanStatusHistory"]>
export type LoanStatusHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  loan?: boolean | Prisma.LoanDefaultArgs<ExtArgs>
  changeUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type LoanStatusHistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  loan?: boolean | Prisma.LoanDefaultArgs<ExtArgs>
  changeUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type LoanStatusHistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  loan?: boolean | Prisma.LoanDefaultArgs<ExtArgs>
  changeUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $LoanStatusHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LoanStatusHistory"
  objects: {
    loan: Prisma.$LoanPayload<ExtArgs>
    changeUser: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    loanId: string
    fromStatus: $Enums.LoanStatus
    toStatus: $Enums.LoanStatus
    changedBy: string
    changeDate: Date
    reason: string | null
  }, ExtArgs["result"]["loanStatusHistory"]>
  composites: {}
}

export type LoanStatusHistoryGetPayload<S extends boolean | null | undefined | LoanStatusHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LoanStatusHistoryPayload, S>

export type LoanStatusHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LoanStatusHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LoanStatusHistoryCountAggregateInputType | true
  }

export interface LoanStatusHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LoanStatusHistory'], meta: { name: 'LoanStatusHistory' } }
  /**
   * Find zero or one LoanStatusHistory that matches the filter.
   * @param {LoanStatusHistoryFindUniqueArgs} args - Arguments to find a LoanStatusHistory
   * @example
   * // Get one LoanStatusHistory
   * const loanStatusHistory = await prisma.loanStatusHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LoanStatusHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, LoanStatusHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LoanStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoanStatusHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LoanStatusHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LoanStatusHistoryFindUniqueOrThrowArgs} args - Arguments to find a LoanStatusHistory
   * @example
   * // Get one LoanStatusHistory
   * const loanStatusHistory = await prisma.loanStatusHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LoanStatusHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LoanStatusHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LoanStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoanStatusHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LoanStatusHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanStatusHistoryFindFirstArgs} args - Arguments to find a LoanStatusHistory
   * @example
   * // Get one LoanStatusHistory
   * const loanStatusHistory = await prisma.loanStatusHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LoanStatusHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, LoanStatusHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__LoanStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoanStatusHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LoanStatusHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanStatusHistoryFindFirstOrThrowArgs} args - Arguments to find a LoanStatusHistory
   * @example
   * // Get one LoanStatusHistory
   * const loanStatusHistory = await prisma.loanStatusHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LoanStatusHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LoanStatusHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LoanStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoanStatusHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LoanStatusHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanStatusHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LoanStatusHistories
   * const loanStatusHistories = await prisma.loanStatusHistory.findMany()
   * 
   * // Get first 10 LoanStatusHistories
   * const loanStatusHistories = await prisma.loanStatusHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const loanStatusHistoryWithIdOnly = await prisma.loanStatusHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LoanStatusHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, LoanStatusHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoanStatusHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LoanStatusHistory.
   * @param {LoanStatusHistoryCreateArgs} args - Arguments to create a LoanStatusHistory.
   * @example
   * // Create one LoanStatusHistory
   * const LoanStatusHistory = await prisma.loanStatusHistory.create({
   *   data: {
   *     // ... data to create a LoanStatusHistory
   *   }
   * })
   * 
   */
  create<T extends LoanStatusHistoryCreateArgs>(args: Prisma.SelectSubset<T, LoanStatusHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__LoanStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoanStatusHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LoanStatusHistories.
   * @param {LoanStatusHistoryCreateManyArgs} args - Arguments to create many LoanStatusHistories.
   * @example
   * // Create many LoanStatusHistories
   * const loanStatusHistory = await prisma.loanStatusHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LoanStatusHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, LoanStatusHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LoanStatusHistories and returns the data saved in the database.
   * @param {LoanStatusHistoryCreateManyAndReturnArgs} args - Arguments to create many LoanStatusHistories.
   * @example
   * // Create many LoanStatusHistories
   * const loanStatusHistory = await prisma.loanStatusHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LoanStatusHistories and only return the `id`
   * const loanStatusHistoryWithIdOnly = await prisma.loanStatusHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LoanStatusHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LoanStatusHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoanStatusHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LoanStatusHistory.
   * @param {LoanStatusHistoryDeleteArgs} args - Arguments to delete one LoanStatusHistory.
   * @example
   * // Delete one LoanStatusHistory
   * const LoanStatusHistory = await prisma.loanStatusHistory.delete({
   *   where: {
   *     // ... filter to delete one LoanStatusHistory
   *   }
   * })
   * 
   */
  delete<T extends LoanStatusHistoryDeleteArgs>(args: Prisma.SelectSubset<T, LoanStatusHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__LoanStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoanStatusHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LoanStatusHistory.
   * @param {LoanStatusHistoryUpdateArgs} args - Arguments to update one LoanStatusHistory.
   * @example
   * // Update one LoanStatusHistory
   * const loanStatusHistory = await prisma.loanStatusHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LoanStatusHistoryUpdateArgs>(args: Prisma.SelectSubset<T, LoanStatusHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__LoanStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoanStatusHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LoanStatusHistories.
   * @param {LoanStatusHistoryDeleteManyArgs} args - Arguments to filter LoanStatusHistories to delete.
   * @example
   * // Delete a few LoanStatusHistories
   * const { count } = await prisma.loanStatusHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LoanStatusHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, LoanStatusHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LoanStatusHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanStatusHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LoanStatusHistories
   * const loanStatusHistory = await prisma.loanStatusHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LoanStatusHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, LoanStatusHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LoanStatusHistories and returns the data updated in the database.
   * @param {LoanStatusHistoryUpdateManyAndReturnArgs} args - Arguments to update many LoanStatusHistories.
   * @example
   * // Update many LoanStatusHistories
   * const loanStatusHistory = await prisma.loanStatusHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LoanStatusHistories and only return the `id`
   * const loanStatusHistoryWithIdOnly = await prisma.loanStatusHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LoanStatusHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LoanStatusHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoanStatusHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LoanStatusHistory.
   * @param {LoanStatusHistoryUpsertArgs} args - Arguments to update or create a LoanStatusHistory.
   * @example
   * // Update or create a LoanStatusHistory
   * const loanStatusHistory = await prisma.loanStatusHistory.upsert({
   *   create: {
   *     // ... data to create a LoanStatusHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LoanStatusHistory we want to update
   *   }
   * })
   */
  upsert<T extends LoanStatusHistoryUpsertArgs>(args: Prisma.SelectSubset<T, LoanStatusHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__LoanStatusHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoanStatusHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LoanStatusHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanStatusHistoryCountArgs} args - Arguments to filter LoanStatusHistories to count.
   * @example
   * // Count the number of LoanStatusHistories
   * const count = await prisma.loanStatusHistory.count({
   *   where: {
   *     // ... the filter for the LoanStatusHistories we want to count
   *   }
   * })
  **/
  count<T extends LoanStatusHistoryCountArgs>(
    args?: Prisma.Subset<T, LoanStatusHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LoanStatusHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LoanStatusHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanStatusHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LoanStatusHistoryAggregateArgs>(args: Prisma.Subset<T, LoanStatusHistoryAggregateArgs>): Prisma.PrismaPromise<GetLoanStatusHistoryAggregateType<T>>

  /**
   * Group by LoanStatusHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanStatusHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LoanStatusHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LoanStatusHistoryGroupByArgs['orderBy'] }
      : { orderBy?: LoanStatusHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LoanStatusHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLoanStatusHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LoanStatusHistory model
 */
readonly fields: LoanStatusHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LoanStatusHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LoanStatusHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  loan<T extends Prisma.LoanDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LoanDefaultArgs<ExtArgs>>): Prisma.Prisma__LoanClient<runtime.Types.Result.GetResult<Prisma.$LoanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  changeUser<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LoanStatusHistory model
 */
export interface LoanStatusHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"LoanStatusHistory", 'String'>
  readonly loanId: Prisma.FieldRef<"LoanStatusHistory", 'String'>
  readonly fromStatus: Prisma.FieldRef<"LoanStatusHistory", 'LoanStatus'>
  readonly toStatus: Prisma.FieldRef<"LoanStatusHistory", 'LoanStatus'>
  readonly changedBy: Prisma.FieldRef<"LoanStatusHistory", 'String'>
  readonly changeDate: Prisma.FieldRef<"LoanStatusHistory", 'DateTime'>
  readonly reason: Prisma.FieldRef<"LoanStatusHistory", 'String'>
}
    

// Custom InputTypes
/**
 * LoanStatusHistory findUnique
 */
export type LoanStatusHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanStatusHistory
   */
  select?: Prisma.LoanStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanStatusHistory
   */
  omit?: Prisma.LoanStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanStatusHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LoanStatusHistory to fetch.
   */
  where: Prisma.LoanStatusHistoryWhereUniqueInput
}

/**
 * LoanStatusHistory findUniqueOrThrow
 */
export type LoanStatusHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanStatusHistory
   */
  select?: Prisma.LoanStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanStatusHistory
   */
  omit?: Prisma.LoanStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanStatusHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LoanStatusHistory to fetch.
   */
  where: Prisma.LoanStatusHistoryWhereUniqueInput
}

/**
 * LoanStatusHistory findFirst
 */
export type LoanStatusHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanStatusHistory
   */
  select?: Prisma.LoanStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanStatusHistory
   */
  omit?: Prisma.LoanStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanStatusHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LoanStatusHistory to fetch.
   */
  where?: Prisma.LoanStatusHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoanStatusHistories to fetch.
   */
  orderBy?: Prisma.LoanStatusHistoryOrderByWithRelationInput | Prisma.LoanStatusHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LoanStatusHistories.
   */
  cursor?: Prisma.LoanStatusHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoanStatusHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoanStatusHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoanStatusHistories.
   */
  distinct?: Prisma.LoanStatusHistoryScalarFieldEnum | Prisma.LoanStatusHistoryScalarFieldEnum[]
}

/**
 * LoanStatusHistory findFirstOrThrow
 */
export type LoanStatusHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanStatusHistory
   */
  select?: Prisma.LoanStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanStatusHistory
   */
  omit?: Prisma.LoanStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanStatusHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LoanStatusHistory to fetch.
   */
  where?: Prisma.LoanStatusHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoanStatusHistories to fetch.
   */
  orderBy?: Prisma.LoanStatusHistoryOrderByWithRelationInput | Prisma.LoanStatusHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LoanStatusHistories.
   */
  cursor?: Prisma.LoanStatusHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoanStatusHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoanStatusHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoanStatusHistories.
   */
  distinct?: Prisma.LoanStatusHistoryScalarFieldEnum | Prisma.LoanStatusHistoryScalarFieldEnum[]
}

/**
 * LoanStatusHistory findMany
 */
export type LoanStatusHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanStatusHistory
   */
  select?: Prisma.LoanStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanStatusHistory
   */
  omit?: Prisma.LoanStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanStatusHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LoanStatusHistories to fetch.
   */
  where?: Prisma.LoanStatusHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoanStatusHistories to fetch.
   */
  orderBy?: Prisma.LoanStatusHistoryOrderByWithRelationInput | Prisma.LoanStatusHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LoanStatusHistories.
   */
  cursor?: Prisma.LoanStatusHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoanStatusHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoanStatusHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoanStatusHistories.
   */
  distinct?: Prisma.LoanStatusHistoryScalarFieldEnum | Prisma.LoanStatusHistoryScalarFieldEnum[]
}

/**
 * LoanStatusHistory create
 */
export type LoanStatusHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanStatusHistory
   */
  select?: Prisma.LoanStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanStatusHistory
   */
  omit?: Prisma.LoanStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanStatusHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a LoanStatusHistory.
   */
  data: Prisma.XOR<Prisma.LoanStatusHistoryCreateInput, Prisma.LoanStatusHistoryUncheckedCreateInput>
}

/**
 * LoanStatusHistory createMany
 */
export type LoanStatusHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LoanStatusHistories.
   */
  data: Prisma.LoanStatusHistoryCreateManyInput | Prisma.LoanStatusHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LoanStatusHistory createManyAndReturn
 */
export type LoanStatusHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanStatusHistory
   */
  select?: Prisma.LoanStatusHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LoanStatusHistory
   */
  omit?: Prisma.LoanStatusHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many LoanStatusHistories.
   */
  data: Prisma.LoanStatusHistoryCreateManyInput | Prisma.LoanStatusHistoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanStatusHistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LoanStatusHistory update
 */
export type LoanStatusHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanStatusHistory
   */
  select?: Prisma.LoanStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanStatusHistory
   */
  omit?: Prisma.LoanStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanStatusHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a LoanStatusHistory.
   */
  data: Prisma.XOR<Prisma.LoanStatusHistoryUpdateInput, Prisma.LoanStatusHistoryUncheckedUpdateInput>
  /**
   * Choose, which LoanStatusHistory to update.
   */
  where: Prisma.LoanStatusHistoryWhereUniqueInput
}

/**
 * LoanStatusHistory updateMany
 */
export type LoanStatusHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LoanStatusHistories.
   */
  data: Prisma.XOR<Prisma.LoanStatusHistoryUpdateManyMutationInput, Prisma.LoanStatusHistoryUncheckedUpdateManyInput>
  /**
   * Filter which LoanStatusHistories to update
   */
  where?: Prisma.LoanStatusHistoryWhereInput
  /**
   * Limit how many LoanStatusHistories to update.
   */
  limit?: number
}

/**
 * LoanStatusHistory updateManyAndReturn
 */
export type LoanStatusHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanStatusHistory
   */
  select?: Prisma.LoanStatusHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LoanStatusHistory
   */
  omit?: Prisma.LoanStatusHistoryOmit<ExtArgs> | null
  /**
   * The data used to update LoanStatusHistories.
   */
  data: Prisma.XOR<Prisma.LoanStatusHistoryUpdateManyMutationInput, Prisma.LoanStatusHistoryUncheckedUpdateManyInput>
  /**
   * Filter which LoanStatusHistories to update
   */
  where?: Prisma.LoanStatusHistoryWhereInput
  /**
   * Limit how many LoanStatusHistories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanStatusHistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LoanStatusHistory upsert
 */
export type LoanStatusHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanStatusHistory
   */
  select?: Prisma.LoanStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanStatusHistory
   */
  omit?: Prisma.LoanStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanStatusHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the LoanStatusHistory to update in case it exists.
   */
  where: Prisma.LoanStatusHistoryWhereUniqueInput
  /**
   * In case the LoanStatusHistory found by the `where` argument doesn't exist, create a new LoanStatusHistory with this data.
   */
  create: Prisma.XOR<Prisma.LoanStatusHistoryCreateInput, Prisma.LoanStatusHistoryUncheckedCreateInput>
  /**
   * In case the LoanStatusHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LoanStatusHistoryUpdateInput, Prisma.LoanStatusHistoryUncheckedUpdateInput>
}

/**
 * LoanStatusHistory delete
 */
export type LoanStatusHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanStatusHistory
   */
  select?: Prisma.LoanStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanStatusHistory
   */
  omit?: Prisma.LoanStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanStatusHistoryInclude<ExtArgs> | null
  /**
   * Filter which LoanStatusHistory to delete.
   */
  where: Prisma.LoanStatusHistoryWhereUniqueInput
}

/**
 * LoanStatusHistory deleteMany
 */
export type LoanStatusHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LoanStatusHistories to delete
   */
  where?: Prisma.LoanStatusHistoryWhereInput
  /**
   * Limit how many LoanStatusHistories to delete.
   */
  limit?: number
}

/**
 * LoanStatusHistory without action
 */
export type LoanStatusHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanStatusHistory
   */
  select?: Prisma.LoanStatusHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanStatusHistory
   */
  omit?: Prisma.LoanStatusHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanStatusHistoryInclude<ExtArgs> | null
}
