
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LoanSchedule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LoanSchedule
 * 
 */
export type LoanScheduleModel = runtime.Types.Result.DefaultSelection<Prisma.$LoanSchedulePayload>

export type AggregateLoanSchedule = {
  _count: LoanScheduleCountAggregateOutputType | null
  _avg: LoanScheduleAvgAggregateOutputType | null
  _sum: LoanScheduleSumAggregateOutputType | null
  _min: LoanScheduleMinAggregateOutputType | null
  _max: LoanScheduleMaxAggregateOutputType | null
}

export type LoanScheduleAvgAggregateOutputType = {
  expectedAmount: runtime.Decimal | null
  principalAmount: runtime.Decimal | null
  interestAmount: runtime.Decimal | null
  paidAmount: runtime.Decimal | null
  remainingBalance: runtime.Decimal | null
}

export type LoanScheduleSumAggregateOutputType = {
  expectedAmount: runtime.Decimal | null
  principalAmount: runtime.Decimal | null
  interestAmount: runtime.Decimal | null
  paidAmount: runtime.Decimal | null
  remainingBalance: runtime.Decimal | null
}

export type LoanScheduleMinAggregateOutputType = {
  id: string | null
  loanId: string | null
  dueDate: Date | null
  expectedAmount: runtime.Decimal | null
  principalAmount: runtime.Decimal | null
  interestAmount: runtime.Decimal | null
  paidAmount: runtime.Decimal | null
  remainingBalance: runtime.Decimal | null
  status: $Enums.PaymentStatus | null
  actualPaymentDate: Date | null
}

export type LoanScheduleMaxAggregateOutputType = {
  id: string | null
  loanId: string | null
  dueDate: Date | null
  expectedAmount: runtime.Decimal | null
  principalAmount: runtime.Decimal | null
  interestAmount: runtime.Decimal | null
  paidAmount: runtime.Decimal | null
  remainingBalance: runtime.Decimal | null
  status: $Enums.PaymentStatus | null
  actualPaymentDate: Date | null
}

export type LoanScheduleCountAggregateOutputType = {
  id: number
  loanId: number
  dueDate: number
  expectedAmount: number
  principalAmount: number
  interestAmount: number
  paidAmount: number
  remainingBalance: number
  status: number
  actualPaymentDate: number
  _all: number
}


export type LoanScheduleAvgAggregateInputType = {
  expectedAmount?: true
  principalAmount?: true
  interestAmount?: true
  paidAmount?: true
  remainingBalance?: true
}

export type LoanScheduleSumAggregateInputType = {
  expectedAmount?: true
  principalAmount?: true
  interestAmount?: true
  paidAmount?: true
  remainingBalance?: true
}

export type LoanScheduleMinAggregateInputType = {
  id?: true
  loanId?: true
  dueDate?: true
  expectedAmount?: true
  principalAmount?: true
  interestAmount?: true
  paidAmount?: true
  remainingBalance?: true
  status?: true
  actualPaymentDate?: true
}

export type LoanScheduleMaxAggregateInputType = {
  id?: true
  loanId?: true
  dueDate?: true
  expectedAmount?: true
  principalAmount?: true
  interestAmount?: true
  paidAmount?: true
  remainingBalance?: true
  status?: true
  actualPaymentDate?: true
}

export type LoanScheduleCountAggregateInputType = {
  id?: true
  loanId?: true
  dueDate?: true
  expectedAmount?: true
  principalAmount?: true
  interestAmount?: true
  paidAmount?: true
  remainingBalance?: true
  status?: true
  actualPaymentDate?: true
  _all?: true
}

export type LoanScheduleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LoanSchedule to aggregate.
   */
  where?: Prisma.LoanScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoanSchedules to fetch.
   */
  orderBy?: Prisma.LoanScheduleOrderByWithRelationInput | Prisma.LoanScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LoanScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoanSchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoanSchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LoanSchedules
  **/
  _count?: true | LoanScheduleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LoanScheduleAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LoanScheduleSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LoanScheduleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LoanScheduleMaxAggregateInputType
}

export type GetLoanScheduleAggregateType<T extends LoanScheduleAggregateArgs> = {
      [P in keyof T & keyof AggregateLoanSchedule]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLoanSchedule[P]>
    : Prisma.GetScalarType<T[P], AggregateLoanSchedule[P]>
}




export type LoanScheduleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LoanScheduleWhereInput
  orderBy?: Prisma.LoanScheduleOrderByWithAggregationInput | Prisma.LoanScheduleOrderByWithAggregationInput[]
  by: Prisma.LoanScheduleScalarFieldEnum[] | Prisma.LoanScheduleScalarFieldEnum
  having?: Prisma.LoanScheduleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LoanScheduleCountAggregateInputType | true
  _avg?: LoanScheduleAvgAggregateInputType
  _sum?: LoanScheduleSumAggregateInputType
  _min?: LoanScheduleMinAggregateInputType
  _max?: LoanScheduleMaxAggregateInputType
}

export type LoanScheduleGroupByOutputType = {
  id: string
  loanId: string
  dueDate: Date
  expectedAmount: runtime.Decimal
  principalAmount: runtime.Decimal
  interestAmount: runtime.Decimal
  paidAmount: runtime.Decimal
  remainingBalance: runtime.Decimal
  status: $Enums.PaymentStatus
  actualPaymentDate: Date | null
  _count: LoanScheduleCountAggregateOutputType | null
  _avg: LoanScheduleAvgAggregateOutputType | null
  _sum: LoanScheduleSumAggregateOutputType | null
  _min: LoanScheduleMinAggregateOutputType | null
  _max: LoanScheduleMaxAggregateOutputType | null
}

export type GetLoanScheduleGroupByPayload<T extends LoanScheduleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LoanScheduleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LoanScheduleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LoanScheduleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LoanScheduleGroupByOutputType[P]>
      }
    >
  >



export type LoanScheduleWhereInput = {
  AND?: Prisma.LoanScheduleWhereInput | Prisma.LoanScheduleWhereInput[]
  OR?: Prisma.LoanScheduleWhereInput[]
  NOT?: Prisma.LoanScheduleWhereInput | Prisma.LoanScheduleWhereInput[]
  id?: Prisma.UuidFilter<"LoanSchedule"> | string
  loanId?: Prisma.UuidFilter<"LoanSchedule"> | string
  dueDate?: Prisma.DateTimeFilter<"LoanSchedule"> | Date | string
  expectedAmount?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusFilter<"LoanSchedule"> | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.DateTimeNullableFilter<"LoanSchedule"> | Date | string | null
  loan?: Prisma.XOR<Prisma.LoanScalarRelationFilter, Prisma.LoanWhereInput>
  repayments?: Prisma.LoanRepaymentListRelationFilter
}

export type LoanScheduleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  expectedAmount?: Prisma.SortOrder
  principalAmount?: Prisma.SortOrder
  interestAmount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  remainingBalance?: Prisma.SortOrder
  status?: Prisma.SortOrder
  actualPaymentDate?: Prisma.SortOrderInput | Prisma.SortOrder
  loan?: Prisma.LoanOrderByWithRelationInput
  repayments?: Prisma.LoanRepaymentOrderByRelationAggregateInput
}

export type LoanScheduleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LoanScheduleWhereInput | Prisma.LoanScheduleWhereInput[]
  OR?: Prisma.LoanScheduleWhereInput[]
  NOT?: Prisma.LoanScheduleWhereInput | Prisma.LoanScheduleWhereInput[]
  loanId?: Prisma.UuidFilter<"LoanSchedule"> | string
  dueDate?: Prisma.DateTimeFilter<"LoanSchedule"> | Date | string
  expectedAmount?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusFilter<"LoanSchedule"> | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.DateTimeNullableFilter<"LoanSchedule"> | Date | string | null
  loan?: Prisma.XOR<Prisma.LoanScalarRelationFilter, Prisma.LoanWhereInput>
  repayments?: Prisma.LoanRepaymentListRelationFilter
}, "id">

export type LoanScheduleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  expectedAmount?: Prisma.SortOrder
  principalAmount?: Prisma.SortOrder
  interestAmount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  remainingBalance?: Prisma.SortOrder
  status?: Prisma.SortOrder
  actualPaymentDate?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.LoanScheduleCountOrderByAggregateInput
  _avg?: Prisma.LoanScheduleAvgOrderByAggregateInput
  _max?: Prisma.LoanScheduleMaxOrderByAggregateInput
  _min?: Prisma.LoanScheduleMinOrderByAggregateInput
  _sum?: Prisma.LoanScheduleSumOrderByAggregateInput
}

export type LoanScheduleScalarWhereWithAggregatesInput = {
  AND?: Prisma.LoanScheduleScalarWhereWithAggregatesInput | Prisma.LoanScheduleScalarWhereWithAggregatesInput[]
  OR?: Prisma.LoanScheduleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LoanScheduleScalarWhereWithAggregatesInput | Prisma.LoanScheduleScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"LoanSchedule"> | string
  loanId?: Prisma.UuidWithAggregatesFilter<"LoanSchedule"> | string
  dueDate?: Prisma.DateTimeWithAggregatesFilter<"LoanSchedule"> | Date | string
  expectedAmount?: Prisma.DecimalWithAggregatesFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalWithAggregatesFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalWithAggregatesFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalWithAggregatesFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalWithAggregatesFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusWithAggregatesFilter<"LoanSchedule"> | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.DateTimeNullableWithAggregatesFilter<"LoanSchedule"> | Date | string | null
}

export type LoanScheduleCreateInput = {
  id?: string
  dueDate: Date | string
  expectedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: $Enums.PaymentStatus
  actualPaymentDate?: Date | string | null
  loan: Prisma.LoanCreateNestedOneWithoutPaymentSchedulesInput
  repayments?: Prisma.LoanRepaymentCreateNestedManyWithoutScheduleInput
}

export type LoanScheduleUncheckedCreateInput = {
  id?: string
  loanId: string
  dueDate: Date | string
  expectedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: $Enums.PaymentStatus
  actualPaymentDate?: Date | string | null
  repayments?: Prisma.LoanRepaymentUncheckedCreateNestedManyWithoutScheduleInput
}

export type LoanScheduleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expectedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  loan?: Prisma.LoanUpdateOneRequiredWithoutPaymentSchedulesNestedInput
  repayments?: Prisma.LoanRepaymentUpdateManyWithoutScheduleNestedInput
}

export type LoanScheduleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.StringFieldUpdateOperationsInput | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expectedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  repayments?: Prisma.LoanRepaymentUncheckedUpdateManyWithoutScheduleNestedInput
}

export type LoanScheduleCreateManyInput = {
  id?: string
  loanId: string
  dueDate: Date | string
  expectedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: $Enums.PaymentStatus
  actualPaymentDate?: Date | string | null
}

export type LoanScheduleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expectedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LoanScheduleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.StringFieldUpdateOperationsInput | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expectedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LoanScheduleListRelationFilter = {
  every?: Prisma.LoanScheduleWhereInput
  some?: Prisma.LoanScheduleWhereInput
  none?: Prisma.LoanScheduleWhereInput
}

export type LoanScheduleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LoanScheduleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  expectedAmount?: Prisma.SortOrder
  principalAmount?: Prisma.SortOrder
  interestAmount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  remainingBalance?: Prisma.SortOrder
  status?: Prisma.SortOrder
  actualPaymentDate?: Prisma.SortOrder
}

export type LoanScheduleAvgOrderByAggregateInput = {
  expectedAmount?: Prisma.SortOrder
  principalAmount?: Prisma.SortOrder
  interestAmount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  remainingBalance?: Prisma.SortOrder
}

export type LoanScheduleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  expectedAmount?: Prisma.SortOrder
  principalAmount?: Prisma.SortOrder
  interestAmount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  remainingBalance?: Prisma.SortOrder
  status?: Prisma.SortOrder
  actualPaymentDate?: Prisma.SortOrder
}

export type LoanScheduleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  loanId?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  expectedAmount?: Prisma.SortOrder
  principalAmount?: Prisma.SortOrder
  interestAmount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  remainingBalance?: Prisma.SortOrder
  status?: Prisma.SortOrder
  actualPaymentDate?: Prisma.SortOrder
}

export type LoanScheduleSumOrderByAggregateInput = {
  expectedAmount?: Prisma.SortOrder
  principalAmount?: Prisma.SortOrder
  interestAmount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  remainingBalance?: Prisma.SortOrder
}

export type LoanScheduleNullableScalarRelationFilter = {
  is?: Prisma.LoanScheduleWhereInput | null
  isNot?: Prisma.LoanScheduleWhereInput | null
}

export type LoanScheduleCreateNestedManyWithoutLoanInput = {
  create?: Prisma.XOR<Prisma.LoanScheduleCreateWithoutLoanInput, Prisma.LoanScheduleUncheckedCreateWithoutLoanInput> | Prisma.LoanScheduleCreateWithoutLoanInput[] | Prisma.LoanScheduleUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.LoanScheduleCreateOrConnectWithoutLoanInput | Prisma.LoanScheduleCreateOrConnectWithoutLoanInput[]
  createMany?: Prisma.LoanScheduleCreateManyLoanInputEnvelope
  connect?: Prisma.LoanScheduleWhereUniqueInput | Prisma.LoanScheduleWhereUniqueInput[]
}

export type LoanScheduleUncheckedCreateNestedManyWithoutLoanInput = {
  create?: Prisma.XOR<Prisma.LoanScheduleCreateWithoutLoanInput, Prisma.LoanScheduleUncheckedCreateWithoutLoanInput> | Prisma.LoanScheduleCreateWithoutLoanInput[] | Prisma.LoanScheduleUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.LoanScheduleCreateOrConnectWithoutLoanInput | Prisma.LoanScheduleCreateOrConnectWithoutLoanInput[]
  createMany?: Prisma.LoanScheduleCreateManyLoanInputEnvelope
  connect?: Prisma.LoanScheduleWhereUniqueInput | Prisma.LoanScheduleWhereUniqueInput[]
}

export type LoanScheduleUpdateManyWithoutLoanNestedInput = {
  create?: Prisma.XOR<Prisma.LoanScheduleCreateWithoutLoanInput, Prisma.LoanScheduleUncheckedCreateWithoutLoanInput> | Prisma.LoanScheduleCreateWithoutLoanInput[] | Prisma.LoanScheduleUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.LoanScheduleCreateOrConnectWithoutLoanInput | Prisma.LoanScheduleCreateOrConnectWithoutLoanInput[]
  upsert?: Prisma.LoanScheduleUpsertWithWhereUniqueWithoutLoanInput | Prisma.LoanScheduleUpsertWithWhereUniqueWithoutLoanInput[]
  createMany?: Prisma.LoanScheduleCreateManyLoanInputEnvelope
  set?: Prisma.LoanScheduleWhereUniqueInput | Prisma.LoanScheduleWhereUniqueInput[]
  disconnect?: Prisma.LoanScheduleWhereUniqueInput | Prisma.LoanScheduleWhereUniqueInput[]
  delete?: Prisma.LoanScheduleWhereUniqueInput | Prisma.LoanScheduleWhereUniqueInput[]
  connect?: Prisma.LoanScheduleWhereUniqueInput | Prisma.LoanScheduleWhereUniqueInput[]
  update?: Prisma.LoanScheduleUpdateWithWhereUniqueWithoutLoanInput | Prisma.LoanScheduleUpdateWithWhereUniqueWithoutLoanInput[]
  updateMany?: Prisma.LoanScheduleUpdateManyWithWhereWithoutLoanInput | Prisma.LoanScheduleUpdateManyWithWhereWithoutLoanInput[]
  deleteMany?: Prisma.LoanScheduleScalarWhereInput | Prisma.LoanScheduleScalarWhereInput[]
}

export type LoanScheduleUncheckedUpdateManyWithoutLoanNestedInput = {
  create?: Prisma.XOR<Prisma.LoanScheduleCreateWithoutLoanInput, Prisma.LoanScheduleUncheckedCreateWithoutLoanInput> | Prisma.LoanScheduleCreateWithoutLoanInput[] | Prisma.LoanScheduleUncheckedCreateWithoutLoanInput[]
  connectOrCreate?: Prisma.LoanScheduleCreateOrConnectWithoutLoanInput | Prisma.LoanScheduleCreateOrConnectWithoutLoanInput[]
  upsert?: Prisma.LoanScheduleUpsertWithWhereUniqueWithoutLoanInput | Prisma.LoanScheduleUpsertWithWhereUniqueWithoutLoanInput[]
  createMany?: Prisma.LoanScheduleCreateManyLoanInputEnvelope
  set?: Prisma.LoanScheduleWhereUniqueInput | Prisma.LoanScheduleWhereUniqueInput[]
  disconnect?: Prisma.LoanScheduleWhereUniqueInput | Prisma.LoanScheduleWhereUniqueInput[]
  delete?: Prisma.LoanScheduleWhereUniqueInput | Prisma.LoanScheduleWhereUniqueInput[]
  connect?: Prisma.LoanScheduleWhereUniqueInput | Prisma.LoanScheduleWhereUniqueInput[]
  update?: Prisma.LoanScheduleUpdateWithWhereUniqueWithoutLoanInput | Prisma.LoanScheduleUpdateWithWhereUniqueWithoutLoanInput[]
  updateMany?: Prisma.LoanScheduleUpdateManyWithWhereWithoutLoanInput | Prisma.LoanScheduleUpdateManyWithWhereWithoutLoanInput[]
  deleteMany?: Prisma.LoanScheduleScalarWhereInput | Prisma.LoanScheduleScalarWhereInput[]
}

export type EnumPaymentStatusFieldUpdateOperationsInput = {
  set?: $Enums.PaymentStatus
}

export type LoanScheduleCreateNestedOneWithoutRepaymentsInput = {
  create?: Prisma.XOR<Prisma.LoanScheduleCreateWithoutRepaymentsInput, Prisma.LoanScheduleUncheckedCreateWithoutRepaymentsInput>
  connectOrCreate?: Prisma.LoanScheduleCreateOrConnectWithoutRepaymentsInput
  connect?: Prisma.LoanScheduleWhereUniqueInput
}

export type LoanScheduleUpdateOneWithoutRepaymentsNestedInput = {
  create?: Prisma.XOR<Prisma.LoanScheduleCreateWithoutRepaymentsInput, Prisma.LoanScheduleUncheckedCreateWithoutRepaymentsInput>
  connectOrCreate?: Prisma.LoanScheduleCreateOrConnectWithoutRepaymentsInput
  upsert?: Prisma.LoanScheduleUpsertWithoutRepaymentsInput
  disconnect?: Prisma.LoanScheduleWhereInput | boolean
  delete?: Prisma.LoanScheduleWhereInput | boolean
  connect?: Prisma.LoanScheduleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LoanScheduleUpdateToOneWithWhereWithoutRepaymentsInput, Prisma.LoanScheduleUpdateWithoutRepaymentsInput>, Prisma.LoanScheduleUncheckedUpdateWithoutRepaymentsInput>
}

export type LoanScheduleCreateWithoutLoanInput = {
  id?: string
  dueDate: Date | string
  expectedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: $Enums.PaymentStatus
  actualPaymentDate?: Date | string | null
  repayments?: Prisma.LoanRepaymentCreateNestedManyWithoutScheduleInput
}

export type LoanScheduleUncheckedCreateWithoutLoanInput = {
  id?: string
  dueDate: Date | string
  expectedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: $Enums.PaymentStatus
  actualPaymentDate?: Date | string | null
  repayments?: Prisma.LoanRepaymentUncheckedCreateNestedManyWithoutScheduleInput
}

export type LoanScheduleCreateOrConnectWithoutLoanInput = {
  where: Prisma.LoanScheduleWhereUniqueInput
  create: Prisma.XOR<Prisma.LoanScheduleCreateWithoutLoanInput, Prisma.LoanScheduleUncheckedCreateWithoutLoanInput>
}

export type LoanScheduleCreateManyLoanInputEnvelope = {
  data: Prisma.LoanScheduleCreateManyLoanInput | Prisma.LoanScheduleCreateManyLoanInput[]
  skipDuplicates?: boolean
}

export type LoanScheduleUpsertWithWhereUniqueWithoutLoanInput = {
  where: Prisma.LoanScheduleWhereUniqueInput
  update: Prisma.XOR<Prisma.LoanScheduleUpdateWithoutLoanInput, Prisma.LoanScheduleUncheckedUpdateWithoutLoanInput>
  create: Prisma.XOR<Prisma.LoanScheduleCreateWithoutLoanInput, Prisma.LoanScheduleUncheckedCreateWithoutLoanInput>
}

export type LoanScheduleUpdateWithWhereUniqueWithoutLoanInput = {
  where: Prisma.LoanScheduleWhereUniqueInput
  data: Prisma.XOR<Prisma.LoanScheduleUpdateWithoutLoanInput, Prisma.LoanScheduleUncheckedUpdateWithoutLoanInput>
}

export type LoanScheduleUpdateManyWithWhereWithoutLoanInput = {
  where: Prisma.LoanScheduleScalarWhereInput
  data: Prisma.XOR<Prisma.LoanScheduleUpdateManyMutationInput, Prisma.LoanScheduleUncheckedUpdateManyWithoutLoanInput>
}

export type LoanScheduleScalarWhereInput = {
  AND?: Prisma.LoanScheduleScalarWhereInput | Prisma.LoanScheduleScalarWhereInput[]
  OR?: Prisma.LoanScheduleScalarWhereInput[]
  NOT?: Prisma.LoanScheduleScalarWhereInput | Prisma.LoanScheduleScalarWhereInput[]
  id?: Prisma.UuidFilter<"LoanSchedule"> | string
  loanId?: Prisma.UuidFilter<"LoanSchedule"> | string
  dueDate?: Prisma.DateTimeFilter<"LoanSchedule"> | Date | string
  expectedAmount?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalFilter<"LoanSchedule"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusFilter<"LoanSchedule"> | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.DateTimeNullableFilter<"LoanSchedule"> | Date | string | null
}

export type LoanScheduleCreateWithoutRepaymentsInput = {
  id?: string
  dueDate: Date | string
  expectedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: $Enums.PaymentStatus
  actualPaymentDate?: Date | string | null
  loan: Prisma.LoanCreateNestedOneWithoutPaymentSchedulesInput
}

export type LoanScheduleUncheckedCreateWithoutRepaymentsInput = {
  id?: string
  loanId: string
  dueDate: Date | string
  expectedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: $Enums.PaymentStatus
  actualPaymentDate?: Date | string | null
}

export type LoanScheduleCreateOrConnectWithoutRepaymentsInput = {
  where: Prisma.LoanScheduleWhereUniqueInput
  create: Prisma.XOR<Prisma.LoanScheduleCreateWithoutRepaymentsInput, Prisma.LoanScheduleUncheckedCreateWithoutRepaymentsInput>
}

export type LoanScheduleUpsertWithoutRepaymentsInput = {
  update: Prisma.XOR<Prisma.LoanScheduleUpdateWithoutRepaymentsInput, Prisma.LoanScheduleUncheckedUpdateWithoutRepaymentsInput>
  create: Prisma.XOR<Prisma.LoanScheduleCreateWithoutRepaymentsInput, Prisma.LoanScheduleUncheckedCreateWithoutRepaymentsInput>
  where?: Prisma.LoanScheduleWhereInput
}

export type LoanScheduleUpdateToOneWithWhereWithoutRepaymentsInput = {
  where?: Prisma.LoanScheduleWhereInput
  data: Prisma.XOR<Prisma.LoanScheduleUpdateWithoutRepaymentsInput, Prisma.LoanScheduleUncheckedUpdateWithoutRepaymentsInput>
}

export type LoanScheduleUpdateWithoutRepaymentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expectedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  loan?: Prisma.LoanUpdateOneRequiredWithoutPaymentSchedulesNestedInput
}

export type LoanScheduleUncheckedUpdateWithoutRepaymentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loanId?: Prisma.StringFieldUpdateOperationsInput | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expectedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LoanScheduleCreateManyLoanInput = {
  id?: string
  dueDate: Date | string
  expectedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance: runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: $Enums.PaymentStatus
  actualPaymentDate?: Date | string | null
}

export type LoanScheduleUpdateWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expectedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  repayments?: Prisma.LoanRepaymentUpdateManyWithoutScheduleNestedInput
}

export type LoanScheduleUncheckedUpdateWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expectedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  repayments?: Prisma.LoanRepaymentUncheckedUpdateManyWithoutScheduleNestedInput
}

export type LoanScheduleUncheckedUpdateManyWithoutLoanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expectedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  principalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  interestAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  remainingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  actualPaymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type LoanScheduleCountOutputType
 */

export type LoanScheduleCountOutputType = {
  repayments: number
}

export type LoanScheduleCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  repayments?: boolean | LoanScheduleCountOutputTypeCountRepaymentsArgs
}

/**
 * LoanScheduleCountOutputType without action
 */
export type LoanScheduleCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanScheduleCountOutputType
   */
  select?: Prisma.LoanScheduleCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LoanScheduleCountOutputType without action
 */
export type LoanScheduleCountOutputTypeCountRepaymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LoanRepaymentWhereInput
}


export type LoanScheduleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  loanId?: boolean
  dueDate?: boolean
  expectedAmount?: boolean
  principalAmount?: boolean
  interestAmount?: boolean
  paidAmount?: boolean
  remainingBalance?: boolean
  status?: boolean
  actualPaymentDate?: boolean
  loan?: boolean | Prisma.LoanDefaultArgs<ExtArgs>
  repayments?: boolean | Prisma.LoanSchedule$repaymentsArgs<ExtArgs>
  _count?: boolean | Prisma.LoanScheduleCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["loanSchedule"]>

export type LoanScheduleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  loanId?: boolean
  dueDate?: boolean
  expectedAmount?: boolean
  principalAmount?: boolean
  interestAmount?: boolean
  paidAmount?: boolean
  remainingBalance?: boolean
  status?: boolean
  actualPaymentDate?: boolean
  loan?: boolean | Prisma.LoanDefaultArgs<ExtArgs>
}, ExtArgs["result"]["loanSchedule"]>

export type LoanScheduleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  loanId?: boolean
  dueDate?: boolean
  expectedAmount?: boolean
  principalAmount?: boolean
  interestAmount?: boolean
  paidAmount?: boolean
  remainingBalance?: boolean
  status?: boolean
  actualPaymentDate?: boolean
  loan?: boolean | Prisma.LoanDefaultArgs<ExtArgs>
}, ExtArgs["result"]["loanSchedule"]>

export type LoanScheduleSelectScalar = {
  id?: boolean
  loanId?: boolean
  dueDate?: boolean
  expectedAmount?: boolean
  principalAmount?: boolean
  interestAmount?: boolean
  paidAmount?: boolean
  remainingBalance?: boolean
  status?: boolean
  actualPaymentDate?: boolean
}

export type LoanScheduleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "loanId" | "dueDate" | "expectedAmount" | "principalAmount" | "interestAmount" | "paidAmount" | "remainingBalance" | "status" | "actualPaymentDate", ExtArgs["result"]["loanSchedule"]>
export type LoanScheduleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  loan?: boolean | Prisma.LoanDefaultArgs<ExtArgs>
  repayments?: boolean | Prisma.LoanSchedule$repaymentsArgs<ExtArgs>
  _count?: boolean | Prisma.LoanScheduleCountOutputTypeDefaultArgs<ExtArgs>
}
export type LoanScheduleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  loan?: boolean | Prisma.LoanDefaultArgs<ExtArgs>
}
export type LoanScheduleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  loan?: boolean | Prisma.LoanDefaultArgs<ExtArgs>
}

export type $LoanSchedulePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LoanSchedule"
  objects: {
    loan: Prisma.$LoanPayload<ExtArgs>
    repayments: Prisma.$LoanRepaymentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    loanId: string
    dueDate: Date
    expectedAmount: runtime.Decimal
    principalAmount: runtime.Decimal
    interestAmount: runtime.Decimal
    paidAmount: runtime.Decimal
    remainingBalance: runtime.Decimal
    status: $Enums.PaymentStatus
    actualPaymentDate: Date | null
  }, ExtArgs["result"]["loanSchedule"]>
  composites: {}
}

export type LoanScheduleGetPayload<S extends boolean | null | undefined | LoanScheduleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LoanSchedulePayload, S>

export type LoanScheduleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LoanScheduleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LoanScheduleCountAggregateInputType | true
  }

export interface LoanScheduleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LoanSchedule'], meta: { name: 'LoanSchedule' } }
  /**
   * Find zero or one LoanSchedule that matches the filter.
   * @param {LoanScheduleFindUniqueArgs} args - Arguments to find a LoanSchedule
   * @example
   * // Get one LoanSchedule
   * const loanSchedule = await prisma.loanSchedule.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LoanScheduleFindUniqueArgs>(args: Prisma.SelectSubset<T, LoanScheduleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LoanScheduleClient<runtime.Types.Result.GetResult<Prisma.$LoanSchedulePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LoanSchedule that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LoanScheduleFindUniqueOrThrowArgs} args - Arguments to find a LoanSchedule
   * @example
   * // Get one LoanSchedule
   * const loanSchedule = await prisma.loanSchedule.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LoanScheduleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LoanScheduleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LoanScheduleClient<runtime.Types.Result.GetResult<Prisma.$LoanSchedulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LoanSchedule that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanScheduleFindFirstArgs} args - Arguments to find a LoanSchedule
   * @example
   * // Get one LoanSchedule
   * const loanSchedule = await prisma.loanSchedule.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LoanScheduleFindFirstArgs>(args?: Prisma.SelectSubset<T, LoanScheduleFindFirstArgs<ExtArgs>>): Prisma.Prisma__LoanScheduleClient<runtime.Types.Result.GetResult<Prisma.$LoanSchedulePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LoanSchedule that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanScheduleFindFirstOrThrowArgs} args - Arguments to find a LoanSchedule
   * @example
   * // Get one LoanSchedule
   * const loanSchedule = await prisma.loanSchedule.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LoanScheduleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LoanScheduleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LoanScheduleClient<runtime.Types.Result.GetResult<Prisma.$LoanSchedulePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LoanSchedules that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanScheduleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LoanSchedules
   * const loanSchedules = await prisma.loanSchedule.findMany()
   * 
   * // Get first 10 LoanSchedules
   * const loanSchedules = await prisma.loanSchedule.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const loanScheduleWithIdOnly = await prisma.loanSchedule.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LoanScheduleFindManyArgs>(args?: Prisma.SelectSubset<T, LoanScheduleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoanSchedulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LoanSchedule.
   * @param {LoanScheduleCreateArgs} args - Arguments to create a LoanSchedule.
   * @example
   * // Create one LoanSchedule
   * const LoanSchedule = await prisma.loanSchedule.create({
   *   data: {
   *     // ... data to create a LoanSchedule
   *   }
   * })
   * 
   */
  create<T extends LoanScheduleCreateArgs>(args: Prisma.SelectSubset<T, LoanScheduleCreateArgs<ExtArgs>>): Prisma.Prisma__LoanScheduleClient<runtime.Types.Result.GetResult<Prisma.$LoanSchedulePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LoanSchedules.
   * @param {LoanScheduleCreateManyArgs} args - Arguments to create many LoanSchedules.
   * @example
   * // Create many LoanSchedules
   * const loanSchedule = await prisma.loanSchedule.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LoanScheduleCreateManyArgs>(args?: Prisma.SelectSubset<T, LoanScheduleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LoanSchedules and returns the data saved in the database.
   * @param {LoanScheduleCreateManyAndReturnArgs} args - Arguments to create many LoanSchedules.
   * @example
   * // Create many LoanSchedules
   * const loanSchedule = await prisma.loanSchedule.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LoanSchedules and only return the `id`
   * const loanScheduleWithIdOnly = await prisma.loanSchedule.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LoanScheduleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LoanScheduleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoanSchedulePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LoanSchedule.
   * @param {LoanScheduleDeleteArgs} args - Arguments to delete one LoanSchedule.
   * @example
   * // Delete one LoanSchedule
   * const LoanSchedule = await prisma.loanSchedule.delete({
   *   where: {
   *     // ... filter to delete one LoanSchedule
   *   }
   * })
   * 
   */
  delete<T extends LoanScheduleDeleteArgs>(args: Prisma.SelectSubset<T, LoanScheduleDeleteArgs<ExtArgs>>): Prisma.Prisma__LoanScheduleClient<runtime.Types.Result.GetResult<Prisma.$LoanSchedulePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LoanSchedule.
   * @param {LoanScheduleUpdateArgs} args - Arguments to update one LoanSchedule.
   * @example
   * // Update one LoanSchedule
   * const loanSchedule = await prisma.loanSchedule.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LoanScheduleUpdateArgs>(args: Prisma.SelectSubset<T, LoanScheduleUpdateArgs<ExtArgs>>): Prisma.Prisma__LoanScheduleClient<runtime.Types.Result.GetResult<Prisma.$LoanSchedulePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LoanSchedules.
   * @param {LoanScheduleDeleteManyArgs} args - Arguments to filter LoanSchedules to delete.
   * @example
   * // Delete a few LoanSchedules
   * const { count } = await prisma.loanSchedule.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LoanScheduleDeleteManyArgs>(args?: Prisma.SelectSubset<T, LoanScheduleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LoanSchedules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanScheduleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LoanSchedules
   * const loanSchedule = await prisma.loanSchedule.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LoanScheduleUpdateManyArgs>(args: Prisma.SelectSubset<T, LoanScheduleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LoanSchedules and returns the data updated in the database.
   * @param {LoanScheduleUpdateManyAndReturnArgs} args - Arguments to update many LoanSchedules.
   * @example
   * // Update many LoanSchedules
   * const loanSchedule = await prisma.loanSchedule.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LoanSchedules and only return the `id`
   * const loanScheduleWithIdOnly = await prisma.loanSchedule.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LoanScheduleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LoanScheduleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoanSchedulePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LoanSchedule.
   * @param {LoanScheduleUpsertArgs} args - Arguments to update or create a LoanSchedule.
   * @example
   * // Update or create a LoanSchedule
   * const loanSchedule = await prisma.loanSchedule.upsert({
   *   create: {
   *     // ... data to create a LoanSchedule
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LoanSchedule we want to update
   *   }
   * })
   */
  upsert<T extends LoanScheduleUpsertArgs>(args: Prisma.SelectSubset<T, LoanScheduleUpsertArgs<ExtArgs>>): Prisma.Prisma__LoanScheduleClient<runtime.Types.Result.GetResult<Prisma.$LoanSchedulePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LoanSchedules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanScheduleCountArgs} args - Arguments to filter LoanSchedules to count.
   * @example
   * // Count the number of LoanSchedules
   * const count = await prisma.loanSchedule.count({
   *   where: {
   *     // ... the filter for the LoanSchedules we want to count
   *   }
   * })
  **/
  count<T extends LoanScheduleCountArgs>(
    args?: Prisma.Subset<T, LoanScheduleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LoanScheduleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LoanSchedule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanScheduleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LoanScheduleAggregateArgs>(args: Prisma.Subset<T, LoanScheduleAggregateArgs>): Prisma.PrismaPromise<GetLoanScheduleAggregateType<T>>

  /**
   * Group by LoanSchedule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanScheduleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LoanScheduleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LoanScheduleGroupByArgs['orderBy'] }
      : { orderBy?: LoanScheduleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LoanScheduleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLoanScheduleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LoanSchedule model
 */
readonly fields: LoanScheduleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LoanSchedule.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LoanScheduleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  loan<T extends Prisma.LoanDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LoanDefaultArgs<ExtArgs>>): Prisma.Prisma__LoanClient<runtime.Types.Result.GetResult<Prisma.$LoanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  repayments<T extends Prisma.LoanSchedule$repaymentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LoanSchedule$repaymentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoanRepaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LoanSchedule model
 */
export interface LoanScheduleFieldRefs {
  readonly id: Prisma.FieldRef<"LoanSchedule", 'String'>
  readonly loanId: Prisma.FieldRef<"LoanSchedule", 'String'>
  readonly dueDate: Prisma.FieldRef<"LoanSchedule", 'DateTime'>
  readonly expectedAmount: Prisma.FieldRef<"LoanSchedule", 'Decimal'>
  readonly principalAmount: Prisma.FieldRef<"LoanSchedule", 'Decimal'>
  readonly interestAmount: Prisma.FieldRef<"LoanSchedule", 'Decimal'>
  readonly paidAmount: Prisma.FieldRef<"LoanSchedule", 'Decimal'>
  readonly remainingBalance: Prisma.FieldRef<"LoanSchedule", 'Decimal'>
  readonly status: Prisma.FieldRef<"LoanSchedule", 'PaymentStatus'>
  readonly actualPaymentDate: Prisma.FieldRef<"LoanSchedule", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LoanSchedule findUnique
 */
export type LoanScheduleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanSchedule
   */
  select?: Prisma.LoanScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanSchedule
   */
  omit?: Prisma.LoanScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanScheduleInclude<ExtArgs> | null
  /**
   * Filter, which LoanSchedule to fetch.
   */
  where: Prisma.LoanScheduleWhereUniqueInput
}

/**
 * LoanSchedule findUniqueOrThrow
 */
export type LoanScheduleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanSchedule
   */
  select?: Prisma.LoanScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanSchedule
   */
  omit?: Prisma.LoanScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanScheduleInclude<ExtArgs> | null
  /**
   * Filter, which LoanSchedule to fetch.
   */
  where: Prisma.LoanScheduleWhereUniqueInput
}

/**
 * LoanSchedule findFirst
 */
export type LoanScheduleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanSchedule
   */
  select?: Prisma.LoanScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanSchedule
   */
  omit?: Prisma.LoanScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanScheduleInclude<ExtArgs> | null
  /**
   * Filter, which LoanSchedule to fetch.
   */
  where?: Prisma.LoanScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoanSchedules to fetch.
   */
  orderBy?: Prisma.LoanScheduleOrderByWithRelationInput | Prisma.LoanScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LoanSchedules.
   */
  cursor?: Prisma.LoanScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoanSchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoanSchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoanSchedules.
   */
  distinct?: Prisma.LoanScheduleScalarFieldEnum | Prisma.LoanScheduleScalarFieldEnum[]
}

/**
 * LoanSchedule findFirstOrThrow
 */
export type LoanScheduleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanSchedule
   */
  select?: Prisma.LoanScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanSchedule
   */
  omit?: Prisma.LoanScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanScheduleInclude<ExtArgs> | null
  /**
   * Filter, which LoanSchedule to fetch.
   */
  where?: Prisma.LoanScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoanSchedules to fetch.
   */
  orderBy?: Prisma.LoanScheduleOrderByWithRelationInput | Prisma.LoanScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LoanSchedules.
   */
  cursor?: Prisma.LoanScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoanSchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoanSchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoanSchedules.
   */
  distinct?: Prisma.LoanScheduleScalarFieldEnum | Prisma.LoanScheduleScalarFieldEnum[]
}

/**
 * LoanSchedule findMany
 */
export type LoanScheduleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanSchedule
   */
  select?: Prisma.LoanScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanSchedule
   */
  omit?: Prisma.LoanScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanScheduleInclude<ExtArgs> | null
  /**
   * Filter, which LoanSchedules to fetch.
   */
  where?: Prisma.LoanScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoanSchedules to fetch.
   */
  orderBy?: Prisma.LoanScheduleOrderByWithRelationInput | Prisma.LoanScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LoanSchedules.
   */
  cursor?: Prisma.LoanScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoanSchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoanSchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoanSchedules.
   */
  distinct?: Prisma.LoanScheduleScalarFieldEnum | Prisma.LoanScheduleScalarFieldEnum[]
}

/**
 * LoanSchedule create
 */
export type LoanScheduleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanSchedule
   */
  select?: Prisma.LoanScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanSchedule
   */
  omit?: Prisma.LoanScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanScheduleInclude<ExtArgs> | null
  /**
   * The data needed to create a LoanSchedule.
   */
  data: Prisma.XOR<Prisma.LoanScheduleCreateInput, Prisma.LoanScheduleUncheckedCreateInput>
}

/**
 * LoanSchedule createMany
 */
export type LoanScheduleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LoanSchedules.
   */
  data: Prisma.LoanScheduleCreateManyInput | Prisma.LoanScheduleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LoanSchedule createManyAndReturn
 */
export type LoanScheduleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanSchedule
   */
  select?: Prisma.LoanScheduleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LoanSchedule
   */
  omit?: Prisma.LoanScheduleOmit<ExtArgs> | null
  /**
   * The data used to create many LoanSchedules.
   */
  data: Prisma.LoanScheduleCreateManyInput | Prisma.LoanScheduleCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanScheduleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LoanSchedule update
 */
export type LoanScheduleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanSchedule
   */
  select?: Prisma.LoanScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanSchedule
   */
  omit?: Prisma.LoanScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanScheduleInclude<ExtArgs> | null
  /**
   * The data needed to update a LoanSchedule.
   */
  data: Prisma.XOR<Prisma.LoanScheduleUpdateInput, Prisma.LoanScheduleUncheckedUpdateInput>
  /**
   * Choose, which LoanSchedule to update.
   */
  where: Prisma.LoanScheduleWhereUniqueInput
}

/**
 * LoanSchedule updateMany
 */
export type LoanScheduleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LoanSchedules.
   */
  data: Prisma.XOR<Prisma.LoanScheduleUpdateManyMutationInput, Prisma.LoanScheduleUncheckedUpdateManyInput>
  /**
   * Filter which LoanSchedules to update
   */
  where?: Prisma.LoanScheduleWhereInput
  /**
   * Limit how many LoanSchedules to update.
   */
  limit?: number
}

/**
 * LoanSchedule updateManyAndReturn
 */
export type LoanScheduleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanSchedule
   */
  select?: Prisma.LoanScheduleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LoanSchedule
   */
  omit?: Prisma.LoanScheduleOmit<ExtArgs> | null
  /**
   * The data used to update LoanSchedules.
   */
  data: Prisma.XOR<Prisma.LoanScheduleUpdateManyMutationInput, Prisma.LoanScheduleUncheckedUpdateManyInput>
  /**
   * Filter which LoanSchedules to update
   */
  where?: Prisma.LoanScheduleWhereInput
  /**
   * Limit how many LoanSchedules to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanScheduleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LoanSchedule upsert
 */
export type LoanScheduleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanSchedule
   */
  select?: Prisma.LoanScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanSchedule
   */
  omit?: Prisma.LoanScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanScheduleInclude<ExtArgs> | null
  /**
   * The filter to search for the LoanSchedule to update in case it exists.
   */
  where: Prisma.LoanScheduleWhereUniqueInput
  /**
   * In case the LoanSchedule found by the `where` argument doesn't exist, create a new LoanSchedule with this data.
   */
  create: Prisma.XOR<Prisma.LoanScheduleCreateInput, Prisma.LoanScheduleUncheckedCreateInput>
  /**
   * In case the LoanSchedule was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LoanScheduleUpdateInput, Prisma.LoanScheduleUncheckedUpdateInput>
}

/**
 * LoanSchedule delete
 */
export type LoanScheduleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanSchedule
   */
  select?: Prisma.LoanScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanSchedule
   */
  omit?: Prisma.LoanScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanScheduleInclude<ExtArgs> | null
  /**
   * Filter which LoanSchedule to delete.
   */
  where: Prisma.LoanScheduleWhereUniqueInput
}

/**
 * LoanSchedule deleteMany
 */
export type LoanScheduleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LoanSchedules to delete
   */
  where?: Prisma.LoanScheduleWhereInput
  /**
   * Limit how many LoanSchedules to delete.
   */
  limit?: number
}

/**
 * LoanSchedule.repayments
 */
export type LoanSchedule$repaymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanRepayment
   */
  select?: Prisma.LoanRepaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanRepayment
   */
  omit?: Prisma.LoanRepaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanRepaymentInclude<ExtArgs> | null
  where?: Prisma.LoanRepaymentWhereInput
  orderBy?: Prisma.LoanRepaymentOrderByWithRelationInput | Prisma.LoanRepaymentOrderByWithRelationInput[]
  cursor?: Prisma.LoanRepaymentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LoanRepaymentScalarFieldEnum | Prisma.LoanRepaymentScalarFieldEnum[]
}

/**
 * LoanSchedule without action
 */
export type LoanScheduleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanSchedule
   */
  select?: Prisma.LoanScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanSchedule
   */
  omit?: Prisma.LoanScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanScheduleInclude<ExtArgs> | null
}
