
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LoanType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LoanType
 * 
 */
export type LoanTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$LoanTypePayload>

export type AggregateLoanType = {
  _count: LoanTypeCountAggregateOutputType | null
  _avg: LoanTypeAvgAggregateOutputType | null
  _sum: LoanTypeSumAggregateOutputType | null
  _min: LoanTypeMinAggregateOutputType | null
  _max: LoanTypeMaxAggregateOutputType | null
}

export type LoanTypeAvgAggregateOutputType = {
  interestRate: runtime.Decimal | null
  minDuration: number | null
  maxDuration: number | null
  maxLoanAmount: runtime.Decimal | null
  savingsMultiplier: runtime.Decimal | null
}

export type LoanTypeSumAggregateOutputType = {
  interestRate: runtime.Decimal | null
  minDuration: number | null
  maxDuration: number | null
  maxLoanAmount: runtime.Decimal | null
  savingsMultiplier: runtime.Decimal | null
}

export type LoanTypeMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  interestRate: runtime.Decimal | null
  minDuration: number | null
  maxDuration: number | null
  maxLoanAmount: runtime.Decimal | null
  savingsMultiplier: runtime.Decimal | null
  isActive: boolean | null
  requiresApproval: boolean | null
  cooperativeId: string | null
}

export type LoanTypeMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  interestRate: runtime.Decimal | null
  minDuration: number | null
  maxDuration: number | null
  maxLoanAmount: runtime.Decimal | null
  savingsMultiplier: runtime.Decimal | null
  isActive: boolean | null
  requiresApproval: boolean | null
  cooperativeId: string | null
}

export type LoanTypeCountAggregateOutputType = {
  id: number
  name: number
  description: number
  interestRate: number
  minDuration: number
  maxDuration: number
  maxLoanAmount: number
  savingsMultiplier: number
  isActive: number
  requiresApproval: number
  cooperativeId: number
  _all: number
}


export type LoanTypeAvgAggregateInputType = {
  interestRate?: true
  minDuration?: true
  maxDuration?: true
  maxLoanAmount?: true
  savingsMultiplier?: true
}

export type LoanTypeSumAggregateInputType = {
  interestRate?: true
  minDuration?: true
  maxDuration?: true
  maxLoanAmount?: true
  savingsMultiplier?: true
}

export type LoanTypeMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  interestRate?: true
  minDuration?: true
  maxDuration?: true
  maxLoanAmount?: true
  savingsMultiplier?: true
  isActive?: true
  requiresApproval?: true
  cooperativeId?: true
}

export type LoanTypeMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  interestRate?: true
  minDuration?: true
  maxDuration?: true
  maxLoanAmount?: true
  savingsMultiplier?: true
  isActive?: true
  requiresApproval?: true
  cooperativeId?: true
}

export type LoanTypeCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  interestRate?: true
  minDuration?: true
  maxDuration?: true
  maxLoanAmount?: true
  savingsMultiplier?: true
  isActive?: true
  requiresApproval?: true
  cooperativeId?: true
  _all?: true
}

export type LoanTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LoanType to aggregate.
   */
  where?: Prisma.LoanTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoanTypes to fetch.
   */
  orderBy?: Prisma.LoanTypeOrderByWithRelationInput | Prisma.LoanTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LoanTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoanTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoanTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LoanTypes
  **/
  _count?: true | LoanTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LoanTypeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LoanTypeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LoanTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LoanTypeMaxAggregateInputType
}

export type GetLoanTypeAggregateType<T extends LoanTypeAggregateArgs> = {
      [P in keyof T & keyof AggregateLoanType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLoanType[P]>
    : Prisma.GetScalarType<T[P], AggregateLoanType[P]>
}




export type LoanTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LoanTypeWhereInput
  orderBy?: Prisma.LoanTypeOrderByWithAggregationInput | Prisma.LoanTypeOrderByWithAggregationInput[]
  by: Prisma.LoanTypeScalarFieldEnum[] | Prisma.LoanTypeScalarFieldEnum
  having?: Prisma.LoanTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LoanTypeCountAggregateInputType | true
  _avg?: LoanTypeAvgAggregateInputType
  _sum?: LoanTypeSumAggregateInputType
  _min?: LoanTypeMinAggregateInputType
  _max?: LoanTypeMaxAggregateInputType
}

export type LoanTypeGroupByOutputType = {
  id: string
  name: string
  description: string
  interestRate: runtime.Decimal
  minDuration: number
  maxDuration: number
  maxLoanAmount: runtime.Decimal
  savingsMultiplier: runtime.Decimal
  isActive: boolean
  requiresApproval: boolean
  cooperativeId: string | null
  _count: LoanTypeCountAggregateOutputType | null
  _avg: LoanTypeAvgAggregateOutputType | null
  _sum: LoanTypeSumAggregateOutputType | null
  _min: LoanTypeMinAggregateOutputType | null
  _max: LoanTypeMaxAggregateOutputType | null
}

export type GetLoanTypeGroupByPayload<T extends LoanTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LoanTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LoanTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LoanTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LoanTypeGroupByOutputType[P]>
      }
    >
  >



export type LoanTypeWhereInput = {
  AND?: Prisma.LoanTypeWhereInput | Prisma.LoanTypeWhereInput[]
  OR?: Prisma.LoanTypeWhereInput[]
  NOT?: Prisma.LoanTypeWhereInput | Prisma.LoanTypeWhereInput[]
  id?: Prisma.UuidFilter<"LoanType"> | string
  name?: Prisma.StringFilter<"LoanType"> | string
  description?: Prisma.StringFilter<"LoanType"> | string
  interestRate?: Prisma.DecimalFilter<"LoanType"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntFilter<"LoanType"> | number
  maxDuration?: Prisma.IntFilter<"LoanType"> | number
  maxLoanAmount?: Prisma.DecimalFilter<"LoanType"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalFilter<"LoanType"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolFilter<"LoanType"> | boolean
  requiresApproval?: Prisma.BoolFilter<"LoanType"> | boolean
  cooperativeId?: Prisma.UuidNullableFilter<"LoanType"> | string | null
  loans?: Prisma.LoanListRelationFilter
  cooperative?: Prisma.XOR<Prisma.CooperativeNullableScalarRelationFilter, Prisma.CooperativeWhereInput> | null
}

export type LoanTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  interestRate?: Prisma.SortOrder
  minDuration?: Prisma.SortOrder
  maxDuration?: Prisma.SortOrder
  maxLoanAmount?: Prisma.SortOrder
  savingsMultiplier?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  requiresApproval?: Prisma.SortOrder
  cooperativeId?: Prisma.SortOrderInput | Prisma.SortOrder
  loans?: Prisma.LoanOrderByRelationAggregateInput
  cooperative?: Prisma.CooperativeOrderByWithRelationInput
}

export type LoanTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name_cooperativeId?: Prisma.LoanTypeNameCooperativeIdCompoundUniqueInput
  AND?: Prisma.LoanTypeWhereInput | Prisma.LoanTypeWhereInput[]
  OR?: Prisma.LoanTypeWhereInput[]
  NOT?: Prisma.LoanTypeWhereInput | Prisma.LoanTypeWhereInput[]
  name?: Prisma.StringFilter<"LoanType"> | string
  description?: Prisma.StringFilter<"LoanType"> | string
  interestRate?: Prisma.DecimalFilter<"LoanType"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntFilter<"LoanType"> | number
  maxDuration?: Prisma.IntFilter<"LoanType"> | number
  maxLoanAmount?: Prisma.DecimalFilter<"LoanType"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalFilter<"LoanType"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolFilter<"LoanType"> | boolean
  requiresApproval?: Prisma.BoolFilter<"LoanType"> | boolean
  cooperativeId?: Prisma.UuidNullableFilter<"LoanType"> | string | null
  loans?: Prisma.LoanListRelationFilter
  cooperative?: Prisma.XOR<Prisma.CooperativeNullableScalarRelationFilter, Prisma.CooperativeWhereInput> | null
}, "id" | "name_cooperativeId">

export type LoanTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  interestRate?: Prisma.SortOrder
  minDuration?: Prisma.SortOrder
  maxDuration?: Prisma.SortOrder
  maxLoanAmount?: Prisma.SortOrder
  savingsMultiplier?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  requiresApproval?: Prisma.SortOrder
  cooperativeId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.LoanTypeCountOrderByAggregateInput
  _avg?: Prisma.LoanTypeAvgOrderByAggregateInput
  _max?: Prisma.LoanTypeMaxOrderByAggregateInput
  _min?: Prisma.LoanTypeMinOrderByAggregateInput
  _sum?: Prisma.LoanTypeSumOrderByAggregateInput
}

export type LoanTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.LoanTypeScalarWhereWithAggregatesInput | Prisma.LoanTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.LoanTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LoanTypeScalarWhereWithAggregatesInput | Prisma.LoanTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"LoanType"> | string
  name?: Prisma.StringWithAggregatesFilter<"LoanType"> | string
  description?: Prisma.StringWithAggregatesFilter<"LoanType"> | string
  interestRate?: Prisma.DecimalWithAggregatesFilter<"LoanType"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntWithAggregatesFilter<"LoanType"> | number
  maxDuration?: Prisma.IntWithAggregatesFilter<"LoanType"> | number
  maxLoanAmount?: Prisma.DecimalWithAggregatesFilter<"LoanType"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalWithAggregatesFilter<"LoanType"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolWithAggregatesFilter<"LoanType"> | boolean
  requiresApproval?: Prisma.BoolWithAggregatesFilter<"LoanType"> | boolean
  cooperativeId?: Prisma.UuidNullableWithAggregatesFilter<"LoanType"> | string | null
}

export type LoanTypeCreateInput = {
  id?: string
  name: string
  description?: string
  interestRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration: number
  maxDuration: number
  maxLoanAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: boolean
  requiresApproval?: boolean
  loans?: Prisma.LoanCreateNestedManyWithoutLoanTypeInput
  cooperative?: Prisma.CooperativeCreateNestedOneWithoutLoanTypesInput
}

export type LoanTypeUncheckedCreateInput = {
  id?: string
  name: string
  description?: string
  interestRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration: number
  maxDuration: number
  maxLoanAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: boolean
  requiresApproval?: boolean
  cooperativeId?: string | null
  loans?: Prisma.LoanUncheckedCreateNestedManyWithoutLoanTypeInput
}

export type LoanTypeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  interestRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxLoanAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresApproval?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loans?: Prisma.LoanUpdateManyWithoutLoanTypeNestedInput
  cooperative?: Prisma.CooperativeUpdateOneWithoutLoanTypesNestedInput
}

export type LoanTypeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  interestRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxLoanAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresApproval?: Prisma.BoolFieldUpdateOperationsInput | boolean
  cooperativeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loans?: Prisma.LoanUncheckedUpdateManyWithoutLoanTypeNestedInput
}

export type LoanTypeCreateManyInput = {
  id?: string
  name: string
  description?: string
  interestRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration: number
  maxDuration: number
  maxLoanAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: boolean
  requiresApproval?: boolean
  cooperativeId?: string | null
}

export type LoanTypeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  interestRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxLoanAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresApproval?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type LoanTypeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  interestRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxLoanAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresApproval?: Prisma.BoolFieldUpdateOperationsInput | boolean
  cooperativeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LoanTypeNameCooperativeIdCompoundUniqueInput = {
  name: string
  cooperativeId: string
}

export type LoanTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  interestRate?: Prisma.SortOrder
  minDuration?: Prisma.SortOrder
  maxDuration?: Prisma.SortOrder
  maxLoanAmount?: Prisma.SortOrder
  savingsMultiplier?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  requiresApproval?: Prisma.SortOrder
  cooperativeId?: Prisma.SortOrder
}

export type LoanTypeAvgOrderByAggregateInput = {
  interestRate?: Prisma.SortOrder
  minDuration?: Prisma.SortOrder
  maxDuration?: Prisma.SortOrder
  maxLoanAmount?: Prisma.SortOrder
  savingsMultiplier?: Prisma.SortOrder
}

export type LoanTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  interestRate?: Prisma.SortOrder
  minDuration?: Prisma.SortOrder
  maxDuration?: Prisma.SortOrder
  maxLoanAmount?: Prisma.SortOrder
  savingsMultiplier?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  requiresApproval?: Prisma.SortOrder
  cooperativeId?: Prisma.SortOrder
}

export type LoanTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  interestRate?: Prisma.SortOrder
  minDuration?: Prisma.SortOrder
  maxDuration?: Prisma.SortOrder
  maxLoanAmount?: Prisma.SortOrder
  savingsMultiplier?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  requiresApproval?: Prisma.SortOrder
  cooperativeId?: Prisma.SortOrder
}

export type LoanTypeSumOrderByAggregateInput = {
  interestRate?: Prisma.SortOrder
  minDuration?: Prisma.SortOrder
  maxDuration?: Prisma.SortOrder
  maxLoanAmount?: Prisma.SortOrder
  savingsMultiplier?: Prisma.SortOrder
}

export type LoanTypeScalarRelationFilter = {
  is?: Prisma.LoanTypeWhereInput
  isNot?: Prisma.LoanTypeWhereInput
}

export type LoanTypeListRelationFilter = {
  every?: Prisma.LoanTypeWhereInput
  some?: Prisma.LoanTypeWhereInput
  none?: Prisma.LoanTypeWhereInput
}

export type LoanTypeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LoanTypeCreateNestedOneWithoutLoansInput = {
  create?: Prisma.XOR<Prisma.LoanTypeCreateWithoutLoansInput, Prisma.LoanTypeUncheckedCreateWithoutLoansInput>
  connectOrCreate?: Prisma.LoanTypeCreateOrConnectWithoutLoansInput
  connect?: Prisma.LoanTypeWhereUniqueInput
}

export type LoanTypeUpdateOneRequiredWithoutLoansNestedInput = {
  create?: Prisma.XOR<Prisma.LoanTypeCreateWithoutLoansInput, Prisma.LoanTypeUncheckedCreateWithoutLoansInput>
  connectOrCreate?: Prisma.LoanTypeCreateOrConnectWithoutLoansInput
  upsert?: Prisma.LoanTypeUpsertWithoutLoansInput
  connect?: Prisma.LoanTypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LoanTypeUpdateToOneWithWhereWithoutLoansInput, Prisma.LoanTypeUpdateWithoutLoansInput>, Prisma.LoanTypeUncheckedUpdateWithoutLoansInput>
}

export type LoanTypeCreateNestedManyWithoutCooperativeInput = {
  create?: Prisma.XOR<Prisma.LoanTypeCreateWithoutCooperativeInput, Prisma.LoanTypeUncheckedCreateWithoutCooperativeInput> | Prisma.LoanTypeCreateWithoutCooperativeInput[] | Prisma.LoanTypeUncheckedCreateWithoutCooperativeInput[]
  connectOrCreate?: Prisma.LoanTypeCreateOrConnectWithoutCooperativeInput | Prisma.LoanTypeCreateOrConnectWithoutCooperativeInput[]
  createMany?: Prisma.LoanTypeCreateManyCooperativeInputEnvelope
  connect?: Prisma.LoanTypeWhereUniqueInput | Prisma.LoanTypeWhereUniqueInput[]
}

export type LoanTypeUncheckedCreateNestedManyWithoutCooperativeInput = {
  create?: Prisma.XOR<Prisma.LoanTypeCreateWithoutCooperativeInput, Prisma.LoanTypeUncheckedCreateWithoutCooperativeInput> | Prisma.LoanTypeCreateWithoutCooperativeInput[] | Prisma.LoanTypeUncheckedCreateWithoutCooperativeInput[]
  connectOrCreate?: Prisma.LoanTypeCreateOrConnectWithoutCooperativeInput | Prisma.LoanTypeCreateOrConnectWithoutCooperativeInput[]
  createMany?: Prisma.LoanTypeCreateManyCooperativeInputEnvelope
  connect?: Prisma.LoanTypeWhereUniqueInput | Prisma.LoanTypeWhereUniqueInput[]
}

export type LoanTypeUpdateManyWithoutCooperativeNestedInput = {
  create?: Prisma.XOR<Prisma.LoanTypeCreateWithoutCooperativeInput, Prisma.LoanTypeUncheckedCreateWithoutCooperativeInput> | Prisma.LoanTypeCreateWithoutCooperativeInput[] | Prisma.LoanTypeUncheckedCreateWithoutCooperativeInput[]
  connectOrCreate?: Prisma.LoanTypeCreateOrConnectWithoutCooperativeInput | Prisma.LoanTypeCreateOrConnectWithoutCooperativeInput[]
  upsert?: Prisma.LoanTypeUpsertWithWhereUniqueWithoutCooperativeInput | Prisma.LoanTypeUpsertWithWhereUniqueWithoutCooperativeInput[]
  createMany?: Prisma.LoanTypeCreateManyCooperativeInputEnvelope
  set?: Prisma.LoanTypeWhereUniqueInput | Prisma.LoanTypeWhereUniqueInput[]
  disconnect?: Prisma.LoanTypeWhereUniqueInput | Prisma.LoanTypeWhereUniqueInput[]
  delete?: Prisma.LoanTypeWhereUniqueInput | Prisma.LoanTypeWhereUniqueInput[]
  connect?: Prisma.LoanTypeWhereUniqueInput | Prisma.LoanTypeWhereUniqueInput[]
  update?: Prisma.LoanTypeUpdateWithWhereUniqueWithoutCooperativeInput | Prisma.LoanTypeUpdateWithWhereUniqueWithoutCooperativeInput[]
  updateMany?: Prisma.LoanTypeUpdateManyWithWhereWithoutCooperativeInput | Prisma.LoanTypeUpdateManyWithWhereWithoutCooperativeInput[]
  deleteMany?: Prisma.LoanTypeScalarWhereInput | Prisma.LoanTypeScalarWhereInput[]
}

export type LoanTypeUncheckedUpdateManyWithoutCooperativeNestedInput = {
  create?: Prisma.XOR<Prisma.LoanTypeCreateWithoutCooperativeInput, Prisma.LoanTypeUncheckedCreateWithoutCooperativeInput> | Prisma.LoanTypeCreateWithoutCooperativeInput[] | Prisma.LoanTypeUncheckedCreateWithoutCooperativeInput[]
  connectOrCreate?: Prisma.LoanTypeCreateOrConnectWithoutCooperativeInput | Prisma.LoanTypeCreateOrConnectWithoutCooperativeInput[]
  upsert?: Prisma.LoanTypeUpsertWithWhereUniqueWithoutCooperativeInput | Prisma.LoanTypeUpsertWithWhereUniqueWithoutCooperativeInput[]
  createMany?: Prisma.LoanTypeCreateManyCooperativeInputEnvelope
  set?: Prisma.LoanTypeWhereUniqueInput | Prisma.LoanTypeWhereUniqueInput[]
  disconnect?: Prisma.LoanTypeWhereUniqueInput | Prisma.LoanTypeWhereUniqueInput[]
  delete?: Prisma.LoanTypeWhereUniqueInput | Prisma.LoanTypeWhereUniqueInput[]
  connect?: Prisma.LoanTypeWhereUniqueInput | Prisma.LoanTypeWhereUniqueInput[]
  update?: Prisma.LoanTypeUpdateWithWhereUniqueWithoutCooperativeInput | Prisma.LoanTypeUpdateWithWhereUniqueWithoutCooperativeInput[]
  updateMany?: Prisma.LoanTypeUpdateManyWithWhereWithoutCooperativeInput | Prisma.LoanTypeUpdateManyWithWhereWithoutCooperativeInput[]
  deleteMany?: Prisma.LoanTypeScalarWhereInput | Prisma.LoanTypeScalarWhereInput[]
}

export type LoanTypeCreateWithoutLoansInput = {
  id?: string
  name: string
  description?: string
  interestRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration: number
  maxDuration: number
  maxLoanAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: boolean
  requiresApproval?: boolean
  cooperative?: Prisma.CooperativeCreateNestedOneWithoutLoanTypesInput
}

export type LoanTypeUncheckedCreateWithoutLoansInput = {
  id?: string
  name: string
  description?: string
  interestRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration: number
  maxDuration: number
  maxLoanAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: boolean
  requiresApproval?: boolean
  cooperativeId?: string | null
}

export type LoanTypeCreateOrConnectWithoutLoansInput = {
  where: Prisma.LoanTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.LoanTypeCreateWithoutLoansInput, Prisma.LoanTypeUncheckedCreateWithoutLoansInput>
}

export type LoanTypeUpsertWithoutLoansInput = {
  update: Prisma.XOR<Prisma.LoanTypeUpdateWithoutLoansInput, Prisma.LoanTypeUncheckedUpdateWithoutLoansInput>
  create: Prisma.XOR<Prisma.LoanTypeCreateWithoutLoansInput, Prisma.LoanTypeUncheckedCreateWithoutLoansInput>
  where?: Prisma.LoanTypeWhereInput
}

export type LoanTypeUpdateToOneWithWhereWithoutLoansInput = {
  where?: Prisma.LoanTypeWhereInput
  data: Prisma.XOR<Prisma.LoanTypeUpdateWithoutLoansInput, Prisma.LoanTypeUncheckedUpdateWithoutLoansInput>
}

export type LoanTypeUpdateWithoutLoansInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  interestRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxLoanAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresApproval?: Prisma.BoolFieldUpdateOperationsInput | boolean
  cooperative?: Prisma.CooperativeUpdateOneWithoutLoanTypesNestedInput
}

export type LoanTypeUncheckedUpdateWithoutLoansInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  interestRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxLoanAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresApproval?: Prisma.BoolFieldUpdateOperationsInput | boolean
  cooperativeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LoanTypeCreateWithoutCooperativeInput = {
  id?: string
  name: string
  description?: string
  interestRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration: number
  maxDuration: number
  maxLoanAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: boolean
  requiresApproval?: boolean
  loans?: Prisma.LoanCreateNestedManyWithoutLoanTypeInput
}

export type LoanTypeUncheckedCreateWithoutCooperativeInput = {
  id?: string
  name: string
  description?: string
  interestRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration: number
  maxDuration: number
  maxLoanAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: boolean
  requiresApproval?: boolean
  loans?: Prisma.LoanUncheckedCreateNestedManyWithoutLoanTypeInput
}

export type LoanTypeCreateOrConnectWithoutCooperativeInput = {
  where: Prisma.LoanTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.LoanTypeCreateWithoutCooperativeInput, Prisma.LoanTypeUncheckedCreateWithoutCooperativeInput>
}

export type LoanTypeCreateManyCooperativeInputEnvelope = {
  data: Prisma.LoanTypeCreateManyCooperativeInput | Prisma.LoanTypeCreateManyCooperativeInput[]
  skipDuplicates?: boolean
}

export type LoanTypeUpsertWithWhereUniqueWithoutCooperativeInput = {
  where: Prisma.LoanTypeWhereUniqueInput
  update: Prisma.XOR<Prisma.LoanTypeUpdateWithoutCooperativeInput, Prisma.LoanTypeUncheckedUpdateWithoutCooperativeInput>
  create: Prisma.XOR<Prisma.LoanTypeCreateWithoutCooperativeInput, Prisma.LoanTypeUncheckedCreateWithoutCooperativeInput>
}

export type LoanTypeUpdateWithWhereUniqueWithoutCooperativeInput = {
  where: Prisma.LoanTypeWhereUniqueInput
  data: Prisma.XOR<Prisma.LoanTypeUpdateWithoutCooperativeInput, Prisma.LoanTypeUncheckedUpdateWithoutCooperativeInput>
}

export type LoanTypeUpdateManyWithWhereWithoutCooperativeInput = {
  where: Prisma.LoanTypeScalarWhereInput
  data: Prisma.XOR<Prisma.LoanTypeUpdateManyMutationInput, Prisma.LoanTypeUncheckedUpdateManyWithoutCooperativeInput>
}

export type LoanTypeScalarWhereInput = {
  AND?: Prisma.LoanTypeScalarWhereInput | Prisma.LoanTypeScalarWhereInput[]
  OR?: Prisma.LoanTypeScalarWhereInput[]
  NOT?: Prisma.LoanTypeScalarWhereInput | Prisma.LoanTypeScalarWhereInput[]
  id?: Prisma.UuidFilter<"LoanType"> | string
  name?: Prisma.StringFilter<"LoanType"> | string
  description?: Prisma.StringFilter<"LoanType"> | string
  interestRate?: Prisma.DecimalFilter<"LoanType"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntFilter<"LoanType"> | number
  maxDuration?: Prisma.IntFilter<"LoanType"> | number
  maxLoanAmount?: Prisma.DecimalFilter<"LoanType"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalFilter<"LoanType"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolFilter<"LoanType"> | boolean
  requiresApproval?: Prisma.BoolFilter<"LoanType"> | boolean
  cooperativeId?: Prisma.UuidNullableFilter<"LoanType"> | string | null
}

export type LoanTypeCreateManyCooperativeInput = {
  id?: string
  name: string
  description?: string
  interestRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration: number
  maxDuration: number
  maxLoanAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: boolean
  requiresApproval?: boolean
}

export type LoanTypeUpdateWithoutCooperativeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  interestRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxLoanAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresApproval?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loans?: Prisma.LoanUpdateManyWithoutLoanTypeNestedInput
}

export type LoanTypeUncheckedUpdateWithoutCooperativeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  interestRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxLoanAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresApproval?: Prisma.BoolFieldUpdateOperationsInput | boolean
  loans?: Prisma.LoanUncheckedUpdateManyWithoutLoanTypeNestedInput
}

export type LoanTypeUncheckedUpdateManyWithoutCooperativeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  interestRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  minDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxDuration?: Prisma.IntFieldUpdateOperationsInput | number
  maxLoanAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  savingsMultiplier?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  requiresApproval?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type LoanTypeCountOutputType
 */

export type LoanTypeCountOutputType = {
  loans: number
}

export type LoanTypeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  loans?: boolean | LoanTypeCountOutputTypeCountLoansArgs
}

/**
 * LoanTypeCountOutputType without action
 */
export type LoanTypeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanTypeCountOutputType
   */
  select?: Prisma.LoanTypeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LoanTypeCountOutputType without action
 */
export type LoanTypeCountOutputTypeCountLoansArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LoanWhereInput
}


export type LoanTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  interestRate?: boolean
  minDuration?: boolean
  maxDuration?: boolean
  maxLoanAmount?: boolean
  savingsMultiplier?: boolean
  isActive?: boolean
  requiresApproval?: boolean
  cooperativeId?: boolean
  loans?: boolean | Prisma.LoanType$loansArgs<ExtArgs>
  cooperative?: boolean | Prisma.LoanType$cooperativeArgs<ExtArgs>
  _count?: boolean | Prisma.LoanTypeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["loanType"]>

export type LoanTypeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  interestRate?: boolean
  minDuration?: boolean
  maxDuration?: boolean
  maxLoanAmount?: boolean
  savingsMultiplier?: boolean
  isActive?: boolean
  requiresApproval?: boolean
  cooperativeId?: boolean
  cooperative?: boolean | Prisma.LoanType$cooperativeArgs<ExtArgs>
}, ExtArgs["result"]["loanType"]>

export type LoanTypeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  interestRate?: boolean
  minDuration?: boolean
  maxDuration?: boolean
  maxLoanAmount?: boolean
  savingsMultiplier?: boolean
  isActive?: boolean
  requiresApproval?: boolean
  cooperativeId?: boolean
  cooperative?: boolean | Prisma.LoanType$cooperativeArgs<ExtArgs>
}, ExtArgs["result"]["loanType"]>

export type LoanTypeSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  interestRate?: boolean
  minDuration?: boolean
  maxDuration?: boolean
  maxLoanAmount?: boolean
  savingsMultiplier?: boolean
  isActive?: boolean
  requiresApproval?: boolean
  cooperativeId?: boolean
}

export type LoanTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "interestRate" | "minDuration" | "maxDuration" | "maxLoanAmount" | "savingsMultiplier" | "isActive" | "requiresApproval" | "cooperativeId", ExtArgs["result"]["loanType"]>
export type LoanTypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  loans?: boolean | Prisma.LoanType$loansArgs<ExtArgs>
  cooperative?: boolean | Prisma.LoanType$cooperativeArgs<ExtArgs>
  _count?: boolean | Prisma.LoanTypeCountOutputTypeDefaultArgs<ExtArgs>
}
export type LoanTypeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cooperative?: boolean | Prisma.LoanType$cooperativeArgs<ExtArgs>
}
export type LoanTypeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cooperative?: boolean | Prisma.LoanType$cooperativeArgs<ExtArgs>
}

export type $LoanTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LoanType"
  objects: {
    loans: Prisma.$LoanPayload<ExtArgs>[]
    cooperative: Prisma.$CooperativePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string
    interestRate: runtime.Decimal
    minDuration: number
    maxDuration: number
    maxLoanAmount: runtime.Decimal
    savingsMultiplier: runtime.Decimal
    isActive: boolean
    requiresApproval: boolean
    cooperativeId: string | null
  }, ExtArgs["result"]["loanType"]>
  composites: {}
}

export type LoanTypeGetPayload<S extends boolean | null | undefined | LoanTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LoanTypePayload, S>

export type LoanTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LoanTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LoanTypeCountAggregateInputType | true
  }

export interface LoanTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LoanType'], meta: { name: 'LoanType' } }
  /**
   * Find zero or one LoanType that matches the filter.
   * @param {LoanTypeFindUniqueArgs} args - Arguments to find a LoanType
   * @example
   * // Get one LoanType
   * const loanType = await prisma.loanType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LoanTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, LoanTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LoanTypeClient<runtime.Types.Result.GetResult<Prisma.$LoanTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LoanType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LoanTypeFindUniqueOrThrowArgs} args - Arguments to find a LoanType
   * @example
   * // Get one LoanType
   * const loanType = await prisma.loanType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LoanTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LoanTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LoanTypeClient<runtime.Types.Result.GetResult<Prisma.$LoanTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LoanType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanTypeFindFirstArgs} args - Arguments to find a LoanType
   * @example
   * // Get one LoanType
   * const loanType = await prisma.loanType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LoanTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, LoanTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__LoanTypeClient<runtime.Types.Result.GetResult<Prisma.$LoanTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LoanType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanTypeFindFirstOrThrowArgs} args - Arguments to find a LoanType
   * @example
   * // Get one LoanType
   * const loanType = await prisma.loanType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LoanTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LoanTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LoanTypeClient<runtime.Types.Result.GetResult<Prisma.$LoanTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LoanTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LoanTypes
   * const loanTypes = await prisma.loanType.findMany()
   * 
   * // Get first 10 LoanTypes
   * const loanTypes = await prisma.loanType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const loanTypeWithIdOnly = await prisma.loanType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LoanTypeFindManyArgs>(args?: Prisma.SelectSubset<T, LoanTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoanTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LoanType.
   * @param {LoanTypeCreateArgs} args - Arguments to create a LoanType.
   * @example
   * // Create one LoanType
   * const LoanType = await prisma.loanType.create({
   *   data: {
   *     // ... data to create a LoanType
   *   }
   * })
   * 
   */
  create<T extends LoanTypeCreateArgs>(args: Prisma.SelectSubset<T, LoanTypeCreateArgs<ExtArgs>>): Prisma.Prisma__LoanTypeClient<runtime.Types.Result.GetResult<Prisma.$LoanTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LoanTypes.
   * @param {LoanTypeCreateManyArgs} args - Arguments to create many LoanTypes.
   * @example
   * // Create many LoanTypes
   * const loanType = await prisma.loanType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LoanTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, LoanTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LoanTypes and returns the data saved in the database.
   * @param {LoanTypeCreateManyAndReturnArgs} args - Arguments to create many LoanTypes.
   * @example
   * // Create many LoanTypes
   * const loanType = await prisma.loanType.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LoanTypes and only return the `id`
   * const loanTypeWithIdOnly = await prisma.loanType.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LoanTypeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LoanTypeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoanTypePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LoanType.
   * @param {LoanTypeDeleteArgs} args - Arguments to delete one LoanType.
   * @example
   * // Delete one LoanType
   * const LoanType = await prisma.loanType.delete({
   *   where: {
   *     // ... filter to delete one LoanType
   *   }
   * })
   * 
   */
  delete<T extends LoanTypeDeleteArgs>(args: Prisma.SelectSubset<T, LoanTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__LoanTypeClient<runtime.Types.Result.GetResult<Prisma.$LoanTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LoanType.
   * @param {LoanTypeUpdateArgs} args - Arguments to update one LoanType.
   * @example
   * // Update one LoanType
   * const loanType = await prisma.loanType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LoanTypeUpdateArgs>(args: Prisma.SelectSubset<T, LoanTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__LoanTypeClient<runtime.Types.Result.GetResult<Prisma.$LoanTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LoanTypes.
   * @param {LoanTypeDeleteManyArgs} args - Arguments to filter LoanTypes to delete.
   * @example
   * // Delete a few LoanTypes
   * const { count } = await prisma.loanType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LoanTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, LoanTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LoanTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LoanTypes
   * const loanType = await prisma.loanType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LoanTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, LoanTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LoanTypes and returns the data updated in the database.
   * @param {LoanTypeUpdateManyAndReturnArgs} args - Arguments to update many LoanTypes.
   * @example
   * // Update many LoanTypes
   * const loanType = await prisma.loanType.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LoanTypes and only return the `id`
   * const loanTypeWithIdOnly = await prisma.loanType.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LoanTypeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LoanTypeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoanTypePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LoanType.
   * @param {LoanTypeUpsertArgs} args - Arguments to update or create a LoanType.
   * @example
   * // Update or create a LoanType
   * const loanType = await prisma.loanType.upsert({
   *   create: {
   *     // ... data to create a LoanType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LoanType we want to update
   *   }
   * })
   */
  upsert<T extends LoanTypeUpsertArgs>(args: Prisma.SelectSubset<T, LoanTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__LoanTypeClient<runtime.Types.Result.GetResult<Prisma.$LoanTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LoanTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanTypeCountArgs} args - Arguments to filter LoanTypes to count.
   * @example
   * // Count the number of LoanTypes
   * const count = await prisma.loanType.count({
   *   where: {
   *     // ... the filter for the LoanTypes we want to count
   *   }
   * })
  **/
  count<T extends LoanTypeCountArgs>(
    args?: Prisma.Subset<T, LoanTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LoanTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LoanType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LoanTypeAggregateArgs>(args: Prisma.Subset<T, LoanTypeAggregateArgs>): Prisma.PrismaPromise<GetLoanTypeAggregateType<T>>

  /**
   * Group by LoanType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoanTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LoanTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LoanTypeGroupByArgs['orderBy'] }
      : { orderBy?: LoanTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LoanTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLoanTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LoanType model
 */
readonly fields: LoanTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LoanType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LoanTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  loans<T extends Prisma.LoanType$loansArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LoanType$loansArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoanPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  cooperative<T extends Prisma.LoanType$cooperativeArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LoanType$cooperativeArgs<ExtArgs>>): Prisma.Prisma__CooperativeClient<runtime.Types.Result.GetResult<Prisma.$CooperativePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LoanType model
 */
export interface LoanTypeFieldRefs {
  readonly id: Prisma.FieldRef<"LoanType", 'String'>
  readonly name: Prisma.FieldRef<"LoanType", 'String'>
  readonly description: Prisma.FieldRef<"LoanType", 'String'>
  readonly interestRate: Prisma.FieldRef<"LoanType", 'Decimal'>
  readonly minDuration: Prisma.FieldRef<"LoanType", 'Int'>
  readonly maxDuration: Prisma.FieldRef<"LoanType", 'Int'>
  readonly maxLoanAmount: Prisma.FieldRef<"LoanType", 'Decimal'>
  readonly savingsMultiplier: Prisma.FieldRef<"LoanType", 'Decimal'>
  readonly isActive: Prisma.FieldRef<"LoanType", 'Boolean'>
  readonly requiresApproval: Prisma.FieldRef<"LoanType", 'Boolean'>
  readonly cooperativeId: Prisma.FieldRef<"LoanType", 'String'>
}
    

// Custom InputTypes
/**
 * LoanType findUnique
 */
export type LoanTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanType
   */
  select?: Prisma.LoanTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanType
   */
  omit?: Prisma.LoanTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanTypeInclude<ExtArgs> | null
  /**
   * Filter, which LoanType to fetch.
   */
  where: Prisma.LoanTypeWhereUniqueInput
}

/**
 * LoanType findUniqueOrThrow
 */
export type LoanTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanType
   */
  select?: Prisma.LoanTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanType
   */
  omit?: Prisma.LoanTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanTypeInclude<ExtArgs> | null
  /**
   * Filter, which LoanType to fetch.
   */
  where: Prisma.LoanTypeWhereUniqueInput
}

/**
 * LoanType findFirst
 */
export type LoanTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanType
   */
  select?: Prisma.LoanTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanType
   */
  omit?: Prisma.LoanTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanTypeInclude<ExtArgs> | null
  /**
   * Filter, which LoanType to fetch.
   */
  where?: Prisma.LoanTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoanTypes to fetch.
   */
  orderBy?: Prisma.LoanTypeOrderByWithRelationInput | Prisma.LoanTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LoanTypes.
   */
  cursor?: Prisma.LoanTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoanTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoanTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoanTypes.
   */
  distinct?: Prisma.LoanTypeScalarFieldEnum | Prisma.LoanTypeScalarFieldEnum[]
}

/**
 * LoanType findFirstOrThrow
 */
export type LoanTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanType
   */
  select?: Prisma.LoanTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanType
   */
  omit?: Prisma.LoanTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanTypeInclude<ExtArgs> | null
  /**
   * Filter, which LoanType to fetch.
   */
  where?: Prisma.LoanTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoanTypes to fetch.
   */
  orderBy?: Prisma.LoanTypeOrderByWithRelationInput | Prisma.LoanTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LoanTypes.
   */
  cursor?: Prisma.LoanTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoanTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoanTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoanTypes.
   */
  distinct?: Prisma.LoanTypeScalarFieldEnum | Prisma.LoanTypeScalarFieldEnum[]
}

/**
 * LoanType findMany
 */
export type LoanTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanType
   */
  select?: Prisma.LoanTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanType
   */
  omit?: Prisma.LoanTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanTypeInclude<ExtArgs> | null
  /**
   * Filter, which LoanTypes to fetch.
   */
  where?: Prisma.LoanTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoanTypes to fetch.
   */
  orderBy?: Prisma.LoanTypeOrderByWithRelationInput | Prisma.LoanTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LoanTypes.
   */
  cursor?: Prisma.LoanTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoanTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoanTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoanTypes.
   */
  distinct?: Prisma.LoanTypeScalarFieldEnum | Prisma.LoanTypeScalarFieldEnum[]
}

/**
 * LoanType create
 */
export type LoanTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanType
   */
  select?: Prisma.LoanTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanType
   */
  omit?: Prisma.LoanTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanTypeInclude<ExtArgs> | null
  /**
   * The data needed to create a LoanType.
   */
  data: Prisma.XOR<Prisma.LoanTypeCreateInput, Prisma.LoanTypeUncheckedCreateInput>
}

/**
 * LoanType createMany
 */
export type LoanTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LoanTypes.
   */
  data: Prisma.LoanTypeCreateManyInput | Prisma.LoanTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LoanType createManyAndReturn
 */
export type LoanTypeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanType
   */
  select?: Prisma.LoanTypeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LoanType
   */
  omit?: Prisma.LoanTypeOmit<ExtArgs> | null
  /**
   * The data used to create many LoanTypes.
   */
  data: Prisma.LoanTypeCreateManyInput | Prisma.LoanTypeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanTypeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LoanType update
 */
export type LoanTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanType
   */
  select?: Prisma.LoanTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanType
   */
  omit?: Prisma.LoanTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanTypeInclude<ExtArgs> | null
  /**
   * The data needed to update a LoanType.
   */
  data: Prisma.XOR<Prisma.LoanTypeUpdateInput, Prisma.LoanTypeUncheckedUpdateInput>
  /**
   * Choose, which LoanType to update.
   */
  where: Prisma.LoanTypeWhereUniqueInput
}

/**
 * LoanType updateMany
 */
export type LoanTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LoanTypes.
   */
  data: Prisma.XOR<Prisma.LoanTypeUpdateManyMutationInput, Prisma.LoanTypeUncheckedUpdateManyInput>
  /**
   * Filter which LoanTypes to update
   */
  where?: Prisma.LoanTypeWhereInput
  /**
   * Limit how many LoanTypes to update.
   */
  limit?: number
}

/**
 * LoanType updateManyAndReturn
 */
export type LoanTypeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanType
   */
  select?: Prisma.LoanTypeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LoanType
   */
  omit?: Prisma.LoanTypeOmit<ExtArgs> | null
  /**
   * The data used to update LoanTypes.
   */
  data: Prisma.XOR<Prisma.LoanTypeUpdateManyMutationInput, Prisma.LoanTypeUncheckedUpdateManyInput>
  /**
   * Filter which LoanTypes to update
   */
  where?: Prisma.LoanTypeWhereInput
  /**
   * Limit how many LoanTypes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanTypeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LoanType upsert
 */
export type LoanTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanType
   */
  select?: Prisma.LoanTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanType
   */
  omit?: Prisma.LoanTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanTypeInclude<ExtArgs> | null
  /**
   * The filter to search for the LoanType to update in case it exists.
   */
  where: Prisma.LoanTypeWhereUniqueInput
  /**
   * In case the LoanType found by the `where` argument doesn't exist, create a new LoanType with this data.
   */
  create: Prisma.XOR<Prisma.LoanTypeCreateInput, Prisma.LoanTypeUncheckedCreateInput>
  /**
   * In case the LoanType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LoanTypeUpdateInput, Prisma.LoanTypeUncheckedUpdateInput>
}

/**
 * LoanType delete
 */
export type LoanTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanType
   */
  select?: Prisma.LoanTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanType
   */
  omit?: Prisma.LoanTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanTypeInclude<ExtArgs> | null
  /**
   * Filter which LoanType to delete.
   */
  where: Prisma.LoanTypeWhereUniqueInput
}

/**
 * LoanType deleteMany
 */
export type LoanTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LoanTypes to delete
   */
  where?: Prisma.LoanTypeWhereInput
  /**
   * Limit how many LoanTypes to delete.
   */
  limit?: number
}

/**
 * LoanType.loans
 */
export type LoanType$loansArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Loan
   */
  select?: Prisma.LoanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Loan
   */
  omit?: Prisma.LoanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanInclude<ExtArgs> | null
  where?: Prisma.LoanWhereInput
  orderBy?: Prisma.LoanOrderByWithRelationInput | Prisma.LoanOrderByWithRelationInput[]
  cursor?: Prisma.LoanWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LoanScalarFieldEnum | Prisma.LoanScalarFieldEnum[]
}

/**
 * LoanType.cooperative
 */
export type LoanType$cooperativeArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cooperative
   */
  select?: Prisma.CooperativeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cooperative
   */
  omit?: Prisma.CooperativeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CooperativeInclude<ExtArgs> | null
  where?: Prisma.CooperativeWhereInput
}

/**
 * LoanType without action
 */
export type LoanTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoanType
   */
  select?: Prisma.LoanTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoanType
   */
  omit?: Prisma.LoanTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoanTypeInclude<ExtArgs> | null
}
