
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PersonalSavingsPlan` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PersonalSavingsPlan
 * 
 */
export type PersonalSavingsPlanModel = runtime.Types.Result.DefaultSelection<Prisma.$PersonalSavingsPlanPayload>

export type AggregatePersonalSavingsPlan = {
  _count: PersonalSavingsPlanCountAggregateOutputType | null
  _min: PersonalSavingsPlanMinAggregateOutputType | null
  _max: PersonalSavingsPlanMaxAggregateOutputType | null
}

export type PersonalSavingsPlanMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PersonalSavingsPlanMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PersonalSavingsPlanCountAggregateOutputType = {
  id: number
  name: number
  description: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PersonalSavingsPlanMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type PersonalSavingsPlanMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type PersonalSavingsPlanCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PersonalSavingsPlanAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PersonalSavingsPlan to aggregate.
   */
  where?: Prisma.PersonalSavingsPlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PersonalSavingsPlans to fetch.
   */
  orderBy?: Prisma.PersonalSavingsPlanOrderByWithRelationInput | Prisma.PersonalSavingsPlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PersonalSavingsPlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PersonalSavingsPlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PersonalSavingsPlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PersonalSavingsPlans
  **/
  _count?: true | PersonalSavingsPlanCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PersonalSavingsPlanMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PersonalSavingsPlanMaxAggregateInputType
}

export type GetPersonalSavingsPlanAggregateType<T extends PersonalSavingsPlanAggregateArgs> = {
      [P in keyof T & keyof AggregatePersonalSavingsPlan]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePersonalSavingsPlan[P]>
    : Prisma.GetScalarType<T[P], AggregatePersonalSavingsPlan[P]>
}




export type PersonalSavingsPlanGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PersonalSavingsPlanWhereInput
  orderBy?: Prisma.PersonalSavingsPlanOrderByWithAggregationInput | Prisma.PersonalSavingsPlanOrderByWithAggregationInput[]
  by: Prisma.PersonalSavingsPlanScalarFieldEnum[] | Prisma.PersonalSavingsPlanScalarFieldEnum
  having?: Prisma.PersonalSavingsPlanScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PersonalSavingsPlanCountAggregateInputType | true
  _min?: PersonalSavingsPlanMinAggregateInputType
  _max?: PersonalSavingsPlanMaxAggregateInputType
}

export type PersonalSavingsPlanGroupByOutputType = {
  id: string
  name: string
  description: string | null
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: PersonalSavingsPlanCountAggregateOutputType | null
  _min: PersonalSavingsPlanMinAggregateOutputType | null
  _max: PersonalSavingsPlanMaxAggregateOutputType | null
}

export type GetPersonalSavingsPlanGroupByPayload<T extends PersonalSavingsPlanGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PersonalSavingsPlanGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PersonalSavingsPlanGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PersonalSavingsPlanGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PersonalSavingsPlanGroupByOutputType[P]>
      }
    >
  >



export type PersonalSavingsPlanWhereInput = {
  AND?: Prisma.PersonalSavingsPlanWhereInput | Prisma.PersonalSavingsPlanWhereInput[]
  OR?: Prisma.PersonalSavingsPlanWhereInput[]
  NOT?: Prisma.PersonalSavingsPlanWhereInput | Prisma.PersonalSavingsPlanWhereInput[]
  id?: Prisma.UuidFilter<"PersonalSavingsPlan"> | string
  name?: Prisma.StringFilter<"PersonalSavingsPlan"> | string
  description?: Prisma.StringNullableFilter<"PersonalSavingsPlan"> | string | null
  isActive?: Prisma.BoolFilter<"PersonalSavingsPlan"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PersonalSavingsPlan"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PersonalSavingsPlan"> | Date | string
  personalSavings?: Prisma.PersonalSavingsListRelationFilter
}

export type PersonalSavingsPlanOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  personalSavings?: Prisma.PersonalSavingsOrderByRelationAggregateInput
}

export type PersonalSavingsPlanWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.PersonalSavingsPlanWhereInput | Prisma.PersonalSavingsPlanWhereInput[]
  OR?: Prisma.PersonalSavingsPlanWhereInput[]
  NOT?: Prisma.PersonalSavingsPlanWhereInput | Prisma.PersonalSavingsPlanWhereInput[]
  description?: Prisma.StringNullableFilter<"PersonalSavingsPlan"> | string | null
  isActive?: Prisma.BoolFilter<"PersonalSavingsPlan"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PersonalSavingsPlan"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PersonalSavingsPlan"> | Date | string
  personalSavings?: Prisma.PersonalSavingsListRelationFilter
}, "id" | "name">

export type PersonalSavingsPlanOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PersonalSavingsPlanCountOrderByAggregateInput
  _max?: Prisma.PersonalSavingsPlanMaxOrderByAggregateInput
  _min?: Prisma.PersonalSavingsPlanMinOrderByAggregateInput
}

export type PersonalSavingsPlanScalarWhereWithAggregatesInput = {
  AND?: Prisma.PersonalSavingsPlanScalarWhereWithAggregatesInput | Prisma.PersonalSavingsPlanScalarWhereWithAggregatesInput[]
  OR?: Prisma.PersonalSavingsPlanScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PersonalSavingsPlanScalarWhereWithAggregatesInput | Prisma.PersonalSavingsPlanScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"PersonalSavingsPlan"> | string
  name?: Prisma.StringWithAggregatesFilter<"PersonalSavingsPlan"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"PersonalSavingsPlan"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"PersonalSavingsPlan"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PersonalSavingsPlan"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PersonalSavingsPlan"> | Date | string
}

export type PersonalSavingsPlanCreateInput = {
  id?: string
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  personalSavings?: Prisma.PersonalSavingsCreateNestedManyWithoutPlanTypeInput
}

export type PersonalSavingsPlanUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  personalSavings?: Prisma.PersonalSavingsUncheckedCreateNestedManyWithoutPlanTypeInput
}

export type PersonalSavingsPlanUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  personalSavings?: Prisma.PersonalSavingsUpdateManyWithoutPlanTypeNestedInput
}

export type PersonalSavingsPlanUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  personalSavings?: Prisma.PersonalSavingsUncheckedUpdateManyWithoutPlanTypeNestedInput
}

export type PersonalSavingsPlanCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PersonalSavingsPlanUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PersonalSavingsPlanUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PersonalSavingsPlanCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PersonalSavingsPlanMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PersonalSavingsPlanMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PersonalSavingsPlanScalarRelationFilter = {
  is?: Prisma.PersonalSavingsPlanWhereInput
  isNot?: Prisma.PersonalSavingsPlanWhereInput
}

export type PersonalSavingsPlanCreateNestedOneWithoutPersonalSavingsInput = {
  create?: Prisma.XOR<Prisma.PersonalSavingsPlanCreateWithoutPersonalSavingsInput, Prisma.PersonalSavingsPlanUncheckedCreateWithoutPersonalSavingsInput>
  connectOrCreate?: Prisma.PersonalSavingsPlanCreateOrConnectWithoutPersonalSavingsInput
  connect?: Prisma.PersonalSavingsPlanWhereUniqueInput
}

export type PersonalSavingsPlanUpdateOneRequiredWithoutPersonalSavingsNestedInput = {
  create?: Prisma.XOR<Prisma.PersonalSavingsPlanCreateWithoutPersonalSavingsInput, Prisma.PersonalSavingsPlanUncheckedCreateWithoutPersonalSavingsInput>
  connectOrCreate?: Prisma.PersonalSavingsPlanCreateOrConnectWithoutPersonalSavingsInput
  upsert?: Prisma.PersonalSavingsPlanUpsertWithoutPersonalSavingsInput
  connect?: Prisma.PersonalSavingsPlanWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PersonalSavingsPlanUpdateToOneWithWhereWithoutPersonalSavingsInput, Prisma.PersonalSavingsPlanUpdateWithoutPersonalSavingsInput>, Prisma.PersonalSavingsPlanUncheckedUpdateWithoutPersonalSavingsInput>
}

export type PersonalSavingsPlanCreateWithoutPersonalSavingsInput = {
  id?: string
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PersonalSavingsPlanUncheckedCreateWithoutPersonalSavingsInput = {
  id?: string
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PersonalSavingsPlanCreateOrConnectWithoutPersonalSavingsInput = {
  where: Prisma.PersonalSavingsPlanWhereUniqueInput
  create: Prisma.XOR<Prisma.PersonalSavingsPlanCreateWithoutPersonalSavingsInput, Prisma.PersonalSavingsPlanUncheckedCreateWithoutPersonalSavingsInput>
}

export type PersonalSavingsPlanUpsertWithoutPersonalSavingsInput = {
  update: Prisma.XOR<Prisma.PersonalSavingsPlanUpdateWithoutPersonalSavingsInput, Prisma.PersonalSavingsPlanUncheckedUpdateWithoutPersonalSavingsInput>
  create: Prisma.XOR<Prisma.PersonalSavingsPlanCreateWithoutPersonalSavingsInput, Prisma.PersonalSavingsPlanUncheckedCreateWithoutPersonalSavingsInput>
  where?: Prisma.PersonalSavingsPlanWhereInput
}

export type PersonalSavingsPlanUpdateToOneWithWhereWithoutPersonalSavingsInput = {
  where?: Prisma.PersonalSavingsPlanWhereInput
  data: Prisma.XOR<Prisma.PersonalSavingsPlanUpdateWithoutPersonalSavingsInput, Prisma.PersonalSavingsPlanUncheckedUpdateWithoutPersonalSavingsInput>
}

export type PersonalSavingsPlanUpdateWithoutPersonalSavingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PersonalSavingsPlanUncheckedUpdateWithoutPersonalSavingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PersonalSavingsPlanCountOutputType
 */

export type PersonalSavingsPlanCountOutputType = {
  personalSavings: number
}

export type PersonalSavingsPlanCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  personalSavings?: boolean | PersonalSavingsPlanCountOutputTypeCountPersonalSavingsArgs
}

/**
 * PersonalSavingsPlanCountOutputType without action
 */
export type PersonalSavingsPlanCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlanCountOutputType
   */
  select?: Prisma.PersonalSavingsPlanCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PersonalSavingsPlanCountOutputType without action
 */
export type PersonalSavingsPlanCountOutputTypeCountPersonalSavingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PersonalSavingsWhereInput
}


export type PersonalSavingsPlanSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  personalSavings?: boolean | Prisma.PersonalSavingsPlan$personalSavingsArgs<ExtArgs>
  _count?: boolean | Prisma.PersonalSavingsPlanCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["personalSavingsPlan"]>

export type PersonalSavingsPlanSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["personalSavingsPlan"]>

export type PersonalSavingsPlanSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["personalSavingsPlan"]>

export type PersonalSavingsPlanSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PersonalSavingsPlanOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["personalSavingsPlan"]>
export type PersonalSavingsPlanInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  personalSavings?: boolean | Prisma.PersonalSavingsPlan$personalSavingsArgs<ExtArgs>
  _count?: boolean | Prisma.PersonalSavingsPlanCountOutputTypeDefaultArgs<ExtArgs>
}
export type PersonalSavingsPlanIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PersonalSavingsPlanIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PersonalSavingsPlanPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PersonalSavingsPlan"
  objects: {
    personalSavings: Prisma.$PersonalSavingsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["personalSavingsPlan"]>
  composites: {}
}

export type PersonalSavingsPlanGetPayload<S extends boolean | null | undefined | PersonalSavingsPlanDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPlanPayload, S>

export type PersonalSavingsPlanCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PersonalSavingsPlanFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PersonalSavingsPlanCountAggregateInputType | true
  }

export interface PersonalSavingsPlanDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PersonalSavingsPlan'], meta: { name: 'PersonalSavingsPlan' } }
  /**
   * Find zero or one PersonalSavingsPlan that matches the filter.
   * @param {PersonalSavingsPlanFindUniqueArgs} args - Arguments to find a PersonalSavingsPlan
   * @example
   * // Get one PersonalSavingsPlan
   * const personalSavingsPlan = await prisma.personalSavingsPlan.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PersonalSavingsPlanFindUniqueArgs>(args: Prisma.SelectSubset<T, PersonalSavingsPlanFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PersonalSavingsPlanClient<runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPlanPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PersonalSavingsPlan that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PersonalSavingsPlanFindUniqueOrThrowArgs} args - Arguments to find a PersonalSavingsPlan
   * @example
   * // Get one PersonalSavingsPlan
   * const personalSavingsPlan = await prisma.personalSavingsPlan.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PersonalSavingsPlanFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PersonalSavingsPlanFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PersonalSavingsPlanClient<runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPlanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PersonalSavingsPlan that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSavingsPlanFindFirstArgs} args - Arguments to find a PersonalSavingsPlan
   * @example
   * // Get one PersonalSavingsPlan
   * const personalSavingsPlan = await prisma.personalSavingsPlan.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PersonalSavingsPlanFindFirstArgs>(args?: Prisma.SelectSubset<T, PersonalSavingsPlanFindFirstArgs<ExtArgs>>): Prisma.Prisma__PersonalSavingsPlanClient<runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPlanPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PersonalSavingsPlan that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSavingsPlanFindFirstOrThrowArgs} args - Arguments to find a PersonalSavingsPlan
   * @example
   * // Get one PersonalSavingsPlan
   * const personalSavingsPlan = await prisma.personalSavingsPlan.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PersonalSavingsPlanFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PersonalSavingsPlanFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PersonalSavingsPlanClient<runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPlanPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PersonalSavingsPlans that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSavingsPlanFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PersonalSavingsPlans
   * const personalSavingsPlans = await prisma.personalSavingsPlan.findMany()
   * 
   * // Get first 10 PersonalSavingsPlans
   * const personalSavingsPlans = await prisma.personalSavingsPlan.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const personalSavingsPlanWithIdOnly = await prisma.personalSavingsPlan.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PersonalSavingsPlanFindManyArgs>(args?: Prisma.SelectSubset<T, PersonalSavingsPlanFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPlanPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PersonalSavingsPlan.
   * @param {PersonalSavingsPlanCreateArgs} args - Arguments to create a PersonalSavingsPlan.
   * @example
   * // Create one PersonalSavingsPlan
   * const PersonalSavingsPlan = await prisma.personalSavingsPlan.create({
   *   data: {
   *     // ... data to create a PersonalSavingsPlan
   *   }
   * })
   * 
   */
  create<T extends PersonalSavingsPlanCreateArgs>(args: Prisma.SelectSubset<T, PersonalSavingsPlanCreateArgs<ExtArgs>>): Prisma.Prisma__PersonalSavingsPlanClient<runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPlanPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PersonalSavingsPlans.
   * @param {PersonalSavingsPlanCreateManyArgs} args - Arguments to create many PersonalSavingsPlans.
   * @example
   * // Create many PersonalSavingsPlans
   * const personalSavingsPlan = await prisma.personalSavingsPlan.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PersonalSavingsPlanCreateManyArgs>(args?: Prisma.SelectSubset<T, PersonalSavingsPlanCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PersonalSavingsPlans and returns the data saved in the database.
   * @param {PersonalSavingsPlanCreateManyAndReturnArgs} args - Arguments to create many PersonalSavingsPlans.
   * @example
   * // Create many PersonalSavingsPlans
   * const personalSavingsPlan = await prisma.personalSavingsPlan.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PersonalSavingsPlans and only return the `id`
   * const personalSavingsPlanWithIdOnly = await prisma.personalSavingsPlan.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PersonalSavingsPlanCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PersonalSavingsPlanCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPlanPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PersonalSavingsPlan.
   * @param {PersonalSavingsPlanDeleteArgs} args - Arguments to delete one PersonalSavingsPlan.
   * @example
   * // Delete one PersonalSavingsPlan
   * const PersonalSavingsPlan = await prisma.personalSavingsPlan.delete({
   *   where: {
   *     // ... filter to delete one PersonalSavingsPlan
   *   }
   * })
   * 
   */
  delete<T extends PersonalSavingsPlanDeleteArgs>(args: Prisma.SelectSubset<T, PersonalSavingsPlanDeleteArgs<ExtArgs>>): Prisma.Prisma__PersonalSavingsPlanClient<runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPlanPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PersonalSavingsPlan.
   * @param {PersonalSavingsPlanUpdateArgs} args - Arguments to update one PersonalSavingsPlan.
   * @example
   * // Update one PersonalSavingsPlan
   * const personalSavingsPlan = await prisma.personalSavingsPlan.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PersonalSavingsPlanUpdateArgs>(args: Prisma.SelectSubset<T, PersonalSavingsPlanUpdateArgs<ExtArgs>>): Prisma.Prisma__PersonalSavingsPlanClient<runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPlanPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PersonalSavingsPlans.
   * @param {PersonalSavingsPlanDeleteManyArgs} args - Arguments to filter PersonalSavingsPlans to delete.
   * @example
   * // Delete a few PersonalSavingsPlans
   * const { count } = await prisma.personalSavingsPlan.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PersonalSavingsPlanDeleteManyArgs>(args?: Prisma.SelectSubset<T, PersonalSavingsPlanDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PersonalSavingsPlans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSavingsPlanUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PersonalSavingsPlans
   * const personalSavingsPlan = await prisma.personalSavingsPlan.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PersonalSavingsPlanUpdateManyArgs>(args: Prisma.SelectSubset<T, PersonalSavingsPlanUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PersonalSavingsPlans and returns the data updated in the database.
   * @param {PersonalSavingsPlanUpdateManyAndReturnArgs} args - Arguments to update many PersonalSavingsPlans.
   * @example
   * // Update many PersonalSavingsPlans
   * const personalSavingsPlan = await prisma.personalSavingsPlan.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PersonalSavingsPlans and only return the `id`
   * const personalSavingsPlanWithIdOnly = await prisma.personalSavingsPlan.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PersonalSavingsPlanUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PersonalSavingsPlanUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPlanPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PersonalSavingsPlan.
   * @param {PersonalSavingsPlanUpsertArgs} args - Arguments to update or create a PersonalSavingsPlan.
   * @example
   * // Update or create a PersonalSavingsPlan
   * const personalSavingsPlan = await prisma.personalSavingsPlan.upsert({
   *   create: {
   *     // ... data to create a PersonalSavingsPlan
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PersonalSavingsPlan we want to update
   *   }
   * })
   */
  upsert<T extends PersonalSavingsPlanUpsertArgs>(args: Prisma.SelectSubset<T, PersonalSavingsPlanUpsertArgs<ExtArgs>>): Prisma.Prisma__PersonalSavingsPlanClient<runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPlanPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PersonalSavingsPlans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSavingsPlanCountArgs} args - Arguments to filter PersonalSavingsPlans to count.
   * @example
   * // Count the number of PersonalSavingsPlans
   * const count = await prisma.personalSavingsPlan.count({
   *   where: {
   *     // ... the filter for the PersonalSavingsPlans we want to count
   *   }
   * })
  **/
  count<T extends PersonalSavingsPlanCountArgs>(
    args?: Prisma.Subset<T, PersonalSavingsPlanCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PersonalSavingsPlanCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PersonalSavingsPlan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSavingsPlanAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PersonalSavingsPlanAggregateArgs>(args: Prisma.Subset<T, PersonalSavingsPlanAggregateArgs>): Prisma.PrismaPromise<GetPersonalSavingsPlanAggregateType<T>>

  /**
   * Group by PersonalSavingsPlan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSavingsPlanGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PersonalSavingsPlanGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PersonalSavingsPlanGroupByArgs['orderBy'] }
      : { orderBy?: PersonalSavingsPlanGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PersonalSavingsPlanGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPersonalSavingsPlanGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PersonalSavingsPlan model
 */
readonly fields: PersonalSavingsPlanFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PersonalSavingsPlan.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PersonalSavingsPlanClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  personalSavings<T extends Prisma.PersonalSavingsPlan$personalSavingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PersonalSavingsPlan$personalSavingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonalSavingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PersonalSavingsPlan model
 */
export interface PersonalSavingsPlanFieldRefs {
  readonly id: Prisma.FieldRef<"PersonalSavingsPlan", 'String'>
  readonly name: Prisma.FieldRef<"PersonalSavingsPlan", 'String'>
  readonly description: Prisma.FieldRef<"PersonalSavingsPlan", 'String'>
  readonly isActive: Prisma.FieldRef<"PersonalSavingsPlan", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"PersonalSavingsPlan", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PersonalSavingsPlan", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PersonalSavingsPlan findUnique
 */
export type PersonalSavingsPlanFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlan
   */
  select?: Prisma.PersonalSavingsPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavingsPlan
   */
  omit?: Prisma.PersonalSavingsPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSavingsPlanInclude<ExtArgs> | null
  /**
   * Filter, which PersonalSavingsPlan to fetch.
   */
  where: Prisma.PersonalSavingsPlanWhereUniqueInput
}

/**
 * PersonalSavingsPlan findUniqueOrThrow
 */
export type PersonalSavingsPlanFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlan
   */
  select?: Prisma.PersonalSavingsPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavingsPlan
   */
  omit?: Prisma.PersonalSavingsPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSavingsPlanInclude<ExtArgs> | null
  /**
   * Filter, which PersonalSavingsPlan to fetch.
   */
  where: Prisma.PersonalSavingsPlanWhereUniqueInput
}

/**
 * PersonalSavingsPlan findFirst
 */
export type PersonalSavingsPlanFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlan
   */
  select?: Prisma.PersonalSavingsPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavingsPlan
   */
  omit?: Prisma.PersonalSavingsPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSavingsPlanInclude<ExtArgs> | null
  /**
   * Filter, which PersonalSavingsPlan to fetch.
   */
  where?: Prisma.PersonalSavingsPlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PersonalSavingsPlans to fetch.
   */
  orderBy?: Prisma.PersonalSavingsPlanOrderByWithRelationInput | Prisma.PersonalSavingsPlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PersonalSavingsPlans.
   */
  cursor?: Prisma.PersonalSavingsPlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PersonalSavingsPlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PersonalSavingsPlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PersonalSavingsPlans.
   */
  distinct?: Prisma.PersonalSavingsPlanScalarFieldEnum | Prisma.PersonalSavingsPlanScalarFieldEnum[]
}

/**
 * PersonalSavingsPlan findFirstOrThrow
 */
export type PersonalSavingsPlanFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlan
   */
  select?: Prisma.PersonalSavingsPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavingsPlan
   */
  omit?: Prisma.PersonalSavingsPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSavingsPlanInclude<ExtArgs> | null
  /**
   * Filter, which PersonalSavingsPlan to fetch.
   */
  where?: Prisma.PersonalSavingsPlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PersonalSavingsPlans to fetch.
   */
  orderBy?: Prisma.PersonalSavingsPlanOrderByWithRelationInput | Prisma.PersonalSavingsPlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PersonalSavingsPlans.
   */
  cursor?: Prisma.PersonalSavingsPlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PersonalSavingsPlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PersonalSavingsPlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PersonalSavingsPlans.
   */
  distinct?: Prisma.PersonalSavingsPlanScalarFieldEnum | Prisma.PersonalSavingsPlanScalarFieldEnum[]
}

/**
 * PersonalSavingsPlan findMany
 */
export type PersonalSavingsPlanFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlan
   */
  select?: Prisma.PersonalSavingsPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavingsPlan
   */
  omit?: Prisma.PersonalSavingsPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSavingsPlanInclude<ExtArgs> | null
  /**
   * Filter, which PersonalSavingsPlans to fetch.
   */
  where?: Prisma.PersonalSavingsPlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PersonalSavingsPlans to fetch.
   */
  orderBy?: Prisma.PersonalSavingsPlanOrderByWithRelationInput | Prisma.PersonalSavingsPlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PersonalSavingsPlans.
   */
  cursor?: Prisma.PersonalSavingsPlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PersonalSavingsPlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PersonalSavingsPlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PersonalSavingsPlans.
   */
  distinct?: Prisma.PersonalSavingsPlanScalarFieldEnum | Prisma.PersonalSavingsPlanScalarFieldEnum[]
}

/**
 * PersonalSavingsPlan create
 */
export type PersonalSavingsPlanCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlan
   */
  select?: Prisma.PersonalSavingsPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavingsPlan
   */
  omit?: Prisma.PersonalSavingsPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSavingsPlanInclude<ExtArgs> | null
  /**
   * The data needed to create a PersonalSavingsPlan.
   */
  data: Prisma.XOR<Prisma.PersonalSavingsPlanCreateInput, Prisma.PersonalSavingsPlanUncheckedCreateInput>
}

/**
 * PersonalSavingsPlan createMany
 */
export type PersonalSavingsPlanCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PersonalSavingsPlans.
   */
  data: Prisma.PersonalSavingsPlanCreateManyInput | Prisma.PersonalSavingsPlanCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PersonalSavingsPlan createManyAndReturn
 */
export type PersonalSavingsPlanCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlan
   */
  select?: Prisma.PersonalSavingsPlanSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavingsPlan
   */
  omit?: Prisma.PersonalSavingsPlanOmit<ExtArgs> | null
  /**
   * The data used to create many PersonalSavingsPlans.
   */
  data: Prisma.PersonalSavingsPlanCreateManyInput | Prisma.PersonalSavingsPlanCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PersonalSavingsPlan update
 */
export type PersonalSavingsPlanUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlan
   */
  select?: Prisma.PersonalSavingsPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavingsPlan
   */
  omit?: Prisma.PersonalSavingsPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSavingsPlanInclude<ExtArgs> | null
  /**
   * The data needed to update a PersonalSavingsPlan.
   */
  data: Prisma.XOR<Prisma.PersonalSavingsPlanUpdateInput, Prisma.PersonalSavingsPlanUncheckedUpdateInput>
  /**
   * Choose, which PersonalSavingsPlan to update.
   */
  where: Prisma.PersonalSavingsPlanWhereUniqueInput
}

/**
 * PersonalSavingsPlan updateMany
 */
export type PersonalSavingsPlanUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PersonalSavingsPlans.
   */
  data: Prisma.XOR<Prisma.PersonalSavingsPlanUpdateManyMutationInput, Prisma.PersonalSavingsPlanUncheckedUpdateManyInput>
  /**
   * Filter which PersonalSavingsPlans to update
   */
  where?: Prisma.PersonalSavingsPlanWhereInput
  /**
   * Limit how many PersonalSavingsPlans to update.
   */
  limit?: number
}

/**
 * PersonalSavingsPlan updateManyAndReturn
 */
export type PersonalSavingsPlanUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlan
   */
  select?: Prisma.PersonalSavingsPlanSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavingsPlan
   */
  omit?: Prisma.PersonalSavingsPlanOmit<ExtArgs> | null
  /**
   * The data used to update PersonalSavingsPlans.
   */
  data: Prisma.XOR<Prisma.PersonalSavingsPlanUpdateManyMutationInput, Prisma.PersonalSavingsPlanUncheckedUpdateManyInput>
  /**
   * Filter which PersonalSavingsPlans to update
   */
  where?: Prisma.PersonalSavingsPlanWhereInput
  /**
   * Limit how many PersonalSavingsPlans to update.
   */
  limit?: number
}

/**
 * PersonalSavingsPlan upsert
 */
export type PersonalSavingsPlanUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlan
   */
  select?: Prisma.PersonalSavingsPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavingsPlan
   */
  omit?: Prisma.PersonalSavingsPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSavingsPlanInclude<ExtArgs> | null
  /**
   * The filter to search for the PersonalSavingsPlan to update in case it exists.
   */
  where: Prisma.PersonalSavingsPlanWhereUniqueInput
  /**
   * In case the PersonalSavingsPlan found by the `where` argument doesn't exist, create a new PersonalSavingsPlan with this data.
   */
  create: Prisma.XOR<Prisma.PersonalSavingsPlanCreateInput, Prisma.PersonalSavingsPlanUncheckedCreateInput>
  /**
   * In case the PersonalSavingsPlan was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PersonalSavingsPlanUpdateInput, Prisma.PersonalSavingsPlanUncheckedUpdateInput>
}

/**
 * PersonalSavingsPlan delete
 */
export type PersonalSavingsPlanDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlan
   */
  select?: Prisma.PersonalSavingsPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavingsPlan
   */
  omit?: Prisma.PersonalSavingsPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSavingsPlanInclude<ExtArgs> | null
  /**
   * Filter which PersonalSavingsPlan to delete.
   */
  where: Prisma.PersonalSavingsPlanWhereUniqueInput
}

/**
 * PersonalSavingsPlan deleteMany
 */
export type PersonalSavingsPlanDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PersonalSavingsPlans to delete
   */
  where?: Prisma.PersonalSavingsPlanWhereInput
  /**
   * Limit how many PersonalSavingsPlans to delete.
   */
  limit?: number
}

/**
 * PersonalSavingsPlan.personalSavings
 */
export type PersonalSavingsPlan$personalSavingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavings
   */
  select?: Prisma.PersonalSavingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavings
   */
  omit?: Prisma.PersonalSavingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSavingsInclude<ExtArgs> | null
  where?: Prisma.PersonalSavingsWhereInput
  orderBy?: Prisma.PersonalSavingsOrderByWithRelationInput | Prisma.PersonalSavingsOrderByWithRelationInput[]
  cursor?: Prisma.PersonalSavingsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PersonalSavingsScalarFieldEnum | Prisma.PersonalSavingsScalarFieldEnum[]
}

/**
 * PersonalSavingsPlan without action
 */
export type PersonalSavingsPlanDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSavingsPlan
   */
  select?: Prisma.PersonalSavingsPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSavingsPlan
   */
  omit?: Prisma.PersonalSavingsPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSavingsPlanInclude<ExtArgs> | null
}
